# Setup

## Imports

In [2]:
import nfl_data_py as nfl

In [3]:
import os

desktop = os.path.join(os.path.expanduser("~"), "Documents")
filePath = os.path.join(desktop, "LL logo.png")

In [4]:

import pandas as pd
import requests
from pandas import json_normalize
import json
import numpy as np
import re
import altair as alt
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import plotly.express as px
import datetime as dt

from plotly.subplots import make_subplots
import plotly.graph_objects as go
from PIL import Image
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

pd.options.mode.copy_on_write = True

## Plotly Template

In [5]:
def apply_logo_to_fig(fig,xval = .5, yval = -.05):
    """
    Adds a standard logo to the top left of any Plotly figure.
    """

    fig.add_layout_image(
        dict(
            
            source=r"https://raw.githubusercontent.com/bgmaddox/sleeper/master/LL%20logo.png",
            xref="paper", yref="paper",
            x= xval, y= yval,  # Adjusted for better placement
            sizex=0.1, sizey=0.1,
            xanchor="center", yanchor="middle",
            opacity=0.6
        )
    )
    return fig

In [6]:
def ImportPlayerData():
        player_data_response = requests.get('https://api.sleeper.app/v1/players/nfl')
        player_data_json = player_data_response.json()
        return player_data_json

In [7]:
NFLPlayerData = ImportPlayerData()

In [8]:
import plotly.io as pio

# 1. Define the color palette and fonts
ink_bg_color =  '#163146' #'#0D1B2A'
ink_text_color =  '#BDE2FF' #'#A9D6E5'
ink_grid_color =  '#3D5E78' #'#4A6B8A'
ink_secondary_color = '#8DCEFF'
ink_font = 'Courier New'
ink_colorway = ['#AAC49F','#FFBDF9','#234515', '#453215', '#451541', '#5B854A', '#C49FC1', '#C4B59F',
                '#854A7F', '#FFE5BD','#D0FFBD','#856D4A',]
coastal_colorway = [
    '#FFC300', # Gold Amber
    '#17BECF', # Vibrant Teal
    '#F94144', # Coral Red
    '#90BE6D', # Lime Green
    '#E377C2', # Bright Magenta
    '#54A2E5', # Sky Blue
    '#FF7F0E', # Bright Orange
    '#9467BD', # Muted Violet
    '#8C564B', # Muted Brown
    '#43AA8B', # Sea Green
    '#C5B0D5', # Light Lavender
    '#F0F0F0'  # Off-White/Silver
]

neon_future_colorway = [
    '#F92672', # Electric Pink
    '#66D9EF', # Vibrant Cyan
    '#A6E22E', # Lime Green
    '#FD971F', # Tangerine Orange
    '#AE81FF', # Rich Purple
    '#E6DB74', # Bright Yellow
    '#FF0000', # Classic Red
    '#529BFF', # Sky Blue
    '#50E3C2', # Seafoam Green
    '#FF6B00', # Hot Orange
    '#FFC0CB', # Light Pink
    '#F8F8F2', # Bright White
]

autumn_forest_colorway = [
    '#D95F02', # Burnt Orange
    '#1B9E77', # Forest Green
    '#E7A033', # Deep Gold
    '#D73027', # Maroon Red
    '#66A61E', # Olive Green
    '#7570B3', # Slate Blue
    '#008B8B', # Rich Teal
    '#FEC89A', # Muted Peach
    '#B35806', # Terracotta
    '#A1045A', # Plum Purple
    '#FEFAE0', # Warm Cream
    '#B0B0B0', # Cool Grey
]
# 2. Create a new template object
gridiron_ink_template = go.layout.Template()


# 3. Set the layout properties
gridiron_ink_template.layout = go.Layout(
    # --- Main Colors ---
    paper_bgcolor=ink_bg_color,
    plot_bgcolor=ink_bg_color,
    barmode = 'group',
    # --- Fonts ---
    font_family=ink_font,
    font_color=ink_text_color,
    title_font_family='Rockwell',
    title_font_color= '#FFC300', #ink_text_color,
    legend_title_font_color=ink_text_color,
    title=dict(
            font=dict(
                size=45,
                variant="petite-caps",
                shadow = 'auto'
            ),
            xanchor = 'center',
            yanchor = 'bottom',
            x= .50,
            y = .95,
            pad=dict(b=10,t=0,l=0,r=0),
            
            
            ),
    title_subtitle=dict(
            font=dict(
                size=30,
                #variant="small-caps",
                
            )),
    # --- Sizes ---
    width = 1200,
    height=1000,
    uniformtext_minsize=12,
    uniformtext_mode='hide',
    showlegend=False,

    # --- Axes ---
    xaxis=dict(
        side = 'top',
        gridcolor=ink_grid_color,
        linecolor=ink_grid_color,
        zerolinecolor=ink_secondary_color,
        zerolinewidth=3,
        tickfont=dict(
                size=20,
                    ),
         title_font=dict(
                    size=20,
                    shadow = 'auto',
                    color =ink_secondary_color
         ),
       title = dict(standoff = 5),
                  
    ),
    yaxis=dict(
        gridcolor=ink_grid_color,
        linecolor=ink_grid_color,
        zerolinecolor=ink_secondary_color,
        zerolinewidth=3,
        tickfont=dict(
                size=15,
                    ),
        title_font=dict(
                    size=20,
                    shadow='auto',
                    color=ink_secondary_color
         )                  
    ),
    
    # --- Data Colors ---
    colorway = coastal_colorway,
    
    # --- Legend ---
    legend=dict(
        bgcolor='rgba(0,0,0,0)', # Transparent legend background
        bordercolor=ink_grid_color,
        borderwidth=1,
        orientation = 'h',
        yanchor="middle",
        y=1,
        xanchor="center",
        x=.5
    ),

    # --- Margins ---
    margin=dict(t=130, b=100, l= 80, r=40) ,# Add more space for a prominent title


)



gridiron_ink_template.data.bar = [
    go.Bar(
        marker=dict(
            cornerradius=13,
            line_color='#2C4C65', # You can add other marker properties here too
            line_width=3,
            
           ),
           insidetextanchor = 'middle',
           

    )
]


# 4. Register the new theme with Plotly
pio.templates['gridiron_ink'] = gridiron_ink_template

# 5. Set it as the default theme for all future charts
pio.templates.default = 'gridiron_ink'


# --- Example Usage ---
# Now, any chart you create will automatically use your new theme!
fig = go.Figure(data=[
    go.Bar(name='Team A', x=['Week 1', 'Week 2', 'Week 3'], y=[110, 145, 95]),
    go.Bar(name='Team B', x=['Week 1', 'Week 2', 'Week 3'], y=[125, 105, 150])
])

fig.update_layout(
    title_text='Weekly Fantasy Scores',
    xaxis_title='Week',
    yaxis_title='Points'
)


apply_logo_to_fig(fig)


fig.show()

## League Info

### League Numbers

In [9]:
leagueID_2019 = 464552024260734976
leagueID_2020 = 601250643570659328
leagueID_2021 = 726148502706589696
leagueID_2022 = 861038938700255232
leagueID_2023 = 992181788975620096
leagueID_2024 = 1122303756063965184
leagueID_2025 = 1252049821154410496 

Survivor_leagueID_2024 = 1136802217681539072

AllSeasonsList = [leagueID_2019,leagueID_2020,leagueID_2021,leagueID_2022,leagueID_2023,leagueID_2024]

leagueNumbers_Dict = {
    2019 : 464552024260734976,
    2020 : 601250643570659328,
    2021 : 726148502706589696,
    2022 : 861038938700255232,
    2023 : 992181788975620096,
    2024 : 1122303756063965184,
    2025 : 1252049821154410496}
leagueID = leagueID_2023

### Roster IDs

In [10]:
roster_ids_2019 = {1: 'bgmaddox',
 2: 'jlglover',
 3: 'akbrown29',
 4: 'RascalHazard',
 5: 'BMoreBallers88',
 6: 'eegrady',
 7: 'YouthPastor',
 8: 'BillyRayGonnaGetcha',
 9: 'GurlyGirls',
 10: 'SweetDizzzzzle',
 11: 'RossLikeSauce',
 12: 'JTizzzzle'}

In [11]:
roster_ids_2020 = {1: 'bgmaddox',
 2: 'jlglover',
 3: 'JTizzzzle',
 4: 'RascalHazard',
 5: 'BMoreBallers88',
 6: 'eegrady',
 7: 'YouthPastor',
 8: 'jhuntmadd',
 9: 'RReclam',
 10: 'SweetDizzzzzle'}

In [12]:
roster_ids_2021 = {1: 'bgmaddox',
 2: 'jlglover',
 3: 'JTizzzzle',
 4: 'RascalHazard',
 5: 'BMoreBallers88',
 6: 'eegrady',
 7: 'YouthPastor',
 8: 'jhuntmadd',
 9: 'RReclam',
 10: 'SweetDizzzzzle',
 11: 'RossLikeSauce',
 12: 'BillyRayGonnaGetcha'}

In [13]:
roster_ids_2022 = {
 1: 'bgmaddox',
 2: 'jlglover',
 3: 'JTizzzzle',
 4: 'RascalHazard',
 5: 'BMoreBallers88',
 6: 'eegrady',
 7: 'DirtyCommie',
 8: 'jhuntmadd',
 9: 'RReclam',
 10: 'sgmaddox',
 11: 'RossLikeSauce',
 12: 'Just_Here_For_The_Snacks'}

In [14]:
roster_ids_2023 = {1: 'bgmaddox',
 2: 'jlglover',
 3: 'JTizzzzle',
 4: 'RascalHazard',
 5: 'BMoreBallers88',
 6: 'eegrady',
 7: 'DirtyCommie',
 8: 'jhuntmadd',
 9: 'RReclam',
 10: 'sgmaddox',
 11: 'RossLikeSauce',
 12: 'InfiniteJesse'}

In [15]:
roster_ids_2025 = {1: 'bgmaddox',
 2: 'jlglover',
 3: 'JTizzzzle',
 4: 'RascalHazard',
 5: 'BMoreBallers88',
 6: 'eegrady',
 7: 'DirtyCommie',
 8: 'jhuntmadd',
 9: 'cosmodromedary',
 10: 'sgmaddox',
 11: 'RossLikeSauce',
 12: 'InfiniteJesse'}

In [16]:
roster_ids = {2019:roster_ids_2019, 2020:roster_ids_2020, 2021:roster_ids_2021, 2022:roster_ids_2022, 2023:roster_ids_2023,2024:roster_ids_2023, 2025:roster_ids_2025 }

In [17]:
positions = {0:'QB',1:'RB1', 2:'RB2', 3: 'WR1', 4:'WR2',5:'TE',6:'WRT',7:'K',8:'DEF'}
position_list = list(positions.values())

# Classes

## Class: League

In [18]:
class League:
    def __init__(self,year, id):
        self.year = year
        self.id = id
        self.SettingsJSONtoDF()
        
        self.UsersJSONtoDF()
        self.UserSetup()
        
        self.schedule = nfl.import_schedules([year])
        self.ScheduleFormater()
        self.StructureWeekIDs()
        if year != 2025:
            self.WeeklyNFLData = nfl.import_weekly_data([year])
        else:
            self.WeeklyNFLData = pd.read_csv('https://github.com/nflverse/nflverse-data/releases/download/stats_player/stats_player_week_2025.csv')
        self.StructureNFLData()
        self.Rosters = nfl.import_seasonal_rosters([year])
        self.PlayerTeamImport()
        self.Player_Pos_Dict()
        

        print(f'League for {self.year} created.')

    def SettingsJSONtoDF(self):
        league_settings_request = requests.get(f'https://api.sleeper.app/v1/league/{self.id}')
        league_settings_json = league_settings_request.json()
        league_settings_json_normal = json_normalize(league_settings_json)
        self.league_settings = league_settings_json_normal.T.set_axis(['league_setting'], axis=1).to_dict()['league_setting']
    
    def UsersJSONtoDF(self):
        league_user_response = requests.get(f'https://api.sleeper.app/v1/league/{self.id}/users')
        league_user_json = league_user_response.json()

        self.Members = json_normalize(league_user_json)
        self.OwnerIDDict = dict(zip(self.Members.user_id , self.Members.display_name))

    def StructureWeekIDs(self):
        self.schedule['teams'] = self.schedule[['home_team','away_team']].values.tolist()
        self.schedule = self.schedule.explode('teams')
        self.schedule['week_id'] = self.schedule['teams'] + '-' + self.schedule['week'].astype(str)

    def StructureNFLData(self):
        if self.year == 2025:
            self.WeeklyNFLData['recent_team'] = self.WeeklyNFLData['team']
        
        
        self.WeeklyNFLData['week_id'] = self.WeeklyNFLData['recent_team'] + '-' + self.WeeklyNFLData['week'].astype(str)
        
    

    def PlayerTeamImport(self):
        if self.year == 2025:
            self.WeeklyNFLData['recent_team'] = self.WeeklyNFLData['team']
        self.player_team_DF_Import = self.WeeklyNFLData[['player_display_name', 'recent_team']].drop_duplicates()
        self.player_team_DF = self.Rosters[['player_name', 'team']].drop_duplicates()

    
        
    
    def Player_Pos_Dict(self):
        player_df = pd.DataFrame.from_dict(NFLPlayerData, orient='index').reset_index()
        player_df = player_df.rename(columns={'index':'index_id'})
        
        player_mask = player_df['index_id'].astype(str).str.contains('[A-Z]')
        player_df.loc[player_mask,'full_name'] = player_df['index_id']
        player_names = player_df.set_index('player_id').to_dict()['full_name']
        player_pos = player_df.set_index('player_id').to_dict()['position']
        player_names['0'] = "Missing"
        player_names['OAK'] = 'OAK'
        player_pos['0'] = 'Missing'
        
        self.player_df = player_df
        self.player_names = player_names
        self.player_pos = player_pos
    
    def UserSetup(self):
        self.Members = self.Members.reset_index().rename({'index':'player_code'},axis=1)
        self.Members['player_code'] = self.Members['player_code'] + 1
        self.Teams = dict(zip(self.Members.player_code,self.Members.display_name))

    def ImportWeek(self, week):
        week_response = requests.get(f'https://api.sleeper.app/v1/league/{self.id}/matchups/{week}')
        week_json = week_response.json()
        return week_json
    
    def ScheduleFormater(self):
        self.schedule['gametime_gameday'] = self.schedule['gameday'] + ' ' + self.schedule['gametime']
        self.schedule['gametime_gameday'] = self.schedule['gametime_gameday'].apply(lambda x: pd.Period(x, freq='ms'))
        self.schedule['gametime_gameday'] = self.schedule['gametime_gameday'].astype(str)
        
        self.schedule['gametime_gameday'] = pd.to_datetime(self.schedule['gametime_gameday'])
        self.schedule['gametime_gameday_sorting'] = self.schedule['gametime_gameday']

        self.schedule['gametime_format']= self.schedule['gametime'].apply(lambda x: pd.Period(x, freq='ms')).dt.strftime('%I %p')
        self.schedule['weekday_str'] = pd.to_datetime(self.schedule['gameday']).dt.strftime('%a')
        #self.schedule['weekday_str'] = self.schedule['gameday'].dt.strftime('%a')
        self.schedule['gametime_str'] = self.schedule['gametime_format'].astype(str).replace("^0", "", regex=True)
        self.schedule['Tick']= "<b>" + self.schedule['weekday_str']  + '</b><br><sup>' + self.schedule['gametime_str'] + '</sup>'
        self.schedule['gametime_gameday_format'] = self.schedule['gametime_gameday'].dt.strftime('%A %I %p')
        #self.schedule['gametime_gameday_format'] = pd.to_datetime(self.schedule['gametime_gameday_format']).dt.strftime('%A %I %p')
        
        self.schedule = self.schedule.sort_values('gametime_gameday')
        self.ScheduleGroup = self.schedule.groupby('week')

        
    
    def Draft(self):
        draft_id = self.league_settings['draft_id']
        draft_request = requests.get(f'https://api.sleeper.app/v1/draft/{draft_id}/picks')
        draft_json = draft_request.json()
        draft_json_normal = json_normalize(draft_json)
        draft_json_normal.roster_id = draft_json_normal['roster_id'].map(self.Teams)
        draft_json_normal['player_name'] = draft_json_normal['player_id'].map(self.player_names)
        draft_json_normal['year'] = self.year
        self.draft = draft_json_normal
        return self.draft

In [19]:
OptimalScores2019 = {}
OptimalScores2020 = {}
OptimalScores2021 = {}
OptimalScores2022 = {}
OptimalScores2023 = {}
OptimalScores2024 = {}
OptimalScores2025 = {}
OptimalScoresByYear = {2019:OptimalScores2019, 2020:OptimalScores2020, 2021:OptimalScores2021, 2022:OptimalScores2022, 2023:OptimalScores2023, 2024:OptimalScores2024, }

## Class: Week

In [20]:
class Week:
    def __init__(self,week, league):
        self.week = week
        self.league = league
        self.id = self.league.id
        self.year = self.league.year
        
        self.ImportWeek()
        self.WeeklyDataframe()
        self.SetTeamColors()
        self.PlayerBreakout()
        if self.year != 2025: 
            self.OptimalTeams()
        
            self.EfficincyScore()

        
    
    def Update(self):
        self.ImportWeek()
        self.PlayerBreakout()
        self.WeeklyDataframe()
            
    
    def ImportWeek(self):
        week_response = requests.get(f'https://api.sleeper.app/v1/league/{self.id}/matchups/{self.week}')
        week_json = week_response.json()
        self.json = week_json

    def ImportFixes(self):
        self.json
    
    def SetTeamColors(self, color_dict:dict = None):
        self.teamcolors = dict(zip(self.WeeklyNoMatches.sort_values('Team').reset_index().Team.unique(),coastal_colorway))
        
        
        if color_dict != None:
            self.teamcolors = color_dict
    
    def UpdateColors(self ,fig):
        """
        Updates the y-axis tick labels of a figure to use team-specific colors.
        """
        # --- THE FIX ---
        # Instead of 'categoryarray', we get labels directly from the figure's data trace.
        # This is a more reliable way to access the list of teams on the y-axis.
        if not fig.data or fig.data[0].y is None:
            # Failsafe in case the figure has no data
            return fig

        y_axis_labels = fig.data[0].y
        
        # Create a new list of HTML-styled labels with the correct colors.
        styled_labels = []
        for label in y_axis_labels:
            # Look up the color for the team from your dictionary
            color = self.teamcolors.get(label, 'white') # Default to white if not found
            styled_labels.append(f"<span style='color:{color}'>{label}</span>")

        # Update the y-axis to use the new styled text.
        # 'tickvals' provides the original labels to map against.
        # 'ticktext' provides the new, styled labels to display.
        fig.update_yaxes(
            tickvals=y_axis_labels,
            ticktext=styled_labels
        )
                
        return fig
    
    def PlayerBreakout(self):
        # Initialize an empty list to hold the rows
        JSON_data = self.json
        player_data = self.league.player_team_DF
        rows = []
        
        Regular = list(range(1,15))
        Playoff = list(range(15,19))

        WeeklyNFLData = self.league.WeeklyNFLData
        schedule = self.league.schedule
        NFLTeamList =self.league.player_team_DF_Import['recent_team'].unique()

        Defence = pd.DataFrame(NFLTeamList)
        Defence = Defence.rename(columns={0:'player_name'})
        Defence['team'] = NFLTeamList
        
        player_team_DF = pd.concat([player_data,Defence])
        
        player_team_DF['player_name'] = player_team_DF['player_name'].replace(' Jr.','', regex=True).replace(' Sr.','', regex=True).replace(' III','',regex=True).replace(' II','',regex=True)

        
        #Player Corrections
        player_team_DF = player_team_DF.drop(1035)
        player_team_DF = player_team_DF.replace('Marquise Brown','Hollywood Brown')
        player_team_DF = player_team_DF.replace('Audric Estimé','Audric Estime')

        # player_team_DF = player_team_DF.replace('Zonovan Knight','Bam Knight')
        player_team_DF.loc[-1] = ['LAR','LA']

        
        player_team_DF.index = player_team_DF.index+1
        player_team_DF = player_team_DF.sort_index()
        
        for team in JSON_data:
            # Extract relevant information
            matchup_id = team['matchup_id']
            roster_id = team['roster_id']
            players_points = team['players_points']
            starters = team['starters']

            # Iterate through each player and their points
            for player, points in players_points.items():
                # Determine if the player is a starter
                is_starter = player in starters
                
                player_name = self.league.player_names.get(player, player)  # Default to player ID if name not found
                player_positions = self.league.player_pos.get(player, 0)

                # Create a row for each player
                rows.append({
                    'team': roster_id,
                    'matchup': matchup_id,
                    'player': player_name,
                    'points': points,
                    'starter': int(is_starter),
                    'position': player_positions
                })
        
        # Convert the list of rows into a DataFrame
        dfBreakout = pd.DataFrame(rows)
        league_names = roster_ids[self.year]
        dfBreakout['team'] = dfBreakout['team'].replace(league_names)
        dfBreakout['week'] = self.week
        dfBreakout['year'] = self.year
        
        player_team_DF['player_name'] = player_team_DF['player_name'].replace(' Jr.',' Jr', regex=True).replace(' Sr.',' Sr', regex=True).replace(' III','',regex=True).replace(' II','',regex=True)

        dfBreakout = dfBreakout.merge(player_team_DF, left_on='player', right_on='player_name', how = 'left')
        dfBreakout['player_name'] = dfBreakout['player_name'].replace(' Jr.',' Jr', regex=True).replace(' Sr.',' Sr', regex=True).replace(' III','',regex=True).replace(' II','',regex=True)

        dfBreakout['week_id'] = dfBreakout['team_y'] + '-' + dfBreakout['week'].astype(str)
        
        if self.week in Regular:
            dfBreakout['Season'] = 'Regular'
        elif self.week in Playoff:
            dfBreakout['Season'] = 'Playoff'

        dfBreakout['player_week_id'] = dfBreakout['player'] + ' - ' + dfBreakout['week'].astype(str)
        WeeklyNFLData['player_display_name'] = WeeklyNFLData['player_display_name'].replace(' Jr.','', regex=True).replace(' Sr.','', regex=True) \
                                                .replace(' III','',regex=True).replace('Bam Knight','Zonovan Knight', regex=True).replace(' II','',regex=True)
        WeeklyNFLData['player_week_id'] = WeeklyNFLData['player_display_name'] + ' - ' + WeeklyNFLData['week'].astype(str)
        
        
        dfBreakout = dfBreakout.merge(schedule, on = 'week_id', how = 'left')
        dfBreakout = dfBreakout.merge(self.league.Rosters, on= 'player_name',how = 'left')
        
        dfBreakout = dfBreakout.merge(WeeklyNFLData, on = 'player_week_id', how = 'left', suffixes=('','_NFL'))
        dfBreakout['gametime'] = pd.to_datetime(dfBreakout['gametime']).dt.strftime('%I %p')
        dfBreakout['Game_date_time'] = dfBreakout['weekday'] + ' ' + dfBreakout['gametime'].astype(str).replace(r'0', "", regex=True)
        dfBreakout = dfBreakout.rename(columns={'team_x':'team','team_y':'recent_teams'})
        dfBreakout = dfBreakout.loc[:,~dfBreakout.columns.duplicated()].copy()
        if self.year != 2025: dfBreakout['color'] = dfBreakout['team'].map(self.teamcolors)
        
        self.Breakout = dfBreakout
        Breakout_Year_Dict = AllBreakoutDict[self.year]
        Breakout_Year_Dict[self.week] = dfBreakout
        
    
    def WeeklyDataframe(self):
        # Create an empty dictionary to hold the DataFrame data
        df_dict = {}
        matchup_dict = {}

        # Iterate through each team and their data
        for team in self.json:
            roster_id = team["roster_id"]
            starters = team['starters']
            starters_points = team['starters_points']
            matchup_id = team['matchup_id']
            
            # Replace player IDs with player names
            starters_with_names = [self.league.player_names[player] for player in starters]
            
            # Combine players and their points into a list where each entry is a list [dictionary, matchup_id]
            df_dict[roster_id] = [{player: points} for player, points in zip(starters_with_names, starters_points)]
            matchup_dict[roster_id] = matchup_id

        # Create a DataFrame from the dictionary
        WeeklyDf = pd.DataFrame.from_dict(df_dict, orient='index')

        WeeklyDf['Matchup'] = WeeklyDf.index.map(matchup_dict)
        # Define a function to sum the values in the dictionaries in each row
        def sum_points(row):
            total = 0
            for entry in row:
                if isinstance(entry, dict):
                    total += sum(entry.values())
            return total

        league_names = roster_ids[self.year]
        # Apply the function to each row to create the 'Total' column
        WeeklyDf['Total'] = WeeklyDf.apply(sum_points, axis=1)
        WeeklyDf = WeeklyDf.rename(index = league_names)
        
        # Step 1: Group by 'Matchup_ID' and get the maximum 'Total' for each group
        max_scores = WeeklyDf.groupby('Matchup')['Total'].transform('max')
    
    

        # Step 2: Create a new column 'Won' that checks if the team's 'Total' equals the max score
        WeeklyDf['Won'] = WeeklyDf['Total'] == max_scores

        # Step 3: Optional - Convert the boolean 'Won' column to 1 (win) and 0 (loss)
        WeeklyDf['Won'] = WeeklyDf['Won'].astype(int)
        
        
        WeeklyDf['Opp'] = np.where(WeeklyDf['Won'] == 1,WeeklyDf.groupby('Matchup')['Total'].transform('min'),WeeklyDf.groupby('Matchup')['Total'].transform('max'))
        
        WeeklyDf['Margin'] = WeeklyDf['Total'] - WeeklyDf['Opp']
        #WeeklyDf.loc[[WeeklyDf['Won']] == 1,'Opp Score'] = WeeklyDf.groupby('Matchup')['Total'].transform('max')
        #WeeklyDf.loc[[WeeklyDf['Won']] == 0,'Opp Score'] = WeeklyDf.groupby('Matchup')['Total'].transform('min')
        
        
        SeasonMultiplier = {2019:0, 2020:1, 2021:2, 2022:3, 2023:4, 2024:5, 2025:6}
        
        WeeklyDf = WeeklyDf.rename(columns=positions).sort_values('Matchup')
        WeeklyDf = WeeklyDf.reset_index().rename({'index':'Team'}, axis = 1)
        WeeklyDf['Week'] = self.week
        WeeklyDf['Season'] = "Regular" if self.week < 15 else "Playoff"
        WeeklyDf['Week Index'] = self.week + (14 * SeasonMultiplier[self.year])
        WeeklyDf['Year'] = self.year
        
        percent = WeeklyDf.groupby('Week')['Total'].sum()
        percent = percent.reset_index()
        WeekTotal = dict(zip(percent['Week'],percent['Total']))
        
        WeeklyDf['LeagueTotal'] = WeeklyDf['Week'].map(WeekTotal)
        WeeklyDf['PercentTotal'] = ((WeeklyDf['Total'] / WeeklyDf['LeagueTotal']) * 100).round(1)
        # Use groupby to assign the opposing team's name
        #WeeklyDf['Opp_team'] = WeeklyDf.groupby('Matchup')['Team'].transform(lambda x: x.shift(-1) if x.index[0] % 2 == 0 else x.shift(1))
        # Define a function to get the opponent team name for each group
        def get_opponent(teams):
            return teams[::-1]  # Reverse the order so each team gets the other team as opponent

        # Apply the function group-wise to assign opposing teams
        #WeeklyDf['Opp_team'] = WeeklyDf.groupby('Matchup')['Team'].transform(get_opponent)
        # Define a function to assign the opponent team name
        def assign_opponents(group):
            # Assuming there are exactly two teams per matchup
            teams = group['Team'].values
            if len(teams) == 2:  # For valid matchups with two teams
                group['Opp_team'] = [teams[1], teams[0]]  # Swap the teams
            return group

        # Apply the function to each matchup
        WeeklyDf = WeeklyDf.groupby('Matchup',group_keys=False).apply(assign_opponents)
            
        WeeklyDfMatches= WeeklyDf.set_index(['Matchup','Team'])
        WeeklyDfNoMatches = WeeklyDf.set_index('Team')
        WeeklyDfClean = WeeklyDf.set_index('Team').drop(axis = 1,columns = ['Total','Won','Week','Opp','Margin'])
        
        self.WeeklyMatches = WeeklyDfMatches
        self.WeeklyNoMatches = WeeklyDfNoMatches
        self.WeeklyClean = WeeklyDfClean

        Dict_to_Add = AllMatchesDict[self.year]
        Dict_to_Add[self.week] = self.WeeklyNoMatches.reset_index()
        
        
    def OptimalTeams(self):    
        OptimalDF = self.Breakout

        position_counts = {
            'QB': 1,
            'RB': 2,
            'WR': 2,
            'TE': 1,
            'DEF': 1,
            'K': 1
        }
        # Define which positions are eligible for the FLEX spot
        flex_eligible_positions = ['RB', 'WR', 'TE']

        OptGroups = OptimalDF.groupby(['team', 'position'])
        DreamGroups = OptimalDF.groupby('position')
        core_lineup_df = pd.DataFrame()
        dream_lineup_df = pd.DataFrame()

        for name, group in OptGroups:
            position = name[1]
            # Use .get() to safely handle positions not in your dictionary (e.g., FLEX)
            # It will default to 0 if the position isn't found.
            num_players = position_counts.get(position, 0)

            if num_players > 0:
                topPlayers = group.sort_values('points', ascending=False).head(num_players)
                core_lineup_df = pd.concat([core_lineup_df, topPlayers])

        for position, group in DreamGroups:
            position = name[1]
            
            num_players = position_counts.get(position, 0)

            if num_players > 0:
                dreamPlayers = group.sort_values('points', ascending=False).head(num_players)
                dream_lineup_df = pd.concat([dream_lineup_df, dreamPlayers])

        # Create a pool of players who are NOT in the core lineup
        flex_pool_df = OptimalDF.drop(core_lineup_df.index)
        flex_dream_pool_df = OptimalDF.drop(dream_lineup_df.index)

        # Filter this pool to only include FLEX-eligible positions
        flex_pool_df = flex_pool_df[flex_pool_df['position'].isin(flex_eligible_positions)]
        flex_dream_pool_df = flex_dream_pool_df[flex_dream_pool_df['position'].isin(flex_eligible_positions)]

        # For each team, find the single highest-scoring player in the flex_pool_df
        # The .loc[...idxmax()] pattern is a very efficient way to do this
        flex_players_df = flex_pool_df.loc[flex_pool_df.groupby('recent_team')['points'].idxmax()]
        flex_dream_pool_df = flex_dream_pool_df.loc[flex_dream_pool_df['points'].idxmax()]

        # For clarity, let's add a column to show where each player started
        core_lineup_df['starting_position'] = core_lineup_df['position']
        flex_players_df['starting_position'] = 'FLEX'
        dream_lineup_df['starting_position'] = dream_lineup_df['position']
        flex_dream_pool_df['starting_position'] = 'FLEX'

        # Concatenate the two DataFrames to get the final, complete optimal lineup
        final_optimal_lineup = pd.concat([core_lineup_df, flex_players_df])
        if self.year != 2025:
            final_dream_team = pd.concat([dream_lineup_df, flex_dream_pool_df])
            self.DreamTeamDF = final_dream_team

        # Sort for a clean final view
        final_optimal_lineup = final_optimal_lineup.sort_values(
            by=['recent_team', 'starting_position'], 
            ascending=True
        )

        self.OptimalScoresDict = dict(final_optimal_lineup.groupby('team')['points'].sum().round(2))
        self.OptimalScoresDF = final_optimal_lineup
        


    def EfficincyScore(self):
        self.OptimalTeams()
        self.Scores = self.WeeklyNoMatches.to_dict()['Total']
        eff_score = {}
        for team , score in self.Scores.items():
            eff_score[team] = ((score / self.OptimalScoresDict[team]) * 100).round(1)
        
        self.efficiency = eff_score
        Dict_to_Add_To = OptimalScoresByYear[self.year]
        Dict_to_Add_To[self.week] = self.OptimalScoresDF
        
    def LuckScore(self):
        SeasonObject = Season_Dict[self.year]
        WeekRange = [1,self.week+1]
        Season = SeasonObject.Matches
        Season = Season[Season['Week'].isin(WeekRange)]
        self.AverageScores = Season.groupby('Team')['Total'].mean().round(1).rename('Averages')   

        Averages = self.AverageScores
        Scores = self.WeeklyNoMatches['Total'].round(1)
        Combo = pd.concat([Averages, Scores], axis = 1)
        Combo['Luck'] = (Combo['Total'] - Combo['Averages']).round(1)
        self.LuckScores = Combo
        

    #
    # GRAPHS
    #

    def WeeklyGraph(self):
    
        #points = MatchDF.drop(axis = 1,columns = ['Total','Won','Week','Opp','Margin']).applymap(lambda if isinstance(x,dict): float(list(x.values())[0]))
        points = self.WeeklyMatches.applymap(lambda x: float(list(x.values())[0]) if isinstance(x, dict) else x)
        points = points.round(2).reset_index()
        
        fig1 = px.bar(points, y='Team',x=position_list,template = 'gridiron_ink',color = "Matchup", barmode='group',text_auto=True, 
                      title = f'<b>Week {self.week} Matchups</b><br><sup>QB → DEF</sup>', orientation='h',
                      color_continuous_scale=px.colors.diverging.Portland)
        
        #Update the layout to hide the legend:
        fig1.update(layout_coloraxis_showscale=False)
        
        # Adjust the figure size
        fig1.update_layout(width=800, height=1200)
        
        fig1.update_traces(textfont_size=12, textangle=0, cliponaxis=True, textposition = 'inside', textfont=dict(weight='bold',  # Font family
                size=12   # Font color
            ))
        
        # Customize the x-axis labels
        fig1.update_xaxes(
            tickfont=dict(
                size=16,         # Font size
            ),
            title = None
        )

        # Customize the y-axis labels
        fig1.update_yaxes(
            tickfont=dict(
                size=18, weight = 'bold'         # Font size
            ),
            title=None
        )

        fig1.add_annotation(
        text="VS.",
        xref="paper", yref="paper",
        x=-.1, y=.93, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            size=15,
            color="magenta",
            weight ='bold'
        ))

        fig1.add_annotation(
        text="VS.",
        xref="paper", yref="paper",
        x=-.1, y=.76, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            size=15,
            color="magenta",
            weight ='bold'
        )
        )

        fig1.add_annotation(
        text="VS.",
        xref="paper", yref="paper",
        x=-.1, y=.58, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            size=15,
            color="magenta",
            weight ='bold'
        )
        )

        fig1.add_annotation(
        text="VS.",
        xref="paper", yref="paper",
        x=-.1, y=.41, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            size=15,
            color="magenta",
            weight ='bold'
        )
        )

        fig1.add_annotation(
        text="VS.",
        xref="paper", yref="paper",
        x=-.1, y=.24, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            size=15,
            color="magenta",
            weight ='bold'
        )
        )

        fig1.add_annotation(
        text="VS.",
        xref="paper", yref="paper",
        x=-.1, y=.07, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            size=15,
            color="magenta",
            weight ='bold'
        )
        )

        
        fig1.update_traces(marker_line_width=2,marker_line_color='black')
        
        fig1.update_traces(insidetextanchor= 'middle')
        fig1.update_layout(
            uniformtext_minsize=12,
            uniformtext_mode='hide'
            )
        
        fig1.update_layout(margin=dict(t=120, b=90, l=170, r=40))
        
        apply_logo_to_fig(fig1,xval=.4,yval = -0.04)
        self.UpdateColors(fig1)
        
        return fig1
        
   
    
    def PointsOverTheWeekend(self, Alternate=None):    
        breakoutDF = self.Breakout
        week_num = self.week

        title_string = f'<b>Points Timeline</b><br><sup>Week {week_num}</sup>'

        TimeAreaDF = breakoutDF[breakoutDF['starter'] == 1]

        
        TimeAreaDF = TimeAreaDF.sort_values('gametime_gameday')

        TimeAreaDFGraph = TimeAreaDF.groupby(['matchup','team','gametime_gameday_format'],
                                             sort='gametime_gameday').agg({'points':'sum','gametime_gameday':'first','Game_date_time':'first' ,'Tick':'first'}).reset_index()
        

        TimeAreaDFGraph['ScoreTally'] = TimeAreaDFGraph.sort_values('gametime_gameday',ascending=True).groupby(['team']).points.cumsum()
        TimeAreaDFGraph = TimeAreaDFGraph.sort_values('gametime_gameday')

        TeamNames = TimeAreaDFGraph.groupby('matchup').team.unique().reset_index()
        TeamNames['MatchupTitle'] = TeamNames.team.str.join(' vs ')
        MatchupNames = dict(zip(TeamNames.matchup, TeamNames.MatchupTitle))
        TimeAreaDFGraph['MatchupTitle'] = TimeAreaDFGraph.matchup.map(MatchupNames)
        ## NEED TO FIGURE OUT THE SORTING OF THE GAMES BEFORE THE CUMULATION IS DONE

        GameList = self.league.ScheduleGroup.get_group(self.week)['gametime_gameday_format'].unique().tolist()
        TickList = self.league.ScheduleGroup.get_group(self.week)['Tick'].unique().tolist()
        self.GametimeList = TimeAreaDFGraph['gametime_gameday_format'].unique()
       
        self.TickList = TickList
        GametimeList = self.GametimeList
        GameListLen = len(GameList)
            
        TimeAreaDFGraph['color'] = TimeAreaDFGraph['team'].map(self.teamcolors) 

        figWeekLine = px.area(TimeAreaDFGraph.sort_values(['matchup','gametime_gameday']), x='gametime_gameday_format', y = 'ScoreTally',color = 'team',color_discrete_map=self.teamcolors, 
                              template = 'gridiron_ink', 
                            facet_col='MatchupTitle', facet_col_wrap=2,  facet_col_spacing=0.10,  facet_row_spacing=0.10, title=title_string, markers=True)
        figWeekLine.update_layout(height=1200, width = 1000)
       
        figWeekLine.update_traces(stackgroup=None,fill='tozeroy', line_shape = 'spline')
        figWeekLine.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
        figWeekLine.update_layout(showlegend=False)
        figWeekLine.update_xaxes(title_text="", side = 'bottom',tickfont=dict(size=20),
                                 ticktext=TimeAreaDFGraph['Tick'], tickvals = TimeAreaDFGraph['gametime_gameday_format'])
        
        # Update facet titles to include team colors
        for annotation in figWeekLine.layout.annotations:
            title_text = annotation.text  # e.g., "Team A vs Team B"
            teams = title_text.split(" vs ")  # Split into individual team names
            # Create a styled title with team names in respective colors
            annotation.text = f"<span style='color:{self.teamcolors[teams[0]]}'>{teams[0]}</span> vs " \
                            f"<span style='color:{self.teamcolors[teams[1]]}'>{teams[1]}</span>"
            annotation.font.size = 23  # Optional: Adjust font size for clarity

        
        # hide subplot y-axis titles and x-axis titles
        for axis in figWeekLine.layout:
            if type(figWeekLine.layout[axis]) == go.layout.YAxis:
                figWeekLine.layout[axis].title.text = ''
            if type(figWeekLine.layout[axis]) == go.layout.XAxis:
                figWeekLine.layout[axis].title.text = ''
        figWeekLine.update_yaxes( showticklabels=True, visible=True)
        figWeekLine.update_xaxes( showticklabels=True, visible=True,ticktext=TickList)
        TimeAreaDFGraph = TimeAreaDFGraph.sort_values('gametime_gameday')

        figWeekLine.update_layout(
            xaxis=dict(ticktext=TimeAreaDFGraph['Tick'], tickvals = TimeAreaDFGraph['gametime_gameday_format']),
            xaxis1=dict(ticktext=TimeAreaDFGraph['Tick'], tickvals = TimeAreaDFGraph['gametime_gameday_format']),
            xaxis2=dict(ticktext=TimeAreaDFGraph['Tick'], tickvals = TimeAreaDFGraph['gametime_gameday_format']),
            xaxis3=dict(ticktext=TimeAreaDFGraph['Tick'], tickvals = TimeAreaDFGraph['gametime_gameday_format']),
            xaxis4=dict(ticktext=TimeAreaDFGraph['Tick'], tickvals = TimeAreaDFGraph['gametime_gameday_format']),
            xaxis5=dict(ticktext=TimeAreaDFGraph['Tick'], tickvals = TimeAreaDFGraph['gametime_gameday_format']),
            xaxis6=dict(ticktext=TimeAreaDFGraph['Tick'], tickvals = TimeAreaDFGraph['gametime_gameday_format']),
            )
        figWeekLine.update_layout(xaxis=dict(categoryorder='array',categoryarray =self.GametimeList))

        self.TimeAreaData = TimeAreaDFGraph

        figWeekLine.update_layout(margin=dict(t=120, b=90, l=50, r=50))
        
        apply_logo_to_fig(figWeekLine,xval=0,yval = 1.06)
        
        return figWeekLine

## Class: Season

In [21]:
Matches_2019 = {}
Matches_2020 = {}
Matches_2021 = {}
Matches_2022 = {}
Matches_2023 = {}
Matches_2024 = {}
Matches_2025 = {}


Breakout_Matches_2019 = {}
Breakout_Matches_2020 = {}
Breakout_Matches_2021 = {}
Breakout_Matches_2022 = {}
Breakout_Matches_2023 = {}
Breakout_Matches_2024 = {}
Breakout_Matches_2025 = {}


AllBreakoutDict = {2019:Breakout_Matches_2019,2020:Breakout_Matches_2020,2021:Breakout_Matches_2021,2022:Breakout_Matches_2022,2023:Breakout_Matches_2023,
                   2024:Breakout_Matches_2024,2025:Breakout_Matches_2025}
AllMatchesDict = {2019:Matches_2019, 2020:Matches_2020, 2021:Matches_2021, 2022:Matches_2022, 2023:Matches_2023, 2024:Matches_2024, 2025:Matches_2025, }

In [22]:
class Season:
    def __init__(self, league):
        self.league = league
        self.id = self.league.id
        self.year = self.league.year
        
        
        print(f'Season for {self.year} created.')
    
    def Update(self):
        self.AllMatchesConcat()
        self.BreakoutConcat()
        
        #self.CalculateAverages()
        self.SetTeamColors()
        print(f'Season has been udpated.')
    
    def BreakoutConcat(self, last_week = None):
        # Filter out the dataframes corresponding to months up to and including the current month
        df_dict = AllBreakoutDict[self.year]
        if last_week != None:
            Week = last_week
        else:
            Week = 17
        dataframes_to_concat = [df_dict[week] for week in range(1, Week + 1)]
        self.Breakout_dict = df_dict
        # Concatenate the selected dataframes
        Weeks= pd.concat(dataframes_to_concat, axis=0)
        
        Weeks['Score YTD'] = Weeks.groupby('player')['points'].cumsum()
        Weeks['TotalYTD'] = Weeks.groupby('player')['points'].transform('sum')
        Weeks['Year'] = self.year

        self.BreakoutSeason = Weeks
        
        self.Starters = Weeks[Weeks['starter'] == 1]

    def SetBest(self,TotalYTD):
        self.Best = self.BreakoutSeason[self.BreakoutSeason['TotalYTD'] > TotalYTD]
        print(f'Best set at {self.Best}')

    def SetTeamColors(self, color_dict:dict = None):
        self.teamcolors = dict(zip(self.Matches.sort_values('Team').reset_index().Team.unique(),coastal_colorway))
        
        
        if color_dict != None:
            self.teamcolors = color_dict
        
    def UpdateColors(self ,fig):
        """
        Updates the y-axis tick labels of a figure to use team-specific colors.
        """
        # --- THE FIX ---
        # Instead of 'categoryarray', we get labels directly from the figure's data trace.
        # This is a more reliable way to access the list of teams on the y-axis.
        if not fig.data or fig.data[0].y is None:
            # Failsafe in case the figure has no data
            return fig

        y_axis_labels = fig.data[0].y
        
        # Create a new list of HTML-styled labels with the correct colors.
        styled_labels = []
        for label in y_axis_labels:
            # Look up the color for the team from your dictionary
            color = self.teamcolors.get(label, 'white') # Default to white if not found
            styled_labels.append(f"<span style='color:{color}'>{label}</span>")

        # Update the y-axis to use the new styled text.
        # 'tickvals' provides the original labels to map against.
        # 'ticktext' provides the new, styled labels to display.
        fig.update_yaxes(
            tickvals=y_axis_labels,
            ticktext=styled_labels
        )
                
        return fig

    def AllMatchesConcat(self):
        
        MatchDictionary = AllMatchesDict[self.year]
        self.Matches = pd.concat(MatchDictionary.values())
        
    def CalculateAverages(self, WeekNum):
        df = self.Matches[self.Matches['Week'].isin(range(0,WeekNum+1))]
        self.AverageScores = df.groupby('Team')['Total'].mean().round(1).rename('Averages')   
        return self.AverageScores
        
    
    def WeeklyWins(self, last_week = None):
        Weeks = self.Matches

        if last_week != None:    
            # Filter out the dataframes corresponding to months up to and including the current month
            df_dict = AllMatchesDict[self.year]
                            
            dataframes_to_concat = [df_dict[week] for week in range(1, last_week + 1)]
        
            # Concatenate the selected dataframes
            Weeks = pd.concat(dataframes_to_concat, axis=0)
        
        Weeks['Total Wins'] = Weeks.groupby('Team')['Won'].cumsum()

        Weeks['Score YTD'] = Weeks.groupby('Team')['Total'].cumsum()

        Weeks['Opp YTD'] = Weeks.groupby('Team')['Opp'].cumsum()
        
        Week_Pivot = Weeks.pivot(index = 'Team', columns = 'Week',values = 'Total Wins')
        
        self.Week_Pivot = Week_Pivot
        self.ConcatinatedWeeks = Weeks

    def OptimalTeams(self):    
        OptimalDF = self.BreakoutSeason.groupby(['team', 'player', 'position'])['points'].sum().reset_index()
        DreamDF = self.BreakoutSeason.groupby(['team', 'position','player'])['points'].sum().reset_index()

        position_counts = {
            'QB': 1,
            'RB': 2,
            'WR': 2,
            'TE': 1,
            'DEF': 1,
            'K': 1
        }
        # Define which positions are eligible for the FLEX spot
        flex_eligible_positions = ['RB', 'WR', 'TE']
        num_flex_spots = 1

        OptGroups = OptimalDF.groupby(['team', 'position'])
        DreamGroups = OptimalDF.groupby(['position'])

        core_lineup_df = pd.DataFrame()
        dream_lineup_df = pd.DataFrame()

        final_optimal_lineup_list = []

        # Process each team individually
        for team_name, team_df in OptimalDF.groupby('team'):
            
            # --- Part A: Handle the non-FLEX positions (QB, K, DEF) ---
            non_flex_starters = pd.DataFrame()
            for pos in ['QB', 'K', 'DEF']:
                # Find the best player for the team at that position
                top_player = team_df[team_df['position'] == pos].nlargest(position_counts[pos], 'points')
                non_flex_starters = pd.concat([non_flex_starters, top_player])

            # --- Part B: Handle the combined RB/WR/TE/FLEX pool ---
            
            # Create one big pool of all FLEX-eligible players for the team
            flex_pool = team_df[team_df['position'].isin(flex_eligible_positions)]
            
            # Determine the total number of starters to take from this pool
            total_flex_group_spots = (position_counts['RB'] + 
                                    position_counts['WR'] + 
                                    position_counts['TE'] + 
                                    num_flex_spots)

            # Find the best N players from this combined pool
            top_flex_group_players = flex_pool.nlargest(total_flex_group_spots, 'points')
            
            # --- Part C: Combine and build the team's final optimal lineup ---
            team_optimal_lineup = pd.concat([non_flex_starters, top_flex_group_players])
            final_optimal_lineup_list.append(team_optimal_lineup)
        
        # Combine the optimal lineups from all teams into one DataFrame
        final_optimal_lineup = pd.concat(final_optimal_lineup_list)
        
        ####Dream Team
        dream_team_core = pd.DataFrame()
        for position, count in position_counts.items():
            positional_players = DreamDF[DreamDF['position'] == position]
            top_players = positional_players.sort_values('points', ascending=False).head(count)
            dream_team_core = pd.concat([dream_team_core, top_players])

        # Create a pool of players who are NOT in the core lineup
      
        flex_dream_pool_df = DreamDF.drop(dream_team_core.index)

        # Filter this pool to only include FLEX-eligible positions
       
        flex_dream_pool_df = flex_dream_pool_df[flex_dream_pool_df['position'].isin(flex_eligible_positions)]

        # For each team, find the single highest-scoring player in the flex_pool_df
        # The .loc[...idxmax()] pattern is a very efficient way to do this
        
        flex_dream_pool_df = flex_dream_pool_df.sort_values('points', ascending=False).head(1)

        # For clarity, let's add a column to show where each player started
        
        dream_team_core['starting_position'] = dream_team_core['position']
        flex_dream_pool_df['starting_position'] = 'FLEX'

        # Concatenate the two DataFrames to get the final, complete optimal lineup
        final_dream_team = pd.concat([dream_team_core, flex_dream_pool_df])

        # Sort for a clean final view
        final_optimal_lineup = final_optimal_lineup.sort_values(
            by=['team', 'position'], 
            ascending=True
        )

        self.OptimalScoresDict = dict(final_optimal_lineup.groupby('team')['points'].sum().round(2))
        self.OptimalScoresDF = final_optimal_lineup
        self.DreamTeamDF = final_dream_team

         
    
    def EfficincyScore(self):
        self.OptimalTeams()
        OptScoresYear = OptimalScoresByYear[self.year]
        OptScores = pd.concat(OptScoresYear.values())
        self.Scores = dict(OptScores.groupby('team')['points'].sum())
        eff_score = {}
        for team , score in self.Scores.items():
            eff_score[team] = ((score / self.OptimalScoresDict[team]) * 100).round(1)
        
        self.efficiency = eff_score
        


    def PlayerTrends(self):
        WonGraph = self.Matches.pivot(columns = 'Week',index='Team',values = 'Won')
        WonGraph = WonGraph.replace(0,'L').replace(1,'W')
        last_five_cols = WonGraph.columns[-5:]
        
        WonGraph['Trend'] = WonGraph[last_five_cols].apply(lambda row: ' '.join(row.astype(str)), axis=1)
        self.WonGraph = WonGraph.reset_index()
        self.PlayerTrend = dict(zip(WonGraph.Team, WonGraph.Trend))
        
    def ScoreTrends(self):
        ScoreTrends = round(self.Matches.groupby('Week')['Total'].agg(['min','mean','max']),2)
        self.ScoreTrends = ScoreTrends
        
        figTrends = px.line(ScoreTrends.reset_index(), x='Week', y = ['min','max','mean'], template = 'gridiron_ink',line_shape = 'spline', title = 'Scoring Trends', markers=True )
        figTrends.update_layout(
            yaxis=dict(
                range=[0, 180]  # Set the y-axis range from 0 to 10
            )
        )
        figTrends.update_layout(width=1200, height=800)
        figTrends.update_layout(font_family="Courier New", title_font = dict(size=45))
        figTrends.update_yaxes(
                tickfont=dict(
                    family='Courier New',  # Font family
                    size=15,         # Font size
                    color='white'    # Font color
                ),
                title = None,
                
            )
        figTrends.update_xaxes(
                tickfont=dict(
                    family='Courier New',  # Font family
                    size=15,         # Font size
                    color='white'    # Font color
                ),
                title = 'Week',
                
            )
        figTrends.update_layout(legend=dict(orientation="h",font=dict(size= 18)))
        # Set legend location
        figTrends.update_layout(
            legend=dict(
                x=0.45,  # x-coordinate of the legend (0 to 1, where 0 is left and 1 is right)
                y=1.02,   # y-coordinate of the legend (0 to 1, where 0 is bottom and 1 is top)
                xanchor="center",  # horizontal anchor point ('left', 'center', 'right')
                yanchor="top",   # vertical anchor point ('top', 'middle', 'bottom')
                title = None
            )
        )
        figTrends.show()
    
    def PowerRankings(self, week):
        df = self.Matches
        PlayerNum = 12

        df['Week Rank'] = df.groupby('Week')['Total'].rank().astype(int) - 1
        df = df[df['Week'] <= week]
        df['Power YTD'] = df.groupby('Team')['Week Rank'].cumsum().astype(int)
        df['Power Loss YTD'] = (df['Week'] * (PlayerNum-1) - df['Power YTD']).astype(int)
        #df['Win Percentage'] = (df['Power YTD']/(df['Week'] * week))
        df['Win Percentage'] = (df['Power YTD']/(df['Power YTD'] + df['Power Loss YTD']))
        df['Power Ranking'] = df.groupby('Week')['Win Percentage'].rank(ascending=False).astype(int)
        self.PowerRanks = df[df["Week"]== week]
        self.PowerRankDict = dict(zip(self.PowerRanks['Team'],self.PowerRanks['Power Ranking']))
        self.PowerPercentDict = dict(zip(self.PowerRanks['Team'],self.PowerRanks['Win Percentage']))


        return self.PowerRanks
        
        
    def Calc(self, WeekObj, team = None):
        self.PowerRankings(WeekObj.week)
        week = WeekObj.week
        WeeklyMatchYTD = self.Matches[self.Matches['Week'] <= week]
        

        Scores = dict(self.Matches[self.Matches['Week']== week].set_index('Team').Total.round(1))
        
        AverageScores = dict(self.CalculateAverages(week))

        LeagueAverage = WeeklyMatchYTD.Total.mean().round(1)

        ThisWeek = self.PowerRankings(week)
        PowerPercentDict = dict(zip(ThisWeek['Team'],ThisWeek['Win Percentage']))
        PowerRanks = dict(zip(ThisWeek['Team'],ThisWeek['Power Ranking']))

        

        if week != 1:
            LastWeek = self.PowerRankings(week - 1)
            
            PreviousRanks = dict(zip(LastWeek['Team'],LastWeek['Power Ranking']))
        else:
            PreviousRanks = self.PowerRankDict

        

        WeekObj.OptimalTeams()
        OptimalScores = WeekObj.OptimalScoresDict
        
        if team != None:
            team_score = Scores[team]
            team_average = AverageScores[team]
            Power = PowerPercents[team]
            CurrentRank = PowerRanks[team]
            PreviousRank = PreviousRanks[team]


        self.StatusDict = {'Scores':Scores, 'AverageScores':AverageScores, 'LeagueAverage' : LeagueAverage, 'PowerRanks': PowerRanks, 'PreviousRanks': PreviousRanks,
                      'PowerPercents':PowerPercentDict, 'OptimalScores': OptimalScores} 
          
    
    def SnakeGraph(self, week):
        self.WeeklyWins(week)
        df = self.ConcatinatedWeeks
        unique_teams = df['Team'].unique()
        week_zero_df = pd.DataFrame({
            'Team': unique_teams,
            'Week': 0,
            'Total Wins': 0
        })
        df = pd.concat([df,week_zero_df], ignore_index=True,)
        df = df.sort_values('Week', ascending=True)
        
        fig2 = px.line(df,x='Week',y='Total Wins', color = 'Team',template='gridiron_ink',line_shape = 'spline', title = 'Win Progression')
        fig2.update_xaxes(dtick=1,
                        tickfont=dict(
                size=18,         # Font size
            ))
        fig2.update_yaxes(dtick=1)
        fig2.update_layout(width=1200, height=800)
        # Adjust the thickness of the lines
        fig2.update_traces(line=dict(width=4))  # Set the line width (e.g., 3 pixels)
        fig2.update_layout(legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1,
            title = ''
        ))

        
        # Customize the y-axis labels
        fig2.update_yaxes(
            tickfont=dict(
                size=20,         # Font size
            )
        )

        fig2.update_layout(uniformtext_minsize=10, uniformtext_mode='hide')

        # Update x-axis and y-axis titles with font customization
        fig2.update_layout(
            xaxis_title="Week",  # Set x-axis title
            yaxis_title="Wins",   # Set y-axis title
            xaxis=dict(
                title_font=dict(
                    size=20          # Set font size for x-axis title
                )
            ),
            yaxis=dict(
                title_font=dict(
                    size=20          # Set font size for y-axis title
                )
            )
        )
        
        # Determine final wins and sort by them
        final_scores = [(d.name, d.x[-1], d.y[-1], d.line.color) for d in fig2.data]
        final_scores.sort(key=lambda x: -x[2])  # Sort by final win count, descending

        # Define a list of potential text positions to avoid overlap
        text_positions = ['middle right','top right', 'bottom right', 'top left', 'bottom left', 'middle left','top center','bottom center']

        previous_score = None
        position_index = 0

        for team_name, x_final, y_final, color in final_scores:
            if y_final == previous_score:
                # Cycle through text positions to avoid overlap if scores are the same
                position_index = (position_index + 1) % len(text_positions)
            else:
                position_index = 0  # Reset position index when score changes

            text_position = text_positions[position_index]
            previous_score = y_final

            fig2.add_scatter(
                x=[x_final], y=[y_final],
                mode='markers+text',
                text=[team_name],
                textfont=dict(color=color, size=14, weight = 'bold'),
                textposition=text_position,
                marker=dict(color=color, size=12),
                showlegend=False
                )    
        fig2.update_layout(margin=dict(l=80, r=80, t=120, b=80))  # Set left, right, top, bottom padding within the plot area
                                
        fig2.update_layout(xaxis=dict(range=[0, week + 1.5])) 
        fig2.update_layout(title = dict(y=.93)
        )
        
        apply_logo_to_fig(fig2)

        return fig2   
    
    def LuckChart(self, current_week):
        
        self.WeeklyWins(current_week)
        df_wins = self.ConcatinatedWeeks
        

        df_week = df_wins[df_wins['Week'] == current_week]
        topscore = df_week['Score YTD'].max()
        topopponent = df_week['Opp YTD'].max()
        minscore = df_week['Score YTD'].min()
        minopponent = df_week['Opp YTD'].min()

        figScat = px.scatter(df_week, x="Opp YTD",y = 'Score YTD',size ="Total Wins", template = 'gridiron_ink', color = 'Team', text = 'Team',title=f'<b>Lucky Squares</b><br><sup>Week {current_week}</sup>')
        figScat.update_layout(width=800, height=800)


        # Calculate median values
        median_score = df_week['Score YTD'].median() #y value
        median_opp = df_week['Opp YTD'].median() #x value
        
        # Add horizontal and vertical lines to divide the plot into quadrants
        figScat.add_shape(type="line", x0=median_opp, x1=median_opp, 
                    y0=df_week['Score YTD'].min()-15, y1=df_week['Score YTD'].max()+15
                    , opacity=0.5,
                    line=dict(color="gold", width=2, dash="dash"))

        figScat.add_shape(type="line", x0=df_week['Opp YTD'].min()-15, x1=df_week['Opp YTD'].max()+15, 
                    y0=median_opp, y1=median_opp, opacity=0.5,
                    line=dict(color="gold", width=2, dash="dash"))

        figScat.update_traces(textposition='top center')
        figScat.update_traces(textfont_size=15,textfont=dict(weight='bold',  # Font family
                size=15   # Font color
            ))
        figScat.update_layout(showlegend=False)
        # Add the diagonal line
        #figScat.update_layout(shapes = [{'type': 'line', 'yref': 'paper', 'xref': 'paper', 'y0': 0, 'y1': 1, 'x0': 0, 'x1': 1}])

        # Add text to each corner
        figScat.add_annotation(x=0, y=0, text="Bad but Lucky", showarrow=False, xref="paper", yref="paper",font=dict(
                    family="Courier New, monospace",
                    size=20,
                    color='#17becf' 
                    ))
        figScat.add_annotation(x=1, y=0, text="Bad & Unlucky", showarrow=False, xref="paper", yref="paper",font=dict(
                    family="Courier New, monospace",
                    size=20,
                    color='#17becf' 
                    ))
        figScat.add_annotation(x=0, y=1, text="Good & Lucky", showarrow=False, xref="paper", yref="paper",font=dict(
                    family="Courier New, monospace",
                    size=20,
                    color='#17becf' 
                    ))
        figScat.add_annotation(x=1, y=1, text="Good & Tested", showarrow=False, xref="paper", yref="paper",font=dict(
                    family="Courier New, monospace",
                    size=20,
                    color='#17becf' 
                    ))
        figScat.update_layout(
            xaxis_title="Points Against",  # Set x-axis title
            yaxis_title="Points For",   # Set y-axis title
            xaxis=dict(
                title_font=dict(
                    color ='red',
                    shadow = False
                )
            ),
            yaxis=dict(
                title_font=dict(
                    color = 'green',
                    shadow = False

                )
            )
        )

        figScat.update_yaxes(dtick=100,
                        tickfont=dict(
                size=16,         # Font size
            ))
        figScat.update_xaxes(dtick=100,
                        tickfont=dict(
                size=16,         # Font size
            ))
        figScat.add_annotation(
        text="O Size = Wins | --- = Avg",
        xref="paper", yref="paper",
        x=0.5, y=1.15, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            size=12,
        )
        )
        
        
        figScat.update_layout(xaxis=dict(range=[minopponent - 30, topopponent + 40])) 
        figScat.update_layout(yaxis=dict(range=[minscore - 25, topscore + 25])) 

        figScat.update_layout(margin=dict(t=200, b=100, l=100, r=100))

        figScat.update_layout(title=dict(y=.9))
        apply_logo_to_fig(figScat)
        return figScat

    def MatchupPreview_WinPercentage(self, PreviewWeek, Alternate=None):
        
        breakoutDF = self.Breakout_dict[PreviewWeek]
        
        
        # # Set Time Ticks
        # time_dict = {'Monday 7 PM': 'MON 7PM', 'Sunday 9 AM':'SUN 9AM', 'Sunday 1 PM':'SUN 1PM', 'Sunday 4 PM': 'SUN 4PM', 'Sunday 8 PM':'SUN 8PM',
        #         'Thursday 8 PM':'THU 8PM', 'Monday 8 PM':'MON 8PM','Thursday 4 PM':'THU 4PM','Thursday 12 PM':'THU 12PM','Friday 3 PM':'FRI 3PM'}
    
        # time_order = ['THU', 'SUN 9AM','SUN 1PM', 'SUN 4PM', 'SUN 8PM', 'MON 7PM', 'MON 8PM']
        
        # if Alternate == 'SundayMorning':
        #     time_order = ['THU 8PM', 'SUN 9AM','SUN 1PM', 'SUN 4PM', 'SUN 8PM', 'MON 8PM']
        # elif Alternate == 'Thanksgiving':
        #     time_order = ['THU 12PM', 'THU 4PM','THU 8PM','FRI 3PM','SUN 1PM', 'SUN 4PM', 'SUN 8PM', 'MON 8PM']
        # if Alternate == None:
        #     time_order = ['THU 8PM','SUN 1PM', 'SUN 4PM', 'SUN 8PM', 'MON 8PM']
        
        #Set-up Data
        breakoutDF['color'] = breakoutDF['team'].map(self.teamcolors)
        breakoutDF = breakoutDF.sort_values('gametime_gameday')
        self.GametimeList = breakoutDF['gametime_gameday_format'].unique()

        breakoutDF_group = breakoutDF.groupby(['team','gametime_gameday_format','matchup']).size().reset_index(name='count')
        #breakoutDF_group['GameTime-Simp'] = breakoutDF_group['gametime_gameday_format'].map(time_dict)
        grouped = breakoutDF_group.groupby('matchup')

        




        
        # Create a subplot with 1 row and 2 columns (for the bar chart and the pie chart)
        figCombo = make_subplots(
                rows=6, cols=2, 
                shared_xaxes=True,
                column_widths=[0.85, 0.15],  # Adjust the width of each subplot
                specs=[[{"type": "bar"}, {"type": "pie"}],
                    [{"type": "bar"}, {"type": "pie"}],
                    [{"type": "bar"}, {"type": "pie"}],
                    [{"type": "bar"}, {"type": "pie"}],
                    [{"type": "bar"}, {"type": "pie"}],
                    [{"type": "bar"}, {"type": "pie"}]]
                #subplot_titles=['Matchup Schedule','Win History']# Specify the chart types
            )
        row_ys = {1: 1, 2: 0.83, 3: 0.66, 4: 0.49, 5: 0.32, 6: 0.15}  # Adjust as needed
        
        OppWinPercentageTable_Current = All_Time.OppWinPercentageTable()
        for i in range(1,7):
            
            testgroup = grouped.get_group(i)

            teams = testgroup['team'].unique()
            win_mean = OppWinPercentageTable_Current.loc[teams[0], teams[1]]




            # Add the bar chart to the first column
            figCombo.add_trace(
                go.Bar(
                    y=testgroup['count'], 
                    x=testgroup['gametime_gameday_format'], 
                    marker=dict(
                        color = [self.teamcolors[team] for team in testgroup['team']], 
                        cornerradius = 10
                    ),
                    text=testgroup['count'],
                    textangle = 0,
                    textposition='auto',
                    showlegend=False,
                ),
                row=i, col=1
            )

            # Add the pie chart to the second column
            figCombo.add_trace(
                go.Pie(values=[win_mean, 1-win_mean] ,labels=[f'{teams[0]}',f'{teams[1]}'],
                    marker = dict(colors = [self.teamcolors[teams[0]],self.teamcolors[teams[1]]]), showlegend=False),
                row=i, col=2
            )
                # Create a custom title with colored team names
            title_html = f'<span style="color:{self.teamcolors[teams[0]]}">{teams[0]}</span> vs <span style="color:{self.teamcolors[teams[1]]}">{teams[1]}</span>'

            # Add the custom title as an annotation at the top of each subplot
            figCombo.add_annotation(
                text=title_html,  # The HTML title
                xref=f'x domain', yref=f'y domain',
                x=.5, y=1.2,  # Position it above the subplot (y > 1)
                xanchor='center',
                font=dict(size=15, weight ='bold'),
                showarrow=False,
                row=i, col=1  # Apply to the i-th row and first column (bar chart)
            )
            # Update the layout with dark theme and grouped bar mode
            figCombo.update_layout(barmode="group", template="gridiron_ink")
            figCombo.update_xaxes(
                # categoryorder="array",
                # categoryarray=time_order,
                showticklabels = True, 
                side = 'bottom',
                row=i, col=1  # Apply to the bar chart in the i-th row and first column
            )
            

        # Show the figure
        figCombo.update_layout(width=800, height=1200, title_text = f'<b>Week {PreviewWeek} Preview</b>')
        figCombo.update_xaxes(title_text="", side = 'bottom',tickfont=dict(size=14),
                                 ticktext=breakoutDF['Tick'], tickvals = breakoutDF['gametime_gameday_format'])
        figCombo.update_layout(xaxis=dict(categoryorder='array',categoryarray =self.GametimeList))
        figCombo.update_annotations(font_size = 20)

        figCombo.add_annotation(
                text=f'<b>Game Time Schedule</b>',  # The HTML title
                xref=f'paper', yref=f'paper',
                x=.4, y=1.06,  # Position it above the subplot (y > 1)
                xanchor='center',
                font=dict(size=26),
                showarrow=False,
            )
        figCombo.add_annotation(
                text=f'<b>Win History</b>',  # The HTML title
                xref=f'paper', yref=f'paper',
                x=.93, y=1.06,  # Position it above the subplot (y > 1)
                xanchor='center',
                font=dict(size=26),
                showarrow=False,
            )
        figCombo.update_traces(textfont=dict(
                        size=18, weight = 'bold'))
        # figCombo.update_xaxes(tickfont=dict(size=12))
        figCombo.update_yaxes(dtick=2)
        figCombo.update_layout(uniformtext_minsize=10, uniformtext_mode='hide')
        
        figCombo.update_layout(
                                margin=dict(t=150, b=40, l=60, r=60)  # Adjust these values as needed
                                )

        apply_logo_to_fig(figCombo,xval=0,yval=1.1)
        
        return figCombo
       
    def PlayerPoints(self, WeekNum):
        self.WeeklyWins()    

        figScoreLine = px.line(self.ConcatinatedWeeks[self.ConcatinatedWeeks['Week'].isin(range(0, WeekNum+1))], x='Week',y='Total', template='gridiron_ink', facet_col='Team',markers=True,facet_col_wrap=4, color='Team', line_shape='spline')
        figScoreLine.update_layout(xaxis_title="", yaxis_title="")
        figScoreLine.update_layout(width=1200, height=1000, showlegend=False)
        figScoreLine.update_layout(title=dict(text=f"{self.year} Score Trends",y=.91))
        figScoreLine.update_annotations(font_size=20)
        
        # Customize facet titles
        figScoreLine.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
        
        figScoreLine.update_xaxes(tickfont=dict(size=13),)
        figScoreLine.update_yaxes(tickfont=dict(size=13))

        figScoreLine.update_xaxes(title_text="", col=1)
        figScoreLine.update_xaxes(title_text="", col=2)
        figScoreLine.update_xaxes(title_text="", col=3)
        figScoreLine.update_xaxes(title_text="", col=4)
        figScoreLine.update_yaxes(title_text="", col=1)
        figScoreLine.update_xaxes(matches=None,side = 'bottom',tickvals = [5, 10, 15])
        figScoreLine.for_each_xaxis(lambda xaxis: xaxis.update(showticklabels=True))
        

        figScoreLine.update_layout(
                                margin=dict(t=160, b=80, l=60, r=60)  # Adjust these values as needed
                                )
        apply_logo_to_fig(figScoreLine,xval=0,yval=1.1)

        return figScoreLine
    
    def WeeklyWinsGraphBreakout(self,week):
        self.WeeklyWins()
        df = self.ConcatinatedWeeks

        fig2 = px.line(df,x='Week',y='Total Wins', color = 'Team',template='gridiron_ink',line_shape = 'spline', facet_col='Team',facet_col_wrap=3, title = '<b>Weekly Wins</b><br><sup>Breakout</sup>')
        
        
        fig2.update_yaxes(zerolinewidth = 1, ticklabelposition = 'inside',ticklabelstandoff=130, tickfont = dict(color ='#4A6B85', size = 12), dtick = 3,showticklabels=True,showgrid=True)
        fig2.update_xaxes(zerolinewidth = 1,side = 'bottom', ticklabelposition = 'inside bottom', tickfont = dict(color ='#4A6B85', size =12), dtick = 3, showticklabels=True,showgrid=False)
        

        
        fig2.update_layout(width=900, height=900, showlegend=False, title = dict(y=.93))
        
        # Adjust the thickness of the lines
        fig2.update_traces(line=dict(width=4))  # Set the line width (e.g., 3 pixels)
        
        fig2.update_layout(legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1,
            title = ''
        ))


        # Update x-axis and y-axis titles with font customization
        fig2.update_layout(
            xaxis_title="",  
            yaxis_title="",  
            xaxis=dict(
                title_font=dict(
                    size=20          # Set font size for x-axis title
                )
            ),
            yaxis=dict(
                title_font=dict(
                    size=20          # Set font size for y-axis title
                )
            )
        )
        fig2.update_layout(
            xaxis2_title="",  
            yaxis2_title="",  
            xaxis2=dict(
                title_font=dict(
                    size=20          # Set font size for x-axis title
                )
            ),
            yaxis2=dict(
                title_font=dict(
                    size=20          # Set font size for y-axis title
                )
            )
        )
        fig2.update_layout(
            xaxis3_title="",  
            yaxis3_title="",  
            xaxis3=dict(
                title_font=dict(
                    size=20          # Set font size for x-axis title
                )
            ),
            yaxis3=dict(
                title_font=dict(
                    size=20          # Set font size for y-axis title
                )
            )
        )
        
        # Determine final wins and sort by them
        final_scores = [(d.name, d.x[-1], d.y[-1], d.line.color) for d in fig2.data]
        final_scores.sort(key=lambda x: -x[2])  # Sort by final win count, descending

       

        fig2.update_layout(xaxis=dict(range=[0, week + 1.5])) 
        fig2.update_layout(yaxis=dict(range=[0, week + 1])) 
        fig2.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
        fig2.update_layout(
        font=dict(
            size=18,  # Set the font size here
        )
    )
        fig2.update_yaxes(title="", col =1)  # Set a new title for all y-axes

        for annotation in fig2.layout.annotations:
                    title_text = annotation.text  # e.g., "Team A vs Team B"
                    #teams = title_text.split(" vs ")  # Split into individual team names
                    # Create a styled title with team names in respective colors
                    annotation.text = f"<span style='color:{self.teamcolors[title_text]}'>{title_text}</span>"
                    annotation.font.size = 23  # Optional: Adjust font size for clarity
        
        fig2.update_layout(
                                margin=dict(t=130, b=80, l=60, r=60)  # Adjust these values as needed
                                )
        apply_logo_to_fig(fig2,xval=0,yval=1.1)
        
        return fig2
 
    def WholeSeasonBarGraph(self):
        No = '#F94144', # Coral Red
        Yes = '#90BE6D', # Lime Green
        
        figBarWeek = px.bar(self.Matches.reset_index().sort_values(['Week','Total']), x='Team',y='Total',template = 'gridiron_ink',color = "Won", barmode='stack', 
                            title = 'Seasonal Performance', text='Week',color_continuous_scale=px.colors.diverging.Tealrose)
        figBarWeek.update_layout( xaxis={'categoryorder':'total descending', 'title': None},
                                 yaxis={'categoryorder':'total ascending','title': None}
                                 )
        
        figBarWeek.update_layout(legend=dict(
                orientation="h",
                yanchor="bottom",
                y=1.02,
                xanchor="right",
                x=1,
                title = ''
            ))
        #Update the layout to hide the legend:
        figBarWeek.update(layout_coloraxis_showscale=False)
        figBarWeek = px.colors.diverging.swatches_continuous()
        figBarWeek.add_vline(x=5.5)
        figBarWeek.update_layout(title = dict(y=.93))
        
        figBarWeek.update_layout(
                                margin=dict(t=180, b=100, l=60, r=60)  # Adjust these values as needed
                                )
        apply_logo_to_fig(figBarWeek, yval=-0.07)
        return figBarWeek
        
    def WeekYTDTotalsPercents(self):
        self.WeeklyWins()
        df = self.ConcatinatedWeeks
        df['BarName'] = df['PercentTotal'].astype(str) + '%'
        df.groupby('Week')['Total'].sum()
        
        figBar = px.bar(df.sort_values('Total'), x='Week',y='Total',template = 'gridiron_ink',color = "Team", barmode='stack',text='BarName', title = f'<b>Week-by-Week Domination</b><br><sup>{self.year}</sup>')
        figBar.update_layout(barmode='stack', xaxis={'categoryorder':'total descending'})
        figBar.update_layout(barcornerradius=5)
        figBar.update_layout(legend=dict(
                orientation="v",
                yanchor="middle",
                y=.5,
                xanchor="right",
                x=1.2,
                title = '',
                font = dict(size = 16)
            ))
        figBar.update_traces(textfont_size=10, textangle=0, cliponaxis=True,insidetextanchor="middle", textposition = 'inside', textfont=dict(size=10))
        figBar.update_layout(width=1200, height=800)
        figBar.update_layout(showlegend=True, title = dict(y= .93))

            # Customize the x-axis labels
        figBar.update_xaxes(
                tickfont=dict(
                    size=16,         # Font size
                ),
                title = None
            )

            # Customize the y-axis labels
        figBar.update_yaxes(
                tickfont=dict(
                    size=18,         # Font size
                ),
                title=None
            )
        figBar.update_xaxes(dtick=1)
        figBar.update_yaxes(dtick=200)
        figBar.update_traces(width=.96)
        figBar.update_traces(marker_line_width=2,marker_line_color='black')

        figBar.update_layout(
                                margin=dict(t=120, b=100, l=60, r=100)  # Adjust these values as needed
                                )
        apply_logo_to_fig(figBar, xval = .57,yval=-0.07)

        return figBar
            
    def ScoreFrequencyGraph(self, WeekNum):
        figScoring = px.histogram(self.Matches[self.Matches['Week'].isin(range(0,WeekNum+1))], x='Total', template='gridiron_ink',title = 'Scoring Frequency', marginal='rug', 
                                  color = 'Team', labels = 'Team')
        figScoring.update_layout(width=1200, height=800)
        figScoring.update_yaxes(
                tickfont=dict(
                    size=15,         # Font size
                ),
                title = None,
                
            )
        figScoring.update_xaxes(
                tickfont=dict(
                    size=15,         # Font size
                ),
                title = None,
                dtick=10,
                side = 'bottom'
            )
        figScoring.update_layout(legend=dict(
                orientation="v",
                yanchor="top",
                y=.8,
                xanchor="right",
                x=1.05,
                title = '',
                font = dict(size = 16),
                bgcolor="#163146",
                bordercolor="#3D5E78",
                borderwidth=2
            ))
        figScoring.update_traces(marker_line_width=2,marker_line_color='black')
        figScoring.update_layout(showlegend = True, title = dict(y=.93))
        
        figScoring.update_layout(
                                margin=dict(t=80, b=100, l=75, r=75)  # Adjust these values as needed
                                )
        apply_logo_to_fig(figScoring, yval=-0.09)
        return figScoring
        
    def StarterPerformanceGraph(self):
        df = self.BreakoutSeason
        Starters = df[df['starter'] == 1]
        PositionPoints = Starters.groupby(['team','position'])['points'].sum()
        PositionPoints = PositionPoints.reset_index()
        PositionPoints = round(PositionPoints,0)
        
        
        figPosTotals = px.bar(PositionPoints, x='points',y='team', color = 'position', template = 'gridiron_ink', orientation='h', 
                      text='points',title = 'Starter Points by Position',
                      category_orders={'position':['QB','RB','WR','TE','K','DEF']})
        figPosTotals.update_yaxes(
                tickfont=dict(
                    size=20,         # Font size
                ),
                title = None,
                categoryorder="total ascending",
            )
        figPosTotals.update_layout(width=800, height=1200)
        figPosTotals.update_traces(textfont_size=16, textangle=0, cliponaxis=True, textposition = 'inside', textfont=dict(size=16))
        figPosTotals.update_traces(marker_line_width=2,marker_line_color='black')
            
        figPosTotals.update_traces(insidetextanchor= 'middle')
        figPosTotals.update_layout(
                uniformtext_minsize=10,
                uniformtext_mode='show'
                )
        # Update the legend title
        figPosTotals.update_layout(
            legend=dict(
                title=dict(
                    text=None,
                    font=dict(
                        size=25,
                        
                    )
                )
            )
        )  
        
        
        figPosTotals.update_xaxes(
                tickfont=dict(
                    size=20,         # Font size
                ),
                title = None
            )
        
        figPosTotals.update_layout(legend=dict(orientation="h"), showlegend = True)
        # Set legend location
        figPosTotals.update_layout(
            legend=dict(
                x=0.4,  # x-coordinate of the legend (0 to 1, where 0 is left and 1 is right)
                y=1.07,   # y-coordinate of the legend (0 to 1, where 0 is bottom and 1 is top)
                xanchor="center",  # horizontal anchor point ('left', 'center', 'right')
                yanchor="top" ,   # vertical anchor point ('top', 'middle', 'bottom')
                font = dict(size = 16)
            )
        )

        figPosTotals.update_layout(
                                margin=dict(t=140, b=100, l=180, r=40)  # Adjust these values as needed
                                )
        apply_logo_to_fig(figPosTotals, xval=.4)

        return figPosTotals

    def ViolinPlayer(self, WeekNum,Starters = False):
        WeekRange = range(0,WeekNum+1)
        if Starters == False:
            df = self.BreakoutSeason[self.BreakoutSeason['week'].isin(WeekRange)]
            titleText = "<b>Positional Points Distribution</b><br><sup>Players</sup>"
        else:
            df = self.Starters[self.Starters['week'].isin(WeekRange)]
            titleText = "<b>Positional Points Distribution</b><br><sup>Starting Players</sup>"
        

        figViolin = px.violin(df,x='points', y='position',facet_col='team',facet_col_wrap=3, color = 'position', template='gridiron_ink')
        figViolin.update_traces(orientation='h', side='positive', width=3, points=False, spanmode = 'hard')
        figViolin.update_layout(
            title=dict(text=titleText)
        )
        figViolin.update_layout(width=800, height=1200)
        figViolin.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
        figViolin.update_annotations(font_size = 25)

        figViolin.for_each_xaxis(lambda xaxis: xaxis.update(showticklabels=True))
        figViolin.update_yaxes(
                tickfont=dict(
                    size=20,         # Font size
                ),
                title=None
            )
        figViolin.update_xaxes(
                tickfont=dict(
                    size=13,         # Font size
                ),
                title=None,
                side = 'bottom'
            )
        for annotation in figViolin.layout.annotations:
                    title_text = annotation.text  # e.g., "Team A vs Team B"
                    #teams = title_text.split(" vs ")  # Split into individual team names
                    # Create a styled title with team names in respective colors
                    annotation.text = f"<span style='color:{self.teamcolors[title_text]}'>{title_text}</span>"
                    annotation.font.size = 25  # Optional: Adjust font size for clarity

        figViolin.update_layout(
                                margin=dict(t=140, b=100, l=40, r=40)  # Adjust these values as needed
                                )
        apply_logo_to_fig(figViolin)
        return figViolin
    
    def ViolinPosition(self, Starters = True):
        
        if Starters == False:
            df = self.BreakoutSeason  
            titleText = "<b>Positional Points Distribution</b><br><sup>Position</sup>"
        else:
            df = self.Starters
            titleText = "<b>Positional Points Distribution</b><br><sup>Starters by Position</sup>"
        
        figViolin2 = px.violin(df,x='points', y='team',facet_col='position',facet_col_wrap=2, color = 'team', 
                       template='gridiron_ink',category_orders={
                           "position": ["QB", "RB", "WR", "TE", "K", "DEF"],
                              })
        figViolin2.update_traces(orientation='h', side='positive', width=3, points=False, spanmode='hard')
        figViolin2.update_layout(width=800, height=1200, showlegend=False,)
        figViolin2.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
        figViolin2.for_each_xaxis(lambda xaxis: xaxis.update(showticklabels=True))
        figViolin2.update_yaxes(
                tickfont=dict(
                    size=13,         # Font size
                ),
                title=None
            )
        figViolin2.update_xaxes(
                tickfont=dict(
                    size=13,         # Font size
                ),
                title=None,
                side = 'bottom'
            )
        figViolin2.update_annotations(font_size=35, font = dict(color = '#C49FC1'))
        figViolin2.update_layout(
            title=dict(text=titleText)
        )
        figViolin2.update_layout(
                                margin=dict(t=140, b=100, l=120, r=40)  # Adjust these values as needed
                                )
        apply_logo_to_fig(figViolin2)
        return figViolin2
        
    def TopPlayers(self, position, threshold):
        self.SetBest(threshold)
        df = self.Best
        TopPlayers = df[df['position'] == position]
        TopPlayers = TopPlayers[TopPlayers['TotalYTD']>threshold]

        figLine = px.line(TopPlayers,x='week_x',y='Score YTD', color = 'player',line_shape = 'spline',template='gridiron_ink',
                          title=f'Top {position}s over {threshold}')
        figLine.update_layout(width=1200, height=800, title = dict(y=.93), showlegend = True)
        figLine.update_layout(
            legend=dict(
                title = '',
                x=0.5,  # x-coordinate of the legend (0 to 1, where 0 is left and 1 is right)
                y=1.24,   # y-coordinate of the legend (0 to 1, where 0 is bottom and 1 is top)
                xanchor="center",  # horizontal anchor point ('left', 'center', 'right')
                yanchor="top" ,   # vertical anchor point ('top', 'middle', 'bottom')
                font = dict(size = 12)
            )
        )
        figLine.update_yaxes(
                tickfont=dict(
                    size=20,         # Font size
                ),
                title=None
            )
        figLine.update_xaxes(
                tickfont=dict(
                    size=20,         # Font size
                ),
                title='Week',
                side = 'top'
            )
        figLine.update_layout(
                                margin=dict(t=190, b=100, l=60, r=60)  # Adjust these values as needed
                                )
        apply_logo_to_fig(figLine)
        return figLine                    
    
    def PositionStrengthCalculator(self):
        scaler = MinMaxScaler()
        scalerStandard = StandardScaler()
        PosistionPolar = self.Starters.groupby(['team','position'])['points'].mean()
        self.PosistionPolar = PosistionPolar.reset_index()
        PosistionPivot = self.PosistionPolar.pivot(columns='position', index='team', values='points')
        PivotPositions = PosistionPivot.columns
        PivotTeams = PosistionPivot.index
        PosistionPivot_scaled = scaler.fit_transform(PosistionPivot)

        PosistionPivot_Standard_scaled = scalerStandard.fit_transform(PosistionPivot)
        
        self.PosistionPivot_scaled = pd.DataFrame(PosistionPivot_scaled, columns = PivotPositions, index=PivotTeams)
        self.PosistionPivot_Standard_scaled = pd.DataFrame(PosistionPivot_Standard_scaled, columns = PivotPositions, index=PivotTeams)
                 
    def PositionStengthPolar(self):
        self.PositionStrengthCalculator()
        
        PosistionAvg = self.Starters.groupby('position')['points'].mean()
        PosistionPolar = round(self.PosistionPolar,2)
        PosistionAvg = round(PosistionAvg,2)
        PosistionPolar = PosistionPolar.reset_index()
        PosistionAvg = PosistionAvg.reset_index()
        PosistionPivot_scaled = self.PosistionPivot_scaled.reset_index()

        PosistionPivot_Standard_scaled = self.PosistionPivot_Standard_scaled.reset_index()
        teamlist = PosistionPivot_scaled.team.unique()
        teamdict = dict(enumerate(teamlist,1))
        teamlistorder = teamdict.values()
        rowlist = [1,1,1,2,2,2,3,3,3,4,4,4]
        collist = [1,2,3,1,2,3,1,2,3,1,2,3]
        rowdict = dict(enumerate(rowlist,1))
        coldict = dict(enumerate(collist,1))
        polars = ['polar']*12
        
        PosistionPivot_scaled = self.PosistionPivot_scaled
        PosistionPivot_Standard_scaled = self.PosistionPivot_Standard_scaled.reset_index()
        
        figPolarAll = make_subplots(rows=4, cols=3, specs=[[{'type': 'polar'}, {'type': 'polar'}, {'type': 'polar'}],[{'type': 'polar'}, {'type': 'polar'}, {'type': 'polar'}],
                                                   [{'type': 'polar'}, {'type': 'polar'}, {'type': 'polar'} ],[{'type': 'polar'}, {'type': 'polar'}, {'type': 'polar'} ]],
                            subplot_titles=list(teamlistorder)
                            )
        for i in range (1,13):
            PolarTest = PosistionPivot_Standard_scaled[PosistionPivot_Standard_scaled['team']==teamdict[i]]
            PolarTest = PolarTest.set_index('team').T
            PolarTest.columns = ['points']
            PolarTest = PolarTest.reset_index()
            figPolarAll.add_trace(go.Scatterpolar(r=PolarTest['points'], theta=PolarTest['position'], mode='markers+text',textposition='top center',name=teamdict[i],fill='toself', r0 = -2, dr = .5, 
                                                  text=round(PolarTest['points'],1)), row=rowdict[i], col=coldict[i])
            
            

        figPolarAll.update_layout(width=800, height=1200, template = 'gridiron_ink', showlegend=False)
        figPolarAll.update_layout(polar1=dict(
                                    radialaxis=dict(
                                        range=[-3, 3],  # Set the radial range; adjust to fit your data scale
                                        tickvals=[-3,0,3],  # Customize tick values for consistency
                                        tickformat=".1f",  # Set the format for tick labels
                                        tickangle=0,  # Optional: Adjust tick angle for readability
                                        showticklabels=False, tickfont=dict(color = '#163146')
                                    )),
                                polar2=dict(
                                    radialaxis=dict(
                                        range=[-3, 3],  # Set the radial range; adjust to fit your data scale
                                        tickvals=[-3,0,3],  # Customize tick values for consistency
                                        tickformat=".1f",  # Set the format for tick labels
                                        tickangle=45,
                                        showticklabels=False, tickfont=dict(color = '#163146')
                                    )),
                                polar3=dict(
                                    radialaxis=dict(
                                        range=[-3, 3],  # Set the radial range; adjust to fit your data scale
                                        tickvals=[-3,0,3],  # Customize tick values for consistency
                                        tickformat=".1f",  # Set the format for tick labels
                                        tickangle=45,
                                        showticklabels=False, tickfont=dict(color = '#163146')
                                    )),
                                polar4=dict(
                                    radialaxis=dict(
                                        range=[-3, 3],  # Set the radial range; adjust to fit your data scale
                                        tickvals=[-3,0,3],  # Customize tick values for consistency
                                        tickformat=".1f",  # Set the format for tick labels
                                        tickangle=45,
                                        showticklabels=False, tickfont=dict(color = '#163146')
                                    )),
                                polar5=dict(
                                    radialaxis=dict(
                                        range=[-3, 3],  # Set the radial range; adjust to fit your data scale
                                        tickvals=[-3,0,3],  # Customize tick values for consistency
                                        tickformat=".1f",  # Set the format for tick labels
                                        tickangle=45,
                                        showticklabels=False, tickfont=dict(color = '#163146')
                                    )),
                                polar6=dict(
                                    radialaxis=dict(
                                        range=[-3, 3],  # Set the radial range; adjust to fit your data scale
                                        tickvals=[-3,0,3],  # Customize tick values for consistency
                                        tickformat=".1f",  # Set the format for tick labels
                                        tickangle=45,
                                        showticklabels=False, tickfont=dict(color = '#163146')
                                    )),
                                polar7=dict(
                                    radialaxis=dict(
                                        range=[-3, 3],  # Set the radial range; adjust to fit your data scale
                                        tickvals=[-3,0,3],  # Customize tick values for consistency
                                        tickformat=".1f",  # Set the format for tick labels
                                        tickangle=45,
                                        showticklabels=False, tickfont=dict(color = '#163146')
                                    )),
                                polar8=dict(
                                    radialaxis=dict(
                                        range=[-3, 3],  # Set the radial range; adjust to fit your data scale
                                        tickvals=[-3,0,3],  # Customize tick values for consistency
                                        tickformat=".1f",  # Set the format for tick labels
                                        tickangle=45,
                                        showticklabels=False, tickfont=dict(color = '#163146')
                                    )),
                                polar9=dict(
                                    radialaxis=dict(
                                        range=[-3, 3],  # Set the radial range; adjust to fit your data scale
                                        tickvals=[-3,0,3],  # Customize tick values for consistency
                                        tickformat=".1f",  # Set the format for tick labels
                                        tickangle=45,
                                        showticklabels=False, tickfont=dict(color = '#163146')
                                    )),
                                polar10=dict(
                                    radialaxis=dict(
                                        range=[-3, 3],  # Set the radial range; adjust to fit your data scale
                                        tickvals=[-3,0,3],  # Customize tick values for consistency
                                        tickformat=".1f",  # Set the format for tick labels
                                        tickangle=45,
                                        showticklabels=False, tickfont=dict(color = '#163146')
                                    )),
                                polar11=dict(
                                    radialaxis=dict(
                                        range=[-3, 3],  # Set the radial range; adjust to fit your data scale
                                        tickvals=[-3,0,3],  # Customize tick values for consistency
                                        tickformat=".1f",  # Set the format for tick labels
                                        tickangle=45,
                                        showticklabels=False, tickfont=dict(color = '#163146')
                                    )),
                                polar12=dict(
                                    radialaxis=dict(
                                        range=[-3, 3],  # Set the radial range; adjust to fit your data scale
                                        tickvals=[-3,0,3],  # Customize tick values for consistency
                                        tickformat=".1f",  # Set the format for tick labels
                                        tickangle=45,
                                        showticklabels=False, tickfont=dict(color = '#163146')
                                    )),
                                )

        figPolarAll.update_layout(
            title="<b>Positional Strength</b><br><sup>Std Dev from Average</sup>",
            )
        
        figPolarAll.update_annotations(font_size=22,font = dict(color = '#C49FC1'))
        figPolarAll.update_polars(bgcolor='#BDE2FF')
        
        figPolarAll.add_annotation(
            text="",
            xref="paper", yref="paper",
            x=-0.0, y=1.05, # Position relative to figure (right side, middle)
            showarrow=False,
            font=dict(
                size=18,
            )
            )
        figPolarAll.update_traces(textfont_size=13, textfont=dict(color = '#163146'))
        
        figPolarAll.update_layout(
                                margin=dict(t=140, b=100, l=60, r=60)  # Adjust these values as needed
                                )
        apply_logo_to_fig(figPolarAll)
        return figPolarAll
    
    
    def ForAgainstwithTeams(self):
        OpponentPoints = self.BreakoutSeason.groupby(['team','opponent_team'])['points'].sum().reset_index().sort_values('points', ascending=False)
        OpponentPointsNoTeam = self.BreakoutSeason.groupby(['team','opponent_team'])['points'].sum().round(1).reset_index().sort_values('points', ascending=False)
        OpponentPointsNoTeamTOP =  OpponentPointsNoTeam.iloc[0:10]
        OpponentPointsNoTeamTOP['TeamVs'] = OpponentPointsNoTeamTOP.team + ' vs. ' + OpponentPointsNoTeamTOP.opponent_team
        OpponentPointsNoTeamTOP['Purpose'] = 'Points Against...'    
        
        TeamPoints = self.BreakoutSeason.groupby(['team','recent_teams'])['points'].sum().round(1).reset_index().sort_values('points', ascending=False)
        TeamPointsTOP = TeamPoints.iloc[0:10]
    
        TeamPointsTOP['color'] = TeamPointsTOP.team.map(self.teamcolors)
        TeamPointsTOP['TeamVs'] = TeamPointsTOP.team + ' w/ ' + TeamPointsTOP.recent_teams
        TeamPointsTOP['Purpose'] = 'Points With...'
        
        JointTopBottom = pd.concat([OpponentPointsNoTeamTOP,TeamPointsTOP ])
        
        figTeamPoints = go.Figure()

        figTeamPoints = make_subplots(
                    rows=2, cols=1, 
                    shared_xaxes=False,
                    vertical_spacing =  .1,
                    #column_widths=[0.5, 0.55],  # Adjust the width of each subplot
                    specs=[[{"type": "bar"}],
                            [{"type": "bar"}]],
                    subplot_titles=['Points With...','Points vs...']# Specify the chart types
                )
        figTeamPoints.add_trace(
                    go.Bar(
                        x=TeamPointsTOP['points'], 
                        y=TeamPointsTOP['TeamVs'], 
                        
                        text=TeamPointsTOP['points'],
                        textangle = 0,
                        textposition='auto',
                        showlegend=False,
                        orientation='h', 
                        marker_color = TeamPointsTOP.points,
                        opacity=.8,
                        textfont=dict(size=24)
                    ),
                    row=1, col=1
                )
        figTeamPoints.add_trace(
                    go.Bar(
                        x=OpponentPointsNoTeamTOP['points'], 
                        y=OpponentPointsNoTeamTOP['TeamVs'], 
                        
                        text=OpponentPointsNoTeamTOP['points'],
                        textangle = 0,
                        textposition='auto',
                        showlegend=False,
                        orientation='h',
                        marker_color = OpponentPointsNoTeamTOP.points,
                        opacity=.8,
                        textfont=dict(size=24)
                    ),
                    row=2, col=1
                )

        figTeamPoints.update_layout(height = 1200, width = 900, template = 'gridiron_ink', barcornerradius = 7)
        
        figTeamPoints.update_annotations(font_size=25)
        figTeamPoints.update_xaxes(side='bottom')
        figTeamPoints.update_layout(title="<b>Points With & Against NFL Team</b>")

        figTeamPoints.update_annotations(font = dict(color = '#C49FC1'))
        figTeamPoints.update_layout(margin=dict(t=100, b=100, l=220, r=40))
        
        apply_logo_to_fig(figTeamPoints,xval=.40, yval=-0.06)

        return figTeamPoints
    
    def StatusGraph(self,WeekObj):
        self.Calc(WeekObj)
        self.PowerRankings(WeekObj.week)
        teams = list(self.PowerRanks[self.PowerRanks['Week'] == WeekObj.week].sort_values('Power Ranking').Team)
        LeagueAverage = self.StatusDict['LeagueAverage']

        Scores = self.StatusDict['Scores']
        AverageScores = self.StatusDict['AverageScores']
        PowerRanks = self.StatusDict['PowerRanks']
        PreviousRanks = self.StatusDict['PreviousRanks']
        PowerPercents = self.StatusDict['PowerPercents']
        OptimalScores = self.StatusDict['OptimalScores']

        
        fig = go.Figure()

        y1 = 1.08
        y2 = 1.0
        
        
        for team in teams:


            y1 -= .08
            y2 -= .08
            

            fig.add_trace(go.Indicator(
                mode="gauge+number",
                value=Scores[team],
                title={'text': f"{team}",'font':{'size' : 25,'color' : self.teamcolors[team]}},
                domain={'x': [.1, .3], 'y': [y2, y1]},
                number = {'font':{'size': 18}},
                gauge={
                    'axis': {'range': [None, OptimalScores[team]], 'tickwidth': 1, 'tickcolor': "darkblue"},
                    'bar': {'color': "#FFC300"}, # Color of the manager's score bar
                    'shape':'bullet',
                    'borderwidth': 4,
                    'bar':{'thickness': .6, 'color' : 'rgba(148,103,189,.8)'},
                    'threshold' : dict(value = OptimalScores[team]),

                    'bordercolor': "gray",
                    'steps': [
                        {'range': [0, OptimalScores[team] * .7], 'color': '#F94144'},   # Poor
                        {'range': [OptimalScores[team] * .7, OptimalScores[team] * .9], 'color': '#E6DB74'},  # Average
                        {'range': [OptimalScores[team] * .9, OptimalScores[team]], 'color': '#90BE6D'}  # Good
                    ],
                }
            ))
            fig.add_trace(go.Indicator(
                mode="number",
                value= Scores[team]/OptimalScores[team],
                #title={'text': f"Efficiency"},
                domain={'x': [0.1, .25], 'y': [y2, y1]},
                number =dict(valueformat = ".0%", suffix = ' Efficient')

            ))

            fig.add_trace(go.Indicator(
                mode = "delta", value = Scores[team],
                domain = {'x': [.35, .45], 'y': [y2, y1]},
                delta = {'reference': AverageScores[team], 'position': "left", 'font':{'size': 40},'decreasing':dict(color='#F94144'),'increasing':dict(color='#90BE6D')}
                #'suffix':f' pts <br>vs Personal Average'
            )
            )

            fig.add_trace(go.Indicator(
                mode = "delta", value = Scores[team],
                domain = {'x': [.5, .6], 'y': [y2, y1]},
                delta = {'reference': LeagueAverage, 'position': "left",'decreasing':dict(color='#F94144'),'increasing':dict(color='#90BE6D'),
                         'font':{'size': 40}},

            ))

            fig.add_trace(go.Indicator(
                mode="number+delta",
                value=PowerRanks[team],
                domain={'x': [0.6, .9], 'y': [y2, y1]},
                number =dict( suffix = ''),    
                delta = {'reference': PreviousRanks[team], 'position': "bottom",'decreasing':dict(color='#90BE6D', symbol = '↑'),'increasing':dict(color='#F94144', symbol = '↓'),
                          'suffix':' vs Last Week','valueformat' : "0",}


            ))

            fig.add_trace(go.Indicator(
                mode="number",
                value=PowerPercents[team],
                #title={'text': f"Power Win %"},
                domain={'x': [0.9, 1], 'y': [y2, y1]},
                number =dict( suffix = '', valueformat = ".0%"),    
                
            ))

            fig.update_layout(
                title_text=f'Power & Efficiency<br><sup>Week {WeekObj.week}</sup>',
                template='gridiron_ink'
            )
        # fig.add_annotation(
        # text="Efficiency",
        # xref="paper", yref="paper",
        # x=.1, y=1.05, # Position relative to figure (right side, middle)
        # showarrow=False,
        # font=dict(
        #     size=25,
        #     color="gold"
        # )
        # )

        fig.add_annotation(
        text="Vs.<br>Personal Avg.",
        xref="paper", yref="paper",
        x=.4, y=1.05, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            size=15,
            color="gold"
        )
        )

        fig.add_annotation(
        text=f"Vs.<br>League Avg.<br><sup>[{int(LeagueAverage)} pts.]</sup>",
        xref="paper", yref="paper",
        x=.55, y=1.05, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            size=15,
            color="gold"
        )
        )

        fig.add_annotation(
        text="Power Rankings",
        xref="paper", yref="paper",
        x=.83, y=1.05, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            size=25,
            color="gold"
        )
        )

        fig.add_annotation(
        text="Power Win %",
        xref="paper", yref="paper",
        x=1.02, y=1.05, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            size=25,
            color="gold"
        )
        )

        fig.update_layout(margin=dict(t=130, b=100, l=120, r=40))
        fig.update_layout(title = dict(y=.95))
        
        apply_logo_to_fig(fig)
        
        return fig
    
    def SeasonPointsForAgainst(self):

        df = self.Matches
        df_group = df.groupby('Team')[['Total','Opp']].sum().round(0)
        df_group['Opp'] = df_group['Opp'] * -1
        df_group['Dif'] = df_group['Total'] + df_group['Opp']
        df_group['Total_Rank'] = df_group['Total'].rank(ascending=False)
        df_group['Opp_Rank'] = df_group['Opp'].rank(ascending=True)

        df_group.sort_values('Dif',ascending=False)




        figTotal = px.bar(df_group.reset_index(),x=['Total','Opp','Dif'], y = 'Team', barmode= 'overlay', text_auto=True, title=f"<b>For & <span style='color:#17BECF'>Against</span></b>")
        figTotal.update_layout( xaxis={'title': None},
                                        yaxis={'categoryorder':'total ascending','title': None}
                                        )
        figTotal.update_xaxes(
                        tickfont=dict(
                            size=16,         # Font size
                        ),
                        title = None
                    )

                    # Customize the y-axis labels
        figTotal.update_yaxes(
                        tickfont=dict(
                            size=25, weight ='bold'       # Font size
                        ),
                        title=None
                    )
        figTotal.update_traces(insidetextanchor= 'middle',textfont=dict(
                        size=35, weight = 'bold'))

        figTotal.update_layout(margin=dict(t=130, b=100, l=230, r=40))
        figTotal.update_layout(title = dict(y=.93))
   
        self.UpdateColors(figTotal)


        apply_logo_to_fig(figTotal)

        return figTotal
    
    def BrawnyBench(self):
        BrawnyBench = self.BreakoutSeason

        BrawnyBench = BrawnyBench[BrawnyBench.starter == 0]
        BrawnyBenchGroup = BrawnyBench.groupby(['team'])['points'].sum().round(0).reset_index().sort_values('points')
        BrawnyBenchGroup['color'] = BrawnyBenchGroup['team'].map(self.teamcolors)

        figBench = px.bar(BrawnyBenchGroup, x = 'points',y = 'team', text = 'points',title = '<b>Brawny Benches</b><br><sup>Points That Just Sat There</sup>', 
                          color = 'team',color_discrete_map=self.teamcolors)
        figBench.update_layout(
                            margin = dict(l=220),
                            xaxis = dict(title = "",tickfont = dict(size = 22)),
                            yaxis = dict(title = '',tickfont = dict(size = 22)),
                            title = dict(y = 0.95, font= dict(size = 45))
                            )
        figBench.update_traces(textposition='inside', textfont_size=80)
        apply_logo_to_fig(figBench, xval = 0.43)
        # self.UpdateColors(figBench)


        return figBench

## Class: Survivor

In [23]:
class Survivor:
    def __init__(self, League):
        self.league = League
        self.id = League.id
        self.SettingsJSONtoDF()
        self.ProcessData()

    def SettingsJSONtoDF(self):
        league_status_request = requests.get(f'https://api.sleeper.app/v1/league/{self.id}/rosters')
        self.league_status_json = league_status_request.json()
        self.league_status_json_normal = json_normalize(self.league_status_json)
        data_for_df = []
        elimination_data = []

        # Loop through each team's data in the list
        for team_data in self.league_status_json:
            owner_id = team_data['owner_id']
            points_by_leg = team_data['metadata']['points_by_leg']
            previous_picks = team_data['metadata']['previous_picks']
            metadata = team_data['metadata']
    
            # Append a dictionary with the desired info to our list
            elimination_data.append({
                'owner_id': owner_id,
                'eliminated_leg_id': metadata.get('eliminated_leg_id'),
                'is_eliminated': metadata.get('is_eliminated'),
                'num_eliminations': metadata.get('num_eliminations')
            })
            
            for week, points in points_by_leg.items():
                pick = previous_picks.get(week)
                team_pick = pick[0] if pick else None
                
                week_number = int(week.split(':')[-1])
                
                # Append a dictionary with the owner_id to our master list
                data_for_df.append({
                    'owner_id': owner_id,
                    'week': week_number, 
                    'team_pick': team_pick, 
                    'points': points
                })

        # Create the final DataFrame from the list of dictionaries
        df = pd.DataFrame(data_for_df)
        self.Status = pd.DataFrame(elimination_data)
        self.Status['eliminated_leg_id'] = self.Status['eliminated_leg_id'].replace('v1:regular:','', regex=True).astype(int)

        # Sort the DataFrame by owner_id and then by week for organization
        self.Data = df.sort_values(by=['owner_id', 'week']).reset_index(drop=True)

    def find_unpicked(self, picked_list):
        nfl_team_abbreviations = [
            'ARI', 'ATL', 'BAL', 'BUF', 'CAR', 'CHI', 'CIN', 'CLE', 'DAL', 'DEN', 
            'DET', 'GB', 'HOU', 'IND', 'JAX', 'KC', 'LAC', 'LAR', 'LV', 'MIA', 
            'MIN', 'NE', 'NO', 'NYG', 'NYJ', 'PHI', 'PIT', 'SEA', 'SF', 'TB', 
            'TEN', 'WAS']
        nfl_set = set(nfl_team_abbreviations)
        
        picked_set = set(picked_list)
        unpicked_set = nfl_set.difference(picked_set)
        return sorted(list(unpicked_set))

    def ProcessData(self):
        nfl_team_abbreviations = [
            'ARI', 'ATL', 'BAL', 'BUF', 'CAR', 'CHI', 'CIN', 'CLE', 'DAL', 'DEN', 
            'DET', 'GB', 'HOU', 'IND', 'JAX', 'KC', 'LAC', 'LAR', 'LV', 'MIA', 
            'MIN', 'NE', 'NO', 'NYG', 'NYJ', 'PHI', 'PIT', 'SEA', 'SF', 'TB', 
            'TEN', 'WAS']
        nfl_set = set(nfl_team_abbreviations)
        self.Picked = dict(self.Data.groupby('owner_id')['team_pick'].unique())
        self.PickStatus = self.Data.groupby('owner_id')['team_pick'].unique().reset_index
        self.Status['Picked'] = self.Status['owner_id'].map(self.Picked)

        self.Status['Left'] = self.Status['Picked'].apply(self.find_unpicked)

    def DisplayLogos(self, fig, TeamList, xstart, ystart):
        TeamDesc = nfl.import_team_desc()
        TeamLogos = dict(zip(TeamDesc['team_abbr'],TeamDesc['team_logo_wikipedia']))
        x = xstart
        y = ystart
        for team in TeamList:
            x += .05
            logo = TeamLogos[team]

            fig.add_layout_image(
            dict(
                source=logo,
                xref="paper", yref="paper",
                x=x, y=y,
                sizex=0.2, sizey=0.2,
                xanchor="right", yanchor="bottom"
                )
                                )

## Class Pick' Em

In [24]:
class PickEm:
    def __init__(self, League):
        self.league = League
        self.id = League.id
        self.SettingsJSONtoDF()

    def SettingsJSONtoDF(self):
        league_status_request = requests.get(f'https://api.sleeper.app/v1/league/{self.id}/rosters')
        self.league_status_json = league_status_request.json()
        self.league_status_json_normal = json_normalize(self.league_status_json)
        data_for_df = []

        # Loop through each team's data in the list
        for team_data in self.league_status_json:
            owner_id = team_data['owner_id']
            points_by_leg = team_data['metadata']['points_by_leg']
            metadata = team_data['metadata']

            data_for_df.append({
                    'owner_id': owner_id,
                    'week': 0, 
                    'points': 0
                })
           
            
            for week, points in points_by_leg.items():
                
                
                week_number = int(week.split(':')[-1])
                
                # Append a dictionary with the owner_id to our master list
                data_for_df.append({
                    'owner_id': owner_id,
                    'week': week_number, 
                    'points': points
                })

        # Create the final DataFrame from the list of dictionaries
        df = pd.DataFrame(data_for_df)

        # Sort the DataFrame by owner_id and then by week for organization
        Data = df.sort_values(by=['owner_id', 'week']).reset_index(drop=True)
        Data['ScoreYTD'] = Data.groupby('owner_id')['points'].cumsum()
        Data['owner'] = Data['owner_id'].replace(self.league.OwnerIDDict)

        self.Data = Data
        self.Totals = self.Data.groupby(['owner_id'])['points'].sum()
        self.WeekResults = self.Data.groupby(['week'])['points'].sum()

    def Graph(self):
        
        fig2 = px.line(self.Data,x='week',y='ScoreYTD', color = 'owner',template='gridiron_ink',line_shape = 'spline', title = "<b>Legacy League Pick 'Em</b>", markers = True)
        fig2.update_xaxes(dtick=1,
                        tickfont=dict(
                size=18,         # Font size
            ))
        fig2.update_yaxes(dtick=10)
        fig2.update_layout(width=1200, height=800)
        
        # Adjust the thickness of the lines
        fig2.update_traces(line=dict(width=4),marker=dict(size=8, symbol="diamond"))  # Set the line width (e.g., 3 pixels)
        fig2.update_layout(legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1,
            title = ''
        ))
        # Customize the y-axis labels
        fig2.update_yaxes(
            tickfont=dict(
                size=24,         # Font size
            )
        )

        fig2.update_layout(uniformtext_minsize=10, uniformtext_mode='hide')

        # Update x-axis and y-axis titles with font customization
        fig2.update_layout(
            xaxis_title="Week",  # Set x-axis title
            yaxis_title="Correct Choices",   # Set y-axis title
            xaxis=dict(
                title_font=dict(
                    size=25          # Set font size for x-axis title
                )
            ),
            yaxis=dict(
                title_font=dict(
                    size=25          # Set font size for y-axis title
                )
            )
        )
        
        # Determine final wins and sort by them
        final_scores = [(d.name, d.x[-1], d.y[-1], d.line.color) for d in fig2.data]
        final_scores.sort(key=lambda x: -x[2])  # Sort by final win count, descending

        # Define a list of potential text positions to avoid overlap
        text_positions = ['middle right','top right', 'bottom right', 'top left', 'bottom left', 'middle left','top center','bottom center']

        previous_score = None
        position_index = 0

        for team_name, x_final, y_final, color in final_scores:
            display_text = f'{team_name}: {int(y_final)}'
            if y_final == previous_score:
                # Cycle through text positions to avoid overlap if scores are the same
                position_index = (position_index + 1) % len(text_positions)
            else:
                position_index = 0  # Reset position index when score changes

            text_position = text_positions[position_index]
            previous_score = y_final

            fig2.add_scatter(
                x=[x_final], y=[y_final],
                mode='markers+text',
                text=display_text,
                textfont=dict(color=color, size=14, weight = 'bold'),
                textposition=text_position,
                marker=dict(color=color, size=12),
                showlegend=False
                )    
        fig2.update_layout(margin=dict(l=80, r=80, t=120, b=80))  # Set left, right, top, bottom padding within the plot area

        weeks = self.Data.week.unique()
        weekNum = len(weeks) - 1
        WeekMax = self.Data.groupby('owner')['points'].sum().max()
        WeekMin = WeekMax - 35
        fig2.update_layout(xaxis=dict(range=[weekNum - 2.5, weekNum + .5]),yaxis=dict(range=[WeekMin, WeekMax + 5])) 
        fig2.update_layout(title = dict(y=.93)
        )
        
        apply_logo_to_fig(fig2)


        fig2.show()

## Class: All-Time

In [25]:
AllSeasonsBreakoutList = [Breakout_Matches_2019, Breakout_Matches_2020, Breakout_Matches_2021, Breakout_Matches_2022, Breakout_Matches_2023, Breakout_Matches_2024, Breakout_Matches_2025]
AllMatchesList = [Matches_2019, Matches_2020, Matches_2021, Matches_2022, Matches_2023, Matches_2025]

In [26]:
class AllTime:
    def __init__(self):
               
        self.MatchProcessing()
        self.SetTeamColors()
        self.BreakoutProcessing()
      
        
            
    def Update(self):
        
        self.MatchProcessing()
        
        self.BreakoutProcessing()
        
    def MatchProcessing(self):    
        
        Match_dfs = [df for week_dict in AllMatchesDict.values() for df in week_dict.values()]
           
        self.Matches =  pd.concat(Match_dfs, ignore_index=True)
        
        self.Matches['Abs Margin'] = abs(self.Matches['Margin'].astype(float)).round(2)
        self.Matches['Margin'] = round(self.Matches['Margin'],2) 
        
    def BreakoutProcessing(self):
        
        breakout_dfs = [df for week_dict in AllBreakoutDict.values() for df in week_dict.values()]
    
        self.Breakout =  pd.concat(breakout_dfs, ignore_index=True)
        
        self.Breakout_Playoffs = self.Breakout[self.Breakout.Season == 'Playoff']
        self.Breakout_Regular = self.Breakout[self.Breakout.Season == 'Regular']
    
    def SetTeamColors(self, color_dict:dict = None):
        self.teamcolors = {'JTizzzzle': 'lightsalmon', 'bgmaddox':'mediumpurple', 'jlglover':'cyan', 'RascalHazard':'pink', 
                    'BMoreBallers88':'gold', 'eegrady':'teal', 'DirtyCommie':'lime', 'jhuntmadd':'orange', 'RReclam':'green', 
                    'sgmaddox':'darkseagreen', 'RossLikeSauce':'red', 'InfiniteJesse':'magenta'}
        if color_dict != None:
            self.teamcolors = color_dict

    
    def OppWinPercentage(self, team, opp):
        OppTable = pd.pivot_table(self.Matches, values='Won',index='Team',columns='Opp_team',aggfunc='mean').round(2).fillna('')
        result = OppTable.loc[team,opp]
        return result
    
    def OppWinPercentageTable(self):
        all_teams = list(roster_ids_2025.values())
        result = pd.pivot_table(self.Matches, values='Won',index='Team',columns='Opp_team',aggfunc='mean').round(2).fillna('')
        result = result[result.columns.intersection(roster_ids_2025.values())].reset_index()
        result = result[result['Team'].isin(roster_ids_2025.values())].set_index('Team')
        result = result.reindex(index=all_teams, columns=all_teams)
        result = result.fillna(0.50)
        
        # result = result.astype(object)
        # np.fill_diagonal(result.values, '')
        self.OppWinPercentage = result
        #result = result.round(2)
        return result
    
    def TopPlayerScoresProcessing(self):
        
        self.TopTeamScores = self.Matches.sort_values('Total', ascending=False)[:10]
        self.TopTeamScores['Names'] = self.TopTeamScores.Team + ' [W' + self.TopTeamScores.Week.astype(str) + ' ' + self.TopTeamScores.Year.astype(str)+ ']' + ' - ' + self.TopTeamScores.Total.round(1).astype(str) 
        self.TopTeamScores['Year'] = self.TopTeamScores['Year'].astype(int)
        
        self.BottomTeamScores = self.Matches.sort_values('Total', ascending=True)[:10]
        self.BottomTeamScores['Names'] = self.BottomTeamScores.Team + ' [W' + self.BottomTeamScores.Week.astype(str) + ' ' + self.BottomTeamScores.Year.astype(str)+ ']' + ' - ' + self.BottomTeamScores.Total.round(1).astype(str) 
        self.BottomTeamScores['Year'] = self.BottomTeamScores['Year'].astype(int)
        
        self.TopPlayerScores = self.Breakout.sort_values('points', ascending=False)[:10]
        self.TopPlayerScores['Names'] = self.TopPlayerScores.team + ' [W' + self.TopPlayerScores.week_x.astype(str) + ' ' + self.TopPlayerScores.year.astype(str)+ ']' + ' - ' + self.TopPlayerScores.points.round(1).astype(str) 
        self.TopPlayerScores['Year'] = self.TopPlayerScores['year'].astype(int)

        self.BottomPlayerScores = self.Breakout.sort_values('points', ascending=True)[:10]
        self.BottomPlayerScores['Names'] = self.BottomPlayerScores.team + ' [W' + self.BottomPlayerScores.week_x.astype(str) + ' ' + self.BottomPlayerScores.year.astype(str)+ ']' + ' - ' + self.BottomPlayerScores.points.round(1).astype(str) 
        self.BottomPlayerScores['Year'] = self.BottomPlayerScores['year'].astype(int)

    
    ### GRAPHS
    
    def TopScores(self, Top_Bottom = 'Top', Team_Player = 'Team'):
        
        self.TopPlayerScoresProcessing()

        if Top_Bottom == 'Top' and Team_Player == 'Team':
            dfgraph = self.TopTeamScores
            Title = '<b>Hall of Fame</b><br><sup>Team</sup>'
            x_graph = 'Total'
            
        elif Top_Bottom == 'Bottom' and Team_Player == 'Team':
            dfgraph = self.BottomTeamScores
            Title = '<b>Hall of Shame</b><br><sup>Players</sup>'
            x_graph = "Total"
            
            
        elif Top_Bottom == 'Top' and Team_Player == 'Player':
            dfgraph = self.TopPlayerScores
            Title = "<b>Hall of Fame</b><br><sup>Player</sup>"
            x_graph = 'points'
        
        elif Top_Bottom == 'Bottom' and Team_Player == 'Player':
            dfgraph = self.BottomPlayerScores
            Title = "<b>Hall of Shame</b><br><sup>Player</sup>"
            x_graph = 'points'
            
        
            
        figTopScores = px.bar(dfgraph , y='Names', x=x_graph, template = 'gridiron_ink',
                             color = 'Team', orientation='h', text = 'Names', title =Title,)
                             
                             
                             
        figTopScores.update_layout(height = 1200, width = 900)
        figTopScores.update_layout(yaxis={'categoryorder': 'total ascending'})
        if Top_Bottom == 'Bottom':
            figTopScores.update_layout(yaxis = {'categoryorder':'total descending'})
        figTopScores.update_coloraxes(showscale=False)
        figTopScores.update_layout(title_font = dict(size=40),xaxis=dict(title=dict(text="")))   
        figTopScores.update_layout(
            font=dict(
                size=18,  # Set the font size here
            )
        )
        figTopScores.update_layout(margin=dict(t=130, b=100, l=40, r=40))
        figTopScores.update_layout(yaxis={'visible': False, 'showticklabels': False})
        apply_logo_to_fig(figTopScores)
        
        

        return figTopScores


    def AllTimeGraphing(self,df,week):
        df = pd.concat(AllMatches).sort_values('Week Index')
        fig2 = px.line(df,x='Week Index',y='Total Wins', color = 'Team',template='gridiron_ink',line_shape = 'spline', title = 'All-Time Wins')
        fig2.update_xaxes(
                        tickfont=dict(
                family='Courier New',  # Font family
                size=18,         # Font size
                color='white'    # Font color
            ))
        fig2.update_yaxes(dtick=10)
        fig2.update_layout(width=1400, height=900)
        # Adjust the thickness of the lines
        fig2.update_traces(line=dict(width=4))  # Set the line width (e.g., 3 pixels)
        fig2.update_layout(legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1,
            title = ''
        ))

        #fig2.update_layout(showlegend = False)
        # Customize the y-axis labels
        fig2.update_yaxes(
            tickfont=dict(
                size=20,         # Font size
            )
        )

        fig2.update_layout(uniformtext_minsize=10, uniformtext_mode='hide')

        # Update x-axis and y-axis titles with font customization
        fig2.update_layout(
            xaxis_title="Week",  # Set x-axis title
            yaxis_title="Wins",   # Set y-axis title
            xaxis=dict(dtick = 10,
                title_font=dict(
                    size=20          # Set font size for x-axis title
                )
            ),
            yaxis=dict(
                title_font=dict(
                    size=20          # Set font size for y-axis title
                )
            )
        )
        
        # Determine final wins and sort by them
        final_scores = [(d.name, d.x[-1], d.y[-1], d.line.color) for d in fig2.data]
        final_scores.sort(key=lambda x: -x[2])  # Sort by final win count, descending

        # Define a list of potential text positions to avoid overlap
        text_positions = ['middle right','top right', 'bottom right', 'top left', 'bottom left', 'middle left']

        previous_score = None
        position_index = 0
        '''
        for team_name, x_final, y_final, color in final_scores:
            if y_final == previous_score:
                # Cycle through text positions to avoid overlap if scores are the same
                position_index = (position_index + 1) % len(text_positions)
            else:
                position_index = 0  # Reset position index when score changes

            text_position = text_positions[position_index]
            previous_score = y_final

            fig2.add_scatter(
                x=[x_final], y=[y_final],
                mode='markers+text',
                text=[team_name],
                textfont=dict(family="Courier New",color=color, size=14, weight = 'bold'),
                textposition=text_position,
                marker=dict(color=color, size=12),
                showlegend=False
                )    
            fig2.update_layout(
            margin=dict(l=50, r=100, t=50, b=50)  # Set left, right, top, bottom padding within the plot area
                )
            
            '''
        fig2.update_layout(xaxis=dict(range=[0, week + 3])) 
        fig2.update_layout(title=dict(
                font=dict(
                    size=50,
                    family="Courier New"))) 
        
        # Find the last data point for each host
        last_points = AllMatches.groupby('Team').apply(lambda d: d.nlargest(1, 'Total Wins','last')).reset_index(drop=True)

        # Define the subset of hosts to style differently
        special_hosts = ['SleeperGawd69']
        special_hosts2 = ['sgmaddox', 'RReclam', 'BillyRayGonnaGetcha','jhuntmadd']
        special_hosts3 = ['eegrady', 'Just_Here_For_The_Snacks']
        special_hosts4 = []
        special_hosts5 = ['GurlyGirls', 'SweetDizzzzzle', 'YouthPastor']
        normal_teams = ['bgmaddox', 'jlglover', 'BMoreBallers88', 'RascalHazard', 'InfiniteJess', 'DirtyCommie', 'JTizzzzle', 'RossLikeSauce','akbrown29']

        for i, row in last_points.iterrows():
            if row['Team'] in special_hosts:
                # Apply special styling for the subset
                text_position = 'top left'
                marker_size = 12
                text_color = 'lightgrey'
                # Default offset
                x_offset = -20
                y_offset = -50
                show_arrow = True
            elif row['Team'] in special_hosts2:
                x_offset = 30
                y_offset = 25
                text_position = 'top left'
                marker_size = 12
                text_color = 'lightgrey'
                show_arrow = True
            elif row['Team'] in special_hosts3:
                x_offset = 50
                y_offset = -20
                text_position = 'top left'
                marker_size = 12
                text_color = 'lightgrey'
                show_arrow = True    
            elif row['Team'] in special_hosts4:
                x_offset = -75
                y_offset = -75
                text_position = 'middle right'
                marker_size = 12
                text_color = 'lightgrey'
                show_arrow = True   
            elif row['Team'] in special_hosts5:
                x_offset = -75
                y_offset = -75
                text_position = 'middle right'
                marker_size = 12
                text_color = 'lightgrey'
                show_arrow = True   
            elif row['Team'] in normal_teams:
                x_offset = 75
                y_offset = 0
                text_position = 'middle right'
                marker_size = 12
                text_color = 'lightgrey'
                show_arrow = True   
            else:
                # Default styling
                text_position = 'top right'
                marker_size = 12
                #text_color = 'lightgrey'
                # Default offset
                x_offset = -100
                y_offset = -0
                show_arrow = False
            fig2.add_annotation(
                x=row['Week Index'],
                y=row['Total Wins'],
                text=row['Team'],
                showarrow=show_arrow,
                arrowhead=2,
                ax=x_offset,
                ay=y_offset,
                font=dict(
                    size=18,
                    #color="white",
                    weight = 'bold'
                ),
                align="left"
            )
        fig2.update_layout(legend=dict(
            orientation="h",
            yanchor="bottom",
            y=-.30,
            xanchor="center",
            x=.5,
            title = '',
            font_size=18,
        ))
        return fig2
    
    
    def HighestScoringLosers(self, team_colors = None):
        
        Losers = self.Matches[self.Matches['Won'] == 0]
        TopTenLosers = Losers.sort_values('Total', ascending=False).head(10)
        TopTenLosers['TeamName'] = "<b>" + TopTenLosers['Team'] + '</b><br>' + "W" +TopTenLosers['Week'].astype(str) + " " + TopTenLosers['Year'].astype(str)
        TopTenLosers['Opp'] = round(TopTenLosers['Opp'],2)
        TopTenLosers['OppName'] = TopTenLosers['Opp_team'] + ' - ' + TopTenLosers['Opp'].astype(str)
        TopTenLosers = TopTenLosers.sort_values('Total')
        
        figLosers = go.Figure()
        figLosers.add_trace(go.Bar(
            x = TopTenLosers['Total'],
            y = TopTenLosers['TeamName'],
            name = 'Losers',
            orientation='h',
            text = TopTenLosers['Total'],
            textfont=dict(size=25)
        ))
        figLosers.add_trace(go.Bar(
            x = TopTenLosers['Opp'],
            y = TopTenLosers['TeamName'],
            name = 'Winners',
            orientation='h',
            opacity=.7,
            text = TopTenLosers['OppName'],
            textfont=dict(size=14),
            ))
        figLosers.update_layout(template="gridiron_ink")
        figLosers.update_layout(width=800, height=1200)
        figLosers.update_layout(showlegend=False)
        figLosers.update_yaxes(
                tickfont=dict(
                    size=18,         # Font size
                ),
                title = None,
            )
        figLosers.update_layout(
            title = "<b>Biggest Losers</b><br><sup>Highest Scores in Loss</sup>",
        )
        figLosers.update_layout(margin=dict(t=130, b=100, l=200, r=40))
        apply_logo_to_fig(figLosers, xval=.35)


        return figLosers
        
    def SmallestMargins(self):
        TenSmallestMargins = self.Matches.sort_values('Abs Margin', ascending=True)[:20]
        TenSmallestMargins = TenSmallestMargins.sort_values('Margin').reset_index()
        TenSmallestMargins['TeamGraph'] = TenSmallestMargins['Team'] + ' - ' + TenSmallestMargins['Year'].astype(str) + ' [' + TenSmallestMargins['Margin'].astype(str) + ']'
        
    
        figMargin = px.bar(TenSmallestMargins, x='Margin',y=TenSmallestMargins.index,template = 'gridiron_ink',title='<b>Top 10 Smallest Margins</b>', color = 'Week Index', orientation='h', text='TeamGraph' )
        figMargin.update_layout(barmode='stack', yaxis={'categoryorder':'total ascending'})
        figMargin.update_layout(width=1200, height=800)
        
        figMargin.update_traces(textfont_size=20, textangle=0, cliponaxis=True, textposition = 'auto', textfont=dict(weight='bold', size=15   # Font color
                ))
        figMargin.update_layout(
                xaxis_title="Margin",  # Set x-axis title
                yaxis_title="",   # Set y-axis title
                xaxis=dict(
                    title_font=dict(
                        size=30,          # Set font size for x-axis title
                        color ='red',
                        weight = 'bold'
                    )
                ),
                yaxis=dict(
                    title_font=dict(
                        size=30,          # Set font size for y-axis title
                        color = 'green',
                        weight = 'bold'
                    )
                )
            )
        figMargin.update_layout(yaxis=dict(showticklabels=False))
        #Update the layout to hide the legend:
        figMargin.update(layout_coloraxis_showscale=False)
        figMargin.update_xaxes(
                tickfont=dict(
                    size=22,         # Font size
                ),
                title = None,
                dtick=.2
            )
        figMargin.update_layout(title=dict(y=.90))
        figMargin.update_layout(margin=dict(t=130, b=100, l=40, r=40))

        apply_logo_to_fig(figMargin,yval= -0.07)

        return figMargin
        
    def HallofShame_Team(self):
        Worst10 = self.Matches.sort_values('Total')[0:10]
        Worst10['Total'] = Worst10['Total'].astype(int)
        Worst10['TeamName'] = '<b>' + Worst10['Team'] + '</b><br>W' + Worst10['Week'].astype(str) + " " + Worst10['Year'].astype(str)
        Worst10 = Worst10.sort_values('Total')
        
        
        
        figWorst = px.bar(Worst10, x='Total',y='TeamName', color = 'Team', orientation='h', template='gridiron_ink', title = '<b>Hall of Shame</b><br><sup>Team</sup>', text = 'Total')
        figWorst.update_layout(height = 1200, width= 800, showlegend=False)
        figWorst.update_layout(title_font = dict(size=45))
        figWorst.update_xaxes(
                tickfont=dict(
                    size=16,         # Font size
                ),
                title = None,
            )
        figWorst.update_yaxes(
                tickfont=dict(
                    size=16,         # Font size
                ),
                title = None,
                categoryorder="total descending",
            )

        # Add the image over a specific bar (adjust xref and yref as needed for placement)
        figWorst.update_traces(textposition='inside', textfont_size=80)
        figWorst.update_layout(margin=dict(t=130, b=100, l=200, r=40))
        
        apply_logo_to_fig(figWorst,xval=.40)

        return figWorst
    
    def HallofFame_Team(self):
        Best10 = self.Matches.sort_values('Total', ascending=False)[0:10]
        Best10['Total'] = Best10['Total'].astype(int)
        Best10['TeamName'] = '<b>'+ Best10['Team'] + '</b>' + '<br>' + "W" +Best10['Week'].astype(str) + " " + Best10['Year'].astype(str)
        
        figBest = px.bar(Best10, x='Total',y='TeamName', color = 'Team', orientation='h', template='gridiron_ink', title = '<b>Hall of Fame</b><br><sup>Team</sup>', text = 'Total')
        figBest.update_layout(height = 1200, width= 800, showlegend=False)
        figBest.update_xaxes(
                tickfont=dict(
                    size=16,         # Font size
                ),
                title = None,
                
            )
        figBest.update_yaxes(
                tickfont=dict(
                    size=16,         # Font size
                ),
                title = None,
                categoryorder="total ascending",
            )
        figBest.update_layout(
            font=dict(
                size=20,  # Set the font size here
            )
        )
        figBest.update_layout(margin=dict(t=130, b=100, l=180, r=40))
        figBest.update_traces(textposition='inside', textfont_size=80)

        
        apply_logo_to_fig(figBest,xval=.40)
        return figBest
        
    def HallofFame_Player(self):
            
        Best10Players = self.Breakout.sort_values('points', ascending=False)[0:10]
        Best10Players['TeamName'] = '<b>' + Best10Players['team'] + '</b><br><sup>' + "W" +Best10Players['week_x'].astype(str) + " " + Best10Players['year'].astype(str) + '</sup>'
        Best10Players['Player-Points'] = '<b>' + Best10Players.player + '</b><br>' + Best10Players.points.astype(str)
        
        figBestPlayers = px.bar(Best10Players, x='points',y='TeamName', color = 'team', orientation='h', 
                        template='gridiron_ink', title = '<b>Hall of Fame</b><br><sup>Players</sup>', text = 'Player-Points',
                        )
        figBestPlayers.update_layout(height = 1200, width= 800, showlegend=False)
        figBestPlayers.update_xaxes(
                tickfont=dict(
                    size=16,         # Font size
                ),
                title = None,
                
            )
        figBestPlayers.update_yaxes(
                tickfont=dict(
                    size=16,         # Font size
                ),
                title = None,
                categoryorder="total ascending",
            )
        
        figBestPlayers.update_layout(margin=dict(t=130, b=100, l=180, r=40))
        figBestPlayers.update_traces(textposition='inside', textfont_size=55)

        
        apply_logo_to_fig(figBestPlayers,xval=.40)

        return figBestPlayers
        
    def ForAgainstwithTeams(self):
        OpponentPoints = self.Breakout.groupby(['team','opponent_team'])['points'].sum().reset_index().sort_values('points', ascending=False)
        OpponentPointsNoTeam = self.Breakout.groupby(['team','opponent_team'])['points'].sum().round(1).reset_index().sort_values('points', ascending=False)
        OpponentPointsNoTeamTOP =  OpponentPointsNoTeam.iloc[0:10]
        OpponentPointsNoTeamTOP['TeamVs'] = OpponentPointsNoTeamTOP.team + ' vs. ' + OpponentPointsNoTeamTOP.opponent_team
        OpponentPointsNoTeamTOP['Purpose'] = 'Points Against...'    
        
        TeamPoints = self.Breakout.groupby(['team','recent_teams'])['points'].sum().round(1).reset_index().sort_values('points', ascending=False)
        TeamPointsTOP = TeamPoints.iloc[0:10]
    
        #TeamPointsTOP['color'] = TeamPointsTOP.team.map(teamcolors)
        TeamPointsTOP['TeamVs'] = TeamPointsTOP.team + ' w/ ' + TeamPointsTOP.recent_teams
        TeamPointsTOP['Purpose'] = 'Points With...'
        
        JointTopBottom = pd.concat([OpponentPointsNoTeamTOP,TeamPointsTOP ])
        
        figTeamPoints = go.Figure()

        figTeamPoints = make_subplots(
                    rows=2, cols=1, 
                    shared_xaxes=False,
                    vertical_spacing =  .1,
                    #column_widths=[0.5, 0.55],  # Adjust the width of each subplot
                    specs=[[{"type": "bar"}],
                            [{"type": "bar"}]],
                    subplot_titles=['Points With...','Points vs...']# Specify the chart types
                )
        figTeamPoints.add_trace(
                    go.Bar(
                        x=TeamPointsTOP['points'], 
                        y=TeamPointsTOP['TeamVs'], 
                        
                        text=TeamPointsTOP['points'],
                        textangle = 0,
                        textposition='auto',
                        showlegend=False,
                        orientation='h', 
                        marker_color = TeamPointsTOP.points,
                        opacity=.8,
                        textfont=dict(size=20)
                    ),
                    row=1, col=1
                )
        figTeamPoints.add_trace(
                    go.Bar(
                        x=OpponentPointsNoTeamTOP['points'], 
                        y=OpponentPointsNoTeamTOP['TeamVs'], 
                        
                        text=OpponentPointsNoTeamTOP['points'],
                        textangle = 0,
                        textposition='auto',
                        showlegend=False,
                        orientation='h',
                        marker_color = OpponentPointsNoTeamTOP.points,
                        opacity=.8, 
                    ),
                    row=2, col=1
                )

        figTeamPoints.update_layout(height = 1200, width = 900, template = 'gridiron_ink', barcornerradius = 7)
        figTeamPoints.update_xaxes(side='bottom')
        figTeamPoints.update_layout(yaxis2 = {'categoryorder': 'total ascending'})
        figTeamPoints.update_annotations(font_size=25)
        figTeamPoints.update_layout(title="<b>Points With & Against NFL Teams</b>")
        
        figTeamPoints.update_layout(xaxis1=dict(side='bottom'),xaxis2=dict(side='bottom'))

        figTeamPoints.update_layout(margin=dict(t=100, b=100, l=220, r=40))
        
        apply_logo_to_fig(figTeamPoints,xval=.40, yval=-0.06)


        return figTeamPoints

## Class: Side Bets

In [27]:
class SideBet:
    def __init__(self,League,Season, DictofWeeks = None, ):
               
        self.DictofWeeks = DictofWeeks
        self.League = League
        self.Season = Season
        
        self.SetTeamColors()

    
    
    
    def UpdateColors2(self,WeekObj ,fig):
        """
        Updates the y-axis tick labels of a figure to use team-specific colors.
        """
        # --- THE FIX ---
        # Instead of 'categoryarray', we get labels directly from the figure's data trace.
        # This is a more reliable way to access the list of teams on the y-axis.
        if not fig.data or fig.data[0].y is None:
            # Failsafe in case the figure has no data
            return fig

        y_axis_labels = fig.data[0].y
        
        # Create a new list of HTML-styled labels with the correct colors.
        styled_labels = []
        for label in y_axis_labels:
            # Look up the color for the team from your dictionary
            color = WeekObj.teamcolors.get(label, 'white') # Default to white if not found
            styled_labels.append(f"<span style='color:{color}'>{label}</span>")

        # Update the y-axis to use the new styled text.
        # 'tickvals' provides the original labels to map against.
        # 'ticktext' provides the new, styled labels to display.
        fig.update_yaxes(
            tickvals=y_axis_labels,
            ticktext=styled_labels
        )
                
        return fig
    
    def SetTeamColors(self, color_dict:dict = None):
        Members = self.Season.Matches.Team.unique()
        self.teamcolors = dict(zip(Members,coastal_colorway))
        
        
        if color_dict != None:
            self.teamcolors = color_dict
    def Scoreboard(self, tally = None):
            
            def calc_table_height(df, base=208, height_per_row=20, char_limit=30, height_padding=16.5):
                '''
                df: The dataframe with only the columns you want to plot
                base: The base height of the table (header without any rows)
                height_per_row: The height that one row requires
                char_limit: If the length of a value crosses this limit, the row's height needs to be expanded to fit the value
                height_padding: Extra height in a row when a length of value exceeds char_limit
                '''
                total_height = 0 + base
                for x in range(df.shape[0]):
                    total_height += height_per_row
                for y in range(df.shape[1]):
                    if len(str(df.iloc[x][y])) > char_limit:
                        total_height += height_padding
                return total_height

            if tally != None:
                 tally_list = tally
            else:
                tally_list = [['JTizzzzle',1],
                ['eegrady',1],
                ['cosmodromedary',1],
                ['bgmaddox',3],
                ['sgmaddox',1],
                ['jhuntmadd',3],
                ['RascalHazard',0],
                ['InfiniteJesse',0],
                ['BMoreBallers88',1],
                ['RossLikeSauce',0],
                ['DirtyCommie',3],
                ['jlglover',0]]

            tallyDF = pd.DataFrame(tally_list, columns=['Team','Wins'])
            tallyDF['Prize $'] = '$' + (tallyDF.Wins * 20).astype(str)

            SideBetWeeklyWins_list = [["<b>WEEK 1:</b> I'm flying, Jack! - Team with the highest score (starters only)",'cosmodromedary'],
            ['<b>WEEK 2:</b> Look At These TDs - Team with the most offensive touchdowns scored','DirtyCommie'],
            ['<b>WEEK 3:</b> Big Helpers, too (just ask my mom): Most combined points with starting D/ST & Kicker','jhuntmadd'],
            ['<b>WEEK 4:</b> Blackjack - Team with a starter closest to 21 points without going over','sgmaddox & jhuntmadd'],
            ['<b>WEEK 5:</b> The Replacements - Team with the highest total points for their bench','DirtyCommie'],
            ['<b>WEEK 6:</b> The Boom & Bust: Team with the largest point differential between their single highest-scoring starter and their single lowest-scoring starter.','eegrady'],
            ['<b>WEEK 7:</b> Campus Rush Week - Total rush yards for team (active or bench)','bgmaddox'],
            ['<b>WEEK 8:</b> All Hands on Deck: Team with the most starting players who score over 15 points','bgmaddox'],
            ['<b>WEEK 9:</b> The Old Man & Young Buck: Best combined score from a starting player over 30 and a rookie','JTizzzzle'],
            ['<b>WEEK 10:</b> NFL Franchise Week - Team with the highest point total of players from the same franchise (active or bench)','DirtyCommie'],
            ['<b>WEEK 11:</b> Please not the Jets (Trade Deadline Week) - Team with the most trades this seasons wins','jhmadd & BMoreBallers88'],
            ['<b>WEEK 12:</b> Go Long - Team with the Starting QB with the highest completion % (over 10 throws)','bgmaddox'],
            ["<b>WEEK 13:</b> Coffee's For Closers - Team that beats its opponent by the smallest margin of victory",''],
            ['<b>WEEK 14:</b> Breaking of the Tie (if needed) - Choose 3 non-QB players. Highest combined total wins.','']]

            SideBetWeeklyWins = pd.DataFrame(SideBetWeeklyWins_list, columns=['Side Bet','Winner'])

            figSideBets = make_subplots(
                rows=1, cols=2, 
                shared_xaxes=False,
                horizontal_spacing=0.08, 
                vertical_spacing=0.05,
                shared_yaxes=True,
                column_widths=[0.35, 0.5],  # Adjust the width of each subplot
                specs=[[{"type": "pie"}, {"type": "table"}]]
                    
                #subplot_titles=['Matchup Schedule','Win History']# Specify the chart types
            )
            tallyDF = tallyDF.sort_values('Wins')
            headerColor = 'grey'
            rowEvenColor = 'lightgrey'
            rowOddColor = 'white'
            df = SideBetWeeklyWins

            figSideBets.add_trace(
                go.Pie(values=tallyDF['Wins'],text=tallyDF['Team']),
                
                row=1, col=1)
            figSideBets.add_trace(go.Table(
                columnorder = [1,2],
                columnwidth = [65,25],
                header=dict(values=list(df.columns),
                            #fill_color='paleturquoise',
                            align=['center','center'],
                            font=dict(size=25, weight = 'bold', color = 'black')),
                cells=dict(values=[df['Side Bet'], df.Winner],
                        fill_color = [[rowOddColor,rowEvenColor,rowOddColor, rowEvenColor]*5],
                        align=['left','center'],
                        height = 30,
                        font=dict(color='black', size=14))
                                        ), row=1, col=2)
            figSideBets.update_layout(height = calc_table_height(SideBetWeeklyWins))
            # figSideBets.update_polars(bgcolor='#BDE2FF')


            # figSideBets.update_layout(
            #     # showlegend = True,
            #     polar=dict(
            #         angularaxis=dict(
            #             showline=False,
            #             tickfont = dict(
            #                  size = 15,
            #                  color = 'white',
            #                 weight = 'bold'
            #             )),
            #         radialaxis=dict(
            #             tickvals=[0,1,2,3,4],  # Specify the tick values
            #             ticktext=['', '1 Win','2 Wins', '3 Wins', '4 Wins'],  # Customize tick labels
            #             tickfont = dict(
            #                  size = 22,
            #                  color = 'black',
            #                 weight = 'bold'
            #             )
            #         )))
            
            figSideBets.update_layout(width=1200, height=1200, title_text = '<b>Side Bet Tally</b>')

            apply_logo_to_fig(figSideBets)
            figSideBets.update_layout(title ={'y':.93, 'font':dict(size=65)})
            self.Tally = tallyDF
            return figSideBets
        
    
    
    def Week1(self, WeekObj,top):
        
        df = WeekObj.WeeklyNoMatches
        df = df.sort_values('Total', ascending = False)
        top = df['Team'][0]
        
        #points = df.drop(axis = 1,columns = ['Total','Won','Week','Opp','Matchup']).applymap(lambda x: float(list(x.values())[0]))
        points = df.applymap(lambda x: float(list(x.values())[0]) if isinstance(x, dict) else x)
        points = points.round(1).reset_index()
        
        default_color = '#F94144'
    
        colors = {top: "#17BECF"}
        
        #points = df.sort_values('Total', ascending = False)
        team_list = df.sort_values('Total', ascending = True).index.tolist()
        
        #Ranked = df.index.sort_values('Total', ascending = True).unique()
        SizeZip = dict(zip(team_list,range(12,30)))
        print(SizeZip)

        color_discrete_map = {
            c: colors.get(c, default_color) 
            for c in team_list}


        fig1 = px.bar(points, y='Team',x=position_list,template = 'gridiron_ink',color = "Team", text_auto=True, title = f'Week {Week} Side Bet', orientation='h',color_discrete_map=color_discrete_map)
        
        #Update the layout to hide the legend:
        fig1.update(layout_coloraxis_showscale=False)
        
        # Adjust the figure size
        fig1.update_layout(title=dict(
                font=dict(
                    size=50,)))  # Set the width and height in pixels
        fig1.update_traces(textfont_size=12, textangle=0, cliponaxis=True, textposition = 'auto', textfont=dict(weight='bold',  # Font family
                size=12   # Font color
            ))
        
        # Customize the x-axis labels
        fig1.update_xaxes(
            tickfont=dict(
                size=16,         # Font size
            ),
            title = None
        )

        # Customize the y-axis labels
        fig1.update_yaxes(
            tickfont=dict(
                size=18,         # Font size
            ),
            title=None
        )

        fig1.update(layout_coloraxis_showscale=False)
        fig1.update_layout(showlegend=False)
        fig1.update_traces(insidetextanchor= 'middle')
        
        
        annotations = []
        for i, val in enumerate(points.Total):
            annotations.append(
                dict(
                    x=val+10, 
                    y=points.Team[i], 
                    text=str(val), 
                    xanchor='left', 
                    yanchor='middle', 
                    showarrow=False, 
                    font=dict(size=SizeZip[points.Team[i]],)
                    )   
                            )

        fig1.update_layout(annotations=annotations)

        fig1.update_traces(marker_line_width=1.5,marker_line_color='black')
        
        fig1.update_traces(insidetextanchor= 'middle')
        fig1.update_layout(
            uniformtext_minsize=12,
            uniformtext_mode='hide'
            )
        fig1.add_annotation(
        text="Bar Order: QB ------------> DEF",
        xref="paper", yref="paper",
        x=0.05, y=-.06, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            size=15,
        )
        )

        return fig1
    

    
    
    def Week2(self, WeekObj):
        Week2 = WeekObj.Breakout
        #Week2 = WeeklyNFLData_24[WeeklyNFLData_24['week'] == 2]
        td_cols = [col for col in Week2.columns if 'tds' in col.lower()]
        td_cols.remove('def_tds')
        td_cols.remove('fumble_recovery_tds')
        info_cols = []
        info_cols.append('player_display_name')
        info_cols.append('team')
        info_cols.append('position')
        info_cols.append('player')

        df_cols = info_cols + td_cols

        #Week2filtered= Week2[td_cols]
        #Week2Data = week2Breakout2024.merge(Week2filtered,left_on='player', right_on='player_display_name')
        Week2Data = Week2[Week2['starter']==1]
        Week2Data = Week2Data[df_cols]
        Week2Data.loc[94,'receiving_tds'] = 1.0
        Week2Data.fillna(0, inplace=True)

        Week2Data['Total']= Week2Data['passing_tds'] + Week2Data['rushing_tds'] + Week2Data['receiving_tds'] + Week2Data['special_teams_tds']

        Week2Totals = Week2Data.groupby(['team','position']).agg('sum')

        Week2Groups = Week2Data.groupby('team')
        Week2Groups.get_group('bgmaddox').sort_values('position')

        Week2Totals.sort_values('Total', ascending=False)
        Week2Totals.sort_values('Total', ascending=False)
        Week2Totals = Week2Totals.sort_values('Total', ascending=False).reset_index()
        
        Week2Data = Week2Data.sort_values(['player'], ascending=False)

        
        # Graph

        fig = px.bar(Week2Totals,y='team',x='Total',color='position' ,title = f'Week {WeekObj.week} Side Bet', orientation='h',text=f'Total')

        fig.update_traces(insidetextanchor= 'middle',textfont=dict(
                size=35, weight = 'bold'))

        fig.update_layout(yaxis={'categoryorder':'total ascending'})
        fig.update_layout(
            showlegend = True,
            legend=dict(
                x=.4,
                y=1.06,
                xref = 'paper',
                xanchor = 'center',
                orientation = 'h',
                #traceorder="reversed",
                title = 'Position',
                font=dict(
                    size=18,
                )#,
                #bgcolor="LightSteelBlue",
                #bordercolor="Black",
                #borderwidth=2
            )
        )
        fig.update_layout(
                xaxis_title="",  # Set x-axis title
                yaxis_title="")
        fig.update_xaxes(
                tickfont=dict(
                    size=16,         # Font size
                ),
                title = None
            )

            # Customize the y-axis labels
        fig.update_yaxes(
                tickfont=dict(
                    size=25, weight ='bold'       # Font size
                ),
                title=None
            )
        fig.update_traces(marker_line_width=2,marker_line_color='black')
        fig.update_layout(margin=dict(t=130, b=100, l=220, r=40), title ={'y':.94})
        
        
        apply_logo_to_fig(fig,xval=.43, yval=-0.06)
        self.UpdateColors2(WeekObj,fig)
        self.Week2Data = Week2Data
        self.Week2Totals = Week2Totals

        fig.show()

    def Week3(self, WeekObj):

        ## Best DF/K Combo

        positions = ['DEF','K']

        df = WeekObj.Breakout
        df = df[df['starter'] == 1]
        df = df[df['position'].isin(positions)]
        df['display_text'] = '<b>' + df['points'].astype(str) + '</b><br><sup>' + df['player'] +'</sup>'


        ## GRAPH

        fig = px.bar(df,y='team',x='points',color='position' ,title = f'<b>Week {WeekObj.week} Side Bet</b><br><sup>Best DEF/K Combo</sup>', orientation='h',text='display_text', barmode='relative')

        fig.update_layout(
                xaxis_title="",  # Set x-axis title
                yaxis_title="")

        fig.update_xaxes(
                tickfont=dict(
                    size=16,         # Font size
                ),
                title = None
            )
        fig.update_layout(yaxis={'categoryorder':'total ascending'})

        fig.update_layout(
            showlegend = True,
            legend=dict(
                x=.8,
                y=1.06,
                xref = 'paper',
                xanchor = 'center',
                orientation = 'h',
                #traceorder="reversed",
                title = '',
                font=dict(
                    size=18,
                )#,
                #bgcolor="LightSteelBlue",
                #bordercolor="Black",
                #borderwidth=2
            )
        )
        fig.update_traces(insidetextanchor= 'middle',textfont=dict(
                size=35, weight = 'bold'))
        
        fig.update_traces(textfont_size=35, textangle=0, cliponaxis=True, textposition = 'inside', textfont=dict(weight='bold',  # Font family
                size=35   # Font color
            ))
        apply_logo_to_fig(fig,xval=.43, yval=-0.06)
        fig.update_layout(margin=dict(t=130, b=100, l=230, r=40), title ={'y':.94})

        fig.update_yaxes(
                tickfont=dict(
                    size=25, weight ='bold'       # Font size
                ),
                title=None
            )
        self.UpdateColors2(WeekObj,fig)
        self.Week3df = df
        

        fig.show()

    def Week4(self, WeekObj):

        Week = WeekObj.week

        Week4SideBet = WeekObj.Breakout[WeekObj.Breakout['points'] <= 22]
        Week4SideBet = Week4SideBet[Week4SideBet['points'] >= 17]
        Week4SideBet = Week4SideBet.sort_values('points', ascending = False)

        df = Week4SideBet.head(15).sort_values('points', ascending = False)

        df['string_pts'] = df['points'].astype(str)
        df['team-points'] = df['team'] + "<br><sup>" + df['string_pts'] + '</sup>'
        df = df.sort_values('points', ascending = True)
      
        team_list = df['team'].unique()

        


        fig1 = px.bar(df, y='player',x='points',template = 'gridiron_ink', color = 'team', text='team-points', #text_auto=True, 
                        title = f'<b>Week {Week} Side Bet</b><br><sup>Blackjack</sup>', orientation='h'
                    )
        
        #Update the layout to hide the legend:
        fig1.update(layout_coloraxis_showscale=False)
        
        # Adjust the figure size
        # fig1.update_layout(width=800, height=1200)
        fig1.update_traces(textfont_size=20, textangle=0, cliponaxis=True, textposition = 'inside', textfont=dict(weight='bold',  # Font family
                size=20   # Font color
            ))
        fig1.update_layout(yaxis={'categoryorder':'total ascending'})
        # Customize the x-axis labels
        fig1.update_xaxes(
            tickfont=dict(
                size=16,         # Font size
            ),
            title = None
        )

        # Customize the y-axis labels
        fig1.update_yaxes(
            tickfont=dict(
                size=18,         # Font size
            ),
            title=None
        )

        #fig1.update(layout_coloraxis_showscale=False)
        fig1.update_layout(showlegend=False)
        
        fig1.update_layout(legend=dict(
        orientation="h",
        #yanchor="bottom",
        #y=-.1,
        xanchor="center",
        x=.5,
        title = ""
    ))
        fig1.add_vline(x=21, line_width=3, line_dash="dash",
        line_color="red", annotation_text="Bust Line", annotation_position="top right",annotation_font_size=25,
        annotation_font_color="red")

        fig1.update_layout(margin=dict(t=130, b=100, l=220, r=40), title ={'y':.94})
        
        
        apply_logo_to_fig(fig1,xval=.43, yval=-0.06)


        return fig1
    

    def Week5(self, WeekObj):
        Week5SideBetdf = WeekObj.Breakout
        Week5SideBetdf = Week5SideBetdf[Week5SideBetdf['starter']==0]
        Week5List = Week5SideBetdf.groupby('team')['points'].sum().reset_index()
        Week5List.sort_values('points')
        figWeek5 = px.bar(Week5SideBetdf, x='points',y='team',template = 'gridiron_ink',title=f'<b>Week {WeekObj.week} Side Bet</b><br><sup>Best Bench</sup>', color = 'position',
                           orientation='h', text = 'player' )
        figWeek5.update_layout(barmode='stack', yaxis={'categoryorder':'total ascending'})
            # Adjust the figure size
        figWeek5.update_layout(width=1200, height=800, showlegend = True)
        
        figWeek5.update_traces(textfont_size=12, textangle=0, cliponaxis=True, textposition = 'inside', textfont=dict(weight='bold',  # Font family
                    size=12   # Font color
                ))
        # Update the line thickness
        figWeek5.update_layout(
                xaxis_title="Points",  # Set x-axis title
                yaxis_title="Teams",   # Set y-axis title
                xaxis=dict(
                    title_font=dict(
                        size=30,          # Set font size for x-axis title
                        color ='red',
                        weight = 'bold'
                    )
                ),
                yaxis=dict(
                    title_font=dict(
                        size=30,          # Set font size for y-axis title
                        color = 'green',
                        weight = 'bold'
                    )
                )
            )
        figWeek5.update_layout(
            legend=dict(
                x=0.37,
                y=1.08,
                xanchor = 'center',
                #traceorder="reversed",
                title = 'Position',
                font=dict(
                    size=15,
                )#,
                #bgcolor="LightSteelBlue",
                #bordercolor="Black",
                #borderwidth=2
            )
        )

        figWeek5.update_xaxes(
                tickfont=dict(
                    size=16,         # Font size
                ),
                title = None
            )

            # Customize the y-axis labels
        figWeek5.update_yaxes(
                tickfont=dict(
                    size=25,         # Font size
                ),
                title=None
            )
        apply_logo_to_fig(figWeek5,xval=.43, yval=-0.06)
        figWeek5.update_layout(margin=dict(t=160, b=100, l=230, r=40), title ={'y':.93})
        self.UpdateColors2(WeekObj,figWeek5)

        
        return figWeek5

    def Week5Graph(self, df, WeekObj,top):
        df = WeekObj.Match
        df = df.sort_values('Total', ascending = False)
        points = df.drop(axis = 1,columns = ['Total','Won','Week','Opp','Matchup']).applymap(lambda x: float(list(x.values())[0]))
        points = points.round(2).reset_index()
        
        default_color = "blue"
        colors = {top: "red"}

        team_list = points['Team'].unique()

        color_discrete_map = {
            c: colors.get(c, default_color) 
            for c in team_list}


        fig1 = px.bar(points, y='Team',x=position_list,template = 'gridiron_ink',color = "Team", text_auto=True, title = f'Week {Week} Side Bet', orientation='h',color_discrete_map=color_discrete_map)
        
        #Update the layout to hide the legend:
        fig1.update(layout_coloraxis_showscale=False)
        
        fig1.update_layout(barcornerradius=13)
        # Adjust the figure size
        fig1.update_layout(width=800, height=1200)
        fig1.update_layout(title=dict(
                font=dict(
                    size=50,
                    family="Courier New")))  # Set the width and height in pixels
        fig1.update_traces(textfont_size=12, textangle=0, cliponaxis=True, textposition = 'auto', textfont=dict(weight='bold',  # Font family
                size=12   # Font color
            ))
        
        # Customize the x-axis labels
        fig1.update_xaxes(
            tickfont=dict(
                size=16,         # Font size
            ),
            title = None
        )

        # Customize the y-axis labels
        fig1.update_yaxes(
            tickfont=dict(
                size=18,         # Font size
            ),
            title=None
        )

        fig1.update(layout_coloraxis_showscale=False)
        fig1.update_layout(showlegend=False)
        # Adjust the figure size
        fig1.update_layout(width=800, height=1200)
        fig1.update_layout(title=dict(
                ))  # Set the width and height in pixels
        fig1.update_traces(textfont_size=12, textangle=0, cliponaxis=True, textposition = 'inside', textfont=dict(weight='bold',  
                size=12   # Font color
            ))
        


        fig1.show()
        return fig1

    def Week6(self, WeekObj):
        df6 = WeekObj.Breakout
        df6 = df6[df6.starter == 1]
        df6group = df6.groupby('team')
        BustBoom = pd.DataFrame()

        for team in df6.team.unique():
            teamdf = df6group.get_group(team)
            maxrow = teamdf[teamdf.points == teamdf.points.max()]
            minrow = teamdf[teamdf.points == teamdf.points.min()]
            teamrows = pd.concat([maxrow,minrow])
            teamrows['difference'] = teamrows.points.sum().round(1)

            BustBoom = pd.concat([BustBoom,teamrows])


        figWeek6 = px.bar(BustBoom, y='team',x='points',template = 'gridiron_ink',color = "team", title = f'Week {WeekObj.week} Side Bet', orientation='h',barmode='overlay', text = 'player')
        figWeek6.update_traces( textfont_size=20  # Font color
            )
        
        figWeek6.update_layout(
                xaxis_title="",  # Set x-axis title
                yaxis_title="")
        
        # self.UpdateColors2(WeekObj,figWeek6)

        apply_logo_to_fig(figWeek6)

        return figWeek6
    

    def Week7(self, WeekObj):
        Week7Data = WeekObj.Breakout
        Week7Groups = Week7Data.groupby('team')['rushing_yards'].sum()
        Week7Groups = Week7Groups.reset_index()


        figWeek7 = px.bar(Week7Data,y='team',x='rushing_yards',color='position' ,template = 'gridiron_ink',title = f'<b>Week {WeekObj.week} Side Bet</b><br><sup>Rush Week</sup>', 
                          orientation='h')
        
        figWeek7.update_layout(width=800, height=1200)
        
        
        figWeek7.update_layout(yaxis={'categoryorder':'total ascending'})
        
        figWeek7.update_layout(
                xaxis_title="",  # Set x-axis title
                yaxis_title="")
        figWeek7.update_xaxes(
                tickfont=dict(
                    size=16,         # Font size
              ),
                title = None
            )

            # Customize the y-axis labels
        figWeek7.update_yaxes(
                tickfont=dict(
                 size=18,         # Font size
                ),
                title=None
            )
        # figWeek7.update_traces(marker_line_width=2,marker_line_color='black')
        
        
        # Add annotations for rushing yards
        for i, row in enumerate(Week7Groups['team']):
            figWeek7.add_annotation(
                x=Week7Groups['rushing_yards'][i].sum()+5,  # Rushing yards for x position
                y=Week7Groups['team'][i],  # Team name for y position
                text=f"{Week7Groups['rushing_yards'][i]} yards",  # Annotation text
                showarrow=False,  # No arrow
                font=dict(
                    size=13,
                ),
                xanchor='left',  # Align to the left of the bar
                yanchor='middle'
            )
        self.Week7Data = Week7Groups

        self.UpdateColors2(WeekObj,figWeek7)
        apply_logo_to_fig(figWeek7, xval=.4)
        figWeek7.update_layout(margin=dict(t=160, b=100, l=180, r=40), title ={'y':.93})


        return figWeek7
    
    def Week8(self,WeekObj):

        df8 = WeekObj.Breakout
        df8 = df8[df8.starter == 1]
        # Create a new column 'over_15' which is 1 if true, 0 if false
        df8['over_15'] = (df8['points'] >= 15).astype(int)
        # Now, sum this column for ALL teams
        df8group = dict(df8.groupby('team')['over_15'].sum())

        figWeek8 = px.bar(df8,x='player',y='points',facet_col='team',facet_col_wrap=3, color = 'position', title = f'<b>Side Bet Week {WeekObj.week}</b><br><sup>Players Over 15 pts</sup>',
                    facet_row_spacing=.1)
        figWeek8.update_xaxes(matches=None,showticklabels = False, title = '')
        figWeek8.update_yaxes(title = '')
        figWeek8.update_layout(showlegend = True)

        figWeek8.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
       
        figWeek8.update_layout(margin=dict(t=180, b=100, l=40, r=40))
        figWeek8.update_layout(
                    legend=dict(
                        x=0.5,  # x-coordinate of the legend (0 to 1, where 0 is left and 1 is right)
                        y=1.13,   # y-coordinate of the legend (0 to 1, where 0 is bottom and 1 is top)
                        xanchor="center",  # horizontal anchor point ('left', 'center', 'right')
                        yanchor="top",   # vertical anchor point ('top', 'middle', 'bottom')
                        title = None
                    )
                )
                
        apply_logo_to_fig(figWeek8)
        for annotation in figWeek8.layout.annotations:
                    title_text = annotation.text  # e.g., "Team A vs Team B"
                    #teams = title_text.split(" vs ")  # Split into individual team names
                    # Create a styled title with team names in respective colors
                    annotation.text = f"<span style='color:{self.teamcolors[title_text]}'>{title_text}</span><br>{df8group[title_text]}"
                    annotation.font.size = 23  # Optional: Adjust font size for clarity
        
        figWeek8.add_hline(y=15,line_color = 'red' ,annotation_text='15 pts.')

        return figWeek8

    def Week9(self,WeekObj):
        Week9Setup = WeekObj.Breakout
        Week9Setup = Week9Setup[Week9Setup.starter == 1]
        Week9Setup = Week9Setup[(Week9Setup['rookie_year'] == 2025.0) | (Week9Setup['age']>29.0)]
            
        Week9Setup['Type'] = np.where(Week9Setup['rookie_year'] == 2025.0, 'Young Buck', 'Old Man')

        idx = Week9Setup.groupby(['team','Type'])['points'].idxmax()

        Week9 = Week9Setup.loc[idx]

        Week9['Player_Text'] = '<b>' + Week9['player'] + '</b><br><sup>' + Week9['Type'] + '</sup>'

        figWeek9 = px.bar(Week9, x = 'points', y = 'team', orientation='h', color = 'Type', text = 'Player_Text', title = f'<b>Week {WeekObj.week} Side Bet</b><br><sup>The Old Man & Young Buck</sup>')
        figWeek9.update_layout(yaxis={'categoryorder':'total ascending'})

        figWeek9.update_layout(
                xaxis_title="",  # Set x-axis title
                yaxis_title="")
        
        figWeek9.update_yaxes(
                tickfont=dict(
                    size=22, weight ='bold'       # Font size
                )
            )

        apply_logo_to_fig(figWeek9)
        self.UpdateColors2(WeekObj,figWeek9)
        figWeek9.update_layout(margin=dict(t=160, b=100, l=210, r=40), title ={'y':.93})



        return figWeek9
    
    def Week10(self, WeekObj):
        

        Week10SideBet2 = WeekObj.Breakout.groupby(['team','recent_team'])[['player','points']].sum(numeric_only=True).reset_index()

        Week10SideBet2Data = Week10SideBet2.sort_values('points', ascending=False).head(10)
        Week10SideBet2Data['Name'] = Week10SideBet2Data['team'] + ' - ' + Week10SideBet2Data['recent_team']

        
        Week10SideBet = WeekObj.Breakout.groupby(['team'])[['player','points','recent_team']]
        Week10SideBet2 = WeekObj.Breakout.groupby(['team','recent_team'])[['player','points']].sum(numeric_only=True).reset_index()
        Week10SideBet2Data = Week10SideBet2.sort_values('points', ascending=False).head(10)
        Week10SideBet2Data['Name'] = Week10SideBet2Data['team'] + ' - ' + Week10SideBet2Data['recent_team']

        #grouped = breakoutDF_group.groupby('matchup')
                # Create a subplot with 1 row and 2 columns (for the bar chart and the pie chart)
        figCombo2 = make_subplots(
                    rows=7, cols=2, 
                    shared_xaxes=False,
                    horizontal_spacing=0.04, 
                    vertical_spacing=0.05,
                    shared_yaxes=True,
                    column_widths=[0.5, 0.5],  # Adjust the width of each subplot
                    specs=[[{"type": "bar"}, {"type": "bar"}],
                        [{"type": "bar"}, {"type": "bar"}],
                        [{"type": "bar"}, {"type": "bar"}],
                        [{"type": "bar"}, {"type": "bar"}],
                        [{"type": "bar"}, {"type": "bar"}],
                        [{"type": "bar"}, {"type": "bar"}],
                        [{"colspan":2,"type":"bar"},None]]
                    #subplot_titles=['Matchup Schedule','Win History']# Specify the chart types
                )
        for i in range(1,13):
                person = roster_ids_2025[i]
                CurrentGraph = Week10SideBet.get_group(person)
                rowlist = [1,1,2,2,3,3,4,4,5,5,6,6]
                collist = [1,2,1,2,1,2,1,2,1,2,1,2]
                rowdict = dict(enumerate(rowlist,1))
                coldict = dict(enumerate(collist,1))
                
                # Add the bar chart to the first column
                figCombo2.add_trace(
                    go.Bar(
                        y=CurrentGraph['points'], 
                        x=CurrentGraph['recent_team'], 
                        
                        #marker=dict(
                        #    color = [teamcolors[team] for team in CurrentGraph['team']], 
                        #    cornerradius = 10
                        #),
                        
                        text=CurrentGraph['points'],
                        textangle = 0,
                        textposition='auto',
                        showlegend=False,
                    ),
                    row=rowdict[i], col=coldict[i]
                )

                
                    # Create a custom title with colored team names
                #title_html = f'<span style="color:{teamcolors[teams[0]]}">{teams[0]}</span> vs <span style="color:{teamcolors[teams[1]]}">{teams[1]}</span>'

                # Add the custom title as an annotation at the top of each subplot
                figCombo2.add_annotation(
                    text=roster_ids_2025[i], #,  # The HTML title
                    xref=f'x domain', yref=f'y domain',
                    x=.5, y=1.2,  # Position it above the subplot (y > 1)
                    xanchor='center',
                    font=dict(size=20, weight ='bold'),
                    showarrow=False,
                    row=rowdict[i], col=coldict[i] # Apply to the i-th row and first column (bar chart)
                )
                # Update the layout with dark theme and grouped bar mode
                figCombo2.update_layout(barmode="group", template="gridiron_ink",barcornerradius=7)
                figCombo2.update_xaxes(
                    categoryorder="array",
                    side = 'bottom',
                    #categoryarray=time_order,
                    showticklabels = True, 
                    row=rowdict[i], col=coldict[i]  # Apply to the bar chart in the i-th row and first column
                )
                figCombo2.update_layout(yaxis1=dict(range=[0, 55]),yaxis2=dict(range=[0, 55]),yaxis3=dict(range=[0, 55]),yaxis4=dict(range=[0, 55]),
                                        yaxis5=dict(range=[0, 55]),yaxis6=dict(range=[0, 55]),yaxis7=dict(range=[0, 55]),yaxis8=dict(range=[0, 55]),
                                        yaxis9=dict(range=[0, 55]),yaxis10=dict(range=[0, 55]),yaxis11=dict(range=[0, 55]),yaxis12=dict(range=[0, 55])
                                        )
                figCombo2.update_layout(xaxis1=dict(tickangle=90),xaxis2=dict(tickangle=90),xaxis3=dict(tickangle=90),xaxis4=dict(tickangle=90),
                                        xaxis5=dict(tickangle=90),xaxis6=dict(tickangle=90),xaxis7=dict(tickangle=90),xaxis8=dict(tickangle=90),
                                        xaxis9=dict(tickangle=90),xaxis10=dict(tickangle=90),xaxis11=dict(tickangle=90),xaxis12=dict(tickangle=90)
                                        )
        figCombo2.add_trace(
                    go.Bar(
                        y=Week10SideBet2Data['points'], 
                        x=Week10SideBet2Data['Name'], 
                        marker_color = ('teal','tomato','tomato','tomato','tomato','tomato','tomato','tomato','tomato','tomato'),
                        
                        #marker=dict(
                        #    color = [teamcolors[team] for team in CurrentGraph['team']], 
                        #    cornerradius = 10
                        #),
                        
                        text=Week10SideBet2Data['recent_team'],
                        textangle = 0,
                        textposition='auto',
                        showlegend=False,
                        
                    ),
                    row=7, col=1
                )
        figCombo2.update_xaxes(
                    side = 'bottom',
                    tickfont = dict(size=15),
                    tickangle = -90
                    )
        
        figCombo2.update_layout(width=900, height=1200,title_text=f"<b>Week {WeekObj.week} Side Bet</b><br><sup>Franchise Week</sup>")
        apply_logo_to_fig(figCombo2,yval = -0.09)
        # self.UpdateColors2(WeekObj,figCombo2)
        figCombo2.update_layout(margin=dict(t=160, b=180, l=40, r=40), title ={'y':.93})

        return figCombo2
    
    def Week12(self,WeekObj):
        df = WeekObj.Breakout
        Week12Graph = df[df['starter']==1]
        Week12Graph = Week12Graph[Week12Graph.position == 'QB']

        cols = ['team','player','completions', 'attempts', 'recent_teams']

        Week12Simple = Week12Graph[cols]
        Week12Simple['CompletionPercent'] = round(Week12Simple['completions'] / Week12Simple['attempts'] * 100,1)
        Week12Simple = Week12Simple.sort_values('CompletionPercent', ascending=False)
        Week12Simple['GraphText'] = Week12Simple.CompletionPercent.astype(str) + '% - ' + Week12Simple.player + ' (' + Week12Simple.recent_teams + ')'

        Week12Simple['color'] = Week12Simple.team.map(WeekObj.teamcolors)
        
        

        figQBComplete = go.Figure()
        
        figQBComplete.update_layout(title_text=f"<b>Week {WeekObj.week} Side Bet</b><br><sup>Best Completion %</sup>")


        figQBComplete.add_trace(go.Bar(
            x=Week12Simple.attempts,
            y=Week12Simple.team,
            name='Trace 1', 
            marker_color = Week12Simple.color,
            orientation='h',
            opacity=.65,
            text=Week12Simple.attempts,
            textposition='outside',
            textfont=dict(size = 24)

            
        ))

        figQBComplete.add_trace(go.Bar(
            x=Week12Simple.completions,
            y=Week12Simple.team,
            name='Trace 2',
            marker_color = Week12Simple.color,
            orientation='h',
            opacity=.5,
            text=Week12Simple.completions,
            textposition='outside',
            textfont=dict(size = 24)


            )
        )

        figQBComplete.add_trace(go.Bar(
            x=-Week12Simple.CompletionPercent,
            y=Week12Simple.team,
            name='Trace 3',
            marker_color = Week12Simple.color,
            orientation='h',
            opacity=.9,
            text=Week12Simple.GraphText,
            textposition='inside',
            textfont=dict(size = 24)

            )
        )
        figQBComplete.update_layout(yaxis3={'categoryorder': 'total ascending'})


        figQBComplete.update_layout(barmode='overlay', showlegend=False)
        figQBComplete.update_layout(
            xaxis=dict(
                tickmode='array',
                tickvals=[-80, -60, -40, -20,0,20,40,60],
                ticktext=['80%', '60%', '40%', '20%', '0','20 ATT','40 ATT']
            )
        )
        figQBComplete.update_yaxes(
                tickfont=dict(
                    size=22,         # Font size
                ),
                title=None
            )
        figQBComplete.update_layout(
            xaxis=dict(
                side="top"
            )
        )
        figQBComplete.update_layout(
            font=dict(
                size=22,  # Set the font size here
            )
        )
        

        figQBComplete.update_traces(marker_line_width=1.5,marker_line_color='black')

        apply_logo_to_fig(figQBComplete,xval=.43)
        self.UpdateColors2(WeekObj,figQBComplete)
        figQBComplete.update_layout(margin=dict(t=140, l=220, r=40), title ={'y':.93})

        return figQBComplete
    
    def Week13(self, WeekObj):
        dfWeek13 = WeekObj.WeeklyNoMatches.reset_index()
        dfWeek13 =dfWeek13[dfWeek13['Won'] == 1]
        dfWeek13['Abs Margin'] = dfWeek13.Margin.abs().round(0)
        dfWeek13['TeamName'] = dfWeek13.Margin.round(1).astype(str) + ' points over ' + dfWeek13.Opp_team

        figWeek13 = px.bar(dfWeek13.sort_values('Abs Margin', ascending=False), x='Margin',y='Team',template = 'gridiron_ink',
                           title=f'<b>Week {WeekObj.week}</b><br><sup>Smallest Margin</sup>', color = 'Matchup', orientation='h', text='TeamName' )
        #figWeek13.update_layout(barmode='stack', yaxis={'categoryorder':'mean ascending'})
        figWeek13.update_layout(width=1200, height=800)

        figWeek13.update_traces(textfont_size=25, textangle=0, cliponaxis=True, textposition = 'auto', textfont=dict(weight='bold',  # Font family
                    size=25   # Font color
                ))
        figWeek13.update_layout(
                xaxis_title="Margin",  # Set x-axis title
                yaxis_title="Winners",   # Set y-axis title
                xaxis=dict(
                    title_font=dict(
                        size=30,          # Set font size for x-axis title
                        weight = 'bold'
                    )
                ),
                yaxis=dict(
                    title_font=dict(
                        size=30,          # Set font size for y-axis title
                        weight = 'bold'
                    )
                )
            )
        figWeek13.update_layout(yaxis=dict(showticklabels=True))
        #Update the layout to hide the legend:
        figWeek13.update(layout_coloraxis_showscale=False)
        figWeek13.update_yaxes(
                tickfont=dict(
                    size=25, weight = 'bold'         # Font size
                ))
        figWeek13.update_xaxes(
                tickfont=dict(
                    size=22,         # Font size
                ),
                title = None,dtick = 25
            )
        apply_logo_to_fig(figWeek13,xval=.43)
        self.UpdateColors2(WeekObj,figWeek13)
        figWeek13.update_layout( title ={'y':.93})
        figWeek13.update_layout(margin=dict(t=140, l=220, r=40))


        return figWeek13

# Reading in Data from API

## Creating Leagues

In [28]:
League_2019 = League(2019,leagueID_2019)
League_2020 = League(2020,leagueID_2020)
League_2021 = League(2021,leagueID_2021)
League_2022 = League(2022,leagueID_2022)
League_2023 = League(2023,leagueID_2023)
League_2024 = League(2024,leagueID_2024)
League_2025 = League(2025,leagueID_2025)

Downcasting floats.
League for 2019 created.
Downcasting floats.
League for 2020 created.
Downcasting floats.
League for 2021 created.
Downcasting floats.
League for 2022 created.
Downcasting floats.
League for 2023 created.
Downcasting floats.
League for 2024 created.

/var/folders/xg/y9j6k4pn725g1jx4yx1dfv2m0000gn/T/ipykernel_94174/3005090329.py:16: DtypeWarning:

Columns (98) have mixed types. Specify dtype option on import or set low_memory=False.

League for 2025 created.

## Creating Survivor League

In [29]:
Survivor_2024 = League(2024,Survivor_leagueID_2024)

Downcasting floats.
League for 2024 created.

In [30]:
Surivior_Season_2024 = Survivor(Survivor_2024)

In [31]:
Surivior_Season_2024.ProcessData()

In [32]:
Surivior_Season_2024.Status

,owner_id,eliminated_leg_id,is_eliminated,num_eliminations,Picked,Left
0,464551361732669440,5,true,3,"[CIN, LAC, LV, SF, SEA, None]","[ARI, ATL, BAL, BUF, CAR, CHI, CLE, DAL, DEN, ..."
1,868709284874182656,5,true,3,"[CIN, KC, TB, SF, SEA, None]","[ARI, ATL, BAL, BUF, CAR, CHI, CLE, DAL, DEN, ..."
2,464832051451785216,5,true,3,"[CIN, BAL, KC, DET, SEA, None]","[ARI, ATL, BUF, CAR, CHI, CLE, DAL, DEN, GB, H..."
3,464565465964867584,3,true,3,"[ATL, BAL, CLE, None]","[ARI, BUF, CAR, CHI, CIN, DAL, DEN, DET, GB, H..."
4,608059974358200320,4,true,3,"[CIN, LAC, TB, NYJ, None]","[ARI, ATL, BAL, BUF, CAR, CHI, CLE, DAL, DEN, ..."
5,465743483693428736,14,false,4,"[CIN, LAC, NYJ, SF, SEA, HOU, WAS, DEN, PHI, C...","[BAL, BUF, CAR, CLE, DAL, DET, GB, IND, JAX, K..."
6,867944967480459264,14,false,3,"[SEA, PIT, LV, SF, WAS, HOU, IND, DEN, CIN, CH...","[BAL, BUF, CAR, CLE, DAL, DET, JAX, KC, LAR, M..."
7,732955301963227136,4,true,3,"[CIN, HOU, CLE, NYJ, None]","[ARI, ATL, BAL, BUF, CAR, CHI, DAL, DEN, DET, ..."
8,465621897623629824,1,true,1,"[CIN, None]","[ARI, ATL, BAL, BUF, CAR, CHI, CLE, DAL, DEN, ..."
9,464835149461188608,1,true,1,"[CIN, None]","[ARI, ATL, BAL, BUF, CAR, CHI, CLE, DAL, DEN, ..."

In [33]:
Surivior_Season_2024.Data.groupby('owner_id')['team_pick'].unique()

owner_id
464551361732669440                        [CIN, LAC, LV, SF, SEA, None]
464565465964867584                                [ATL, BAL, CLE, None]
464832051451785216                       [CIN, BAL, KC, DET, SEA, None]
464835149461188608                                          [CIN, None]
465621897623629824                                          [CIN, None]
465743483693428736    [CIN, LAC, NYJ, SF, SEA, HOU, WAS, DEN, PHI, C...
608059974358200320                            [CIN, LAC, TB, NYJ, None]
732955301963227136                           [CIN, HOU, CLE, NYJ, None]
867944967480459264    [SEA, PIT, LV, SF, WAS, HOU, IND, DEN, CIN, CH...
868709284874182656                         [CIN, KC, TB, SF, SEA, None]
Name: team_pick, dtype: object

## Creating Pick Em League

In [34]:
League_PickEm_2025 = League(2025, '1263903606336139264')

/var/folders/xg/y9j6k4pn725g1jx4yx1dfv2m0000gn/T/ipykernel_94174/3005090329.py:16: DtypeWarning:

Columns (98) have mixed types. Specify dtype option on import or set low_memory=False.

League for 2025 created.

In [35]:
PickEm_2025 = PickEm(League_PickEm_2025)

In [36]:
PickEm_2025.Graph()

## Creating Seasons

In [37]:
Season_2019 = Season(League_2019)
Season_2020 = Season(League_2020)
Season_2021 = Season(League_2021)
Season_2022 = Season(League_2022)
Season_2023 = Season(League_2023)
Season_2024 = Season(League_2024)
Season_2025 = Season(League_2025)

Season for 2019 created.
Season for 2020 created.
Season for 2021 created.
Season for 2022 created.
Season for 2023 created.
Season for 2024 created.
Season for 2025 created.

In [38]:
# Survivor_Week1_2024 = Week(1, Survivor_2024,)

In [39]:
Season_Dict = {2019:Season_2019, 2020:Season_2020, 2021:Season_2021, 2022:Season_2022, 2023:Season_2023, 2024:Season_2024, 2025:Season_2025}

## Creating Weeks

### 2019

In [40]:
Week1_2019 = Week(1,League_2019)
Week2_2019 = Week(2,League_2019)
Week3_2019 = Week(3,League_2019)
Week4_2019 = Week(4,League_2019)
Week5_2019 = Week(5,League_2019)
Week6_2019 = Week(6,League_2019)
Week7_2019 = Week(7,League_2019)
Week8_2019 = Week(8,League_2019)
Week9_2019 = Week(9,League_2019)
Week10_2019 = Week(10,League_2019)
Week11_2019 = Week(11,League_2019)
Week12_2019 = Week(12,League_2019)
Week13_2019 = Week(13,League_2019)
Week14_2019 = Week(14,League_2019)
Week15_2019 = Week(15,League_2019)
Week16_2019 = Week(16,League_2019)
Week17_2019 = Week(17,League_2019)

### 2020

In [41]:
Week1_2020 = Week(1,League_2020)
Week2_2020 = Week(2,League_2020)
Week3_2020 = Week(3,League_2020)
Week4_2020 = Week(4,League_2020)
Week5_2020 = Week(5,League_2020)
Week6_2020 = Week(6,League_2020)
Week7_2020 = Week(7,League_2020)
Week8_2020 = Week(8,League_2020)
Week9_2020 = Week(9,League_2020)
Week10_2020 = Week(10,League_2020)
Week11_2020 = Week(11,League_2020)
Week12_2020 = Week(12,League_2020)
Week13_2020 = Week(13,League_2020)
Week14_2020 = Week(14,League_2020)
Week15_2020 = Week(15,League_2020)
Week16_2020 = Week(16,League_2020)
Week17_2020 = Week(17,League_2020)

### 2021

In [42]:
Week1_2021 = Week(1,League_2021)
Week2_2021 = Week(2,League_2021)
Week3_2021 = Week(3,League_2021)
Week4_2021 = Week(4,League_2021)
Week5_2021 = Week(5,League_2021)
Week6_2021 = Week(6,League_2021)
Week7_2021 = Week(7,League_2021)
Week8_2021 = Week(8,League_2021)
Week9_2021 = Week(9,League_2021)
Week10_2021 = Week(10,League_2021)
Week11_2021 = Week(11,League_2021)
Week12_2021 = Week(12,League_2021)
Week13_2021 = Week(13,League_2021)
Week14_2021 = Week(14,League_2021)
Week15_2021 = Week(15,League_2021)
Week16_2021 = Week(16,League_2021)
Week17_2021 = Week(17,League_2021)
Week18_2021 = Week(18,League_2021)

### 2022

In [43]:
Week1_2022 = Week(1,League_2022)
Week2_2022 = Week(2,League_2022)
Week3_2022 = Week(3,League_2022)
Week4_2022 = Week(4,League_2022)
Week5_2022 = Week(5,League_2022)
Week6_2022 = Week(6,League_2022)
Week7_2022 = Week(7,League_2022)
Week8_2022 = Week(8,League_2022)
Week9_2022 = Week(9,League_2022)
Week10_2022 = Week(10,League_2022)
Week11_2022 = Week(11,League_2022)
Week12_2022 = Week(12,League_2022)
Week13_2022 = Week(13,League_2022)
Week14_2022 = Week(14,League_2022)
Week15_2022 = Week(15,League_2022)
Week16_2022 = Week(16,League_2022)
Week17_2022 = Week(17,League_2022)
Week18_2022 = Week(18,League_2022)

### 2023

In [44]:
Week1_2023 = Week(1,League_2023)
Week2_2023 = Week(2,League_2023)
Week3_2023 = Week(3,League_2023)
Week4_2023 = Week(4,League_2023)
Week5_2023 = Week(5,League_2023)
Week6_2023 = Week(6,League_2023)
Week7_2023 = Week(7,League_2023)
Week8_2023 = Week(8,League_2023)
Week9_2023 = Week(9,League_2023)
Week10_2023 = Week(10,League_2023)
Week11_2023 = Week(11,League_2023)
Week12_2023 = Week(12,League_2023)
Week13_2023 = Week(13,League_2023)
Week14_2023 = Week(14,League_2023)
Week15_2023 = Week(15,League_2023)
Week16_2023 = Week(16,League_2023)
Week17_2023 = Week(17,League_2023)
Week18_2023 = Week(18,League_2023)

### 2024

In [45]:
Week1_2024 = Week(1,League_2024)
Week2_2024 = Week(2,League_2024)
Week3_2024 = Week(3,League_2024)
Week4_2024 = Week(4,League_2024)
Week5_2024 = Week(5,League_2024)
Week6_2024 = Week(6,League_2024)
Week7_2024 = Week(7,League_2024)
Week8_2024 = Week(8,League_2024)
Week9_2024 = Week(9,League_2024)
Week10_2024 = Week(10,League_2024)
Week11_2024 = Week(11,League_2024)
Week12_2024 = Week(12,League_2024)
Week13_2024 = Week(13,League_2024)
Week14_2024 = Week(14,League_2024)
Week15_2024 = Week(15,League_2024)
Week16_2024 = Week(16,League_2024)
Week17_2024 = Week(17,League_2024)
Week18_2024 = Week(18,League_2024)

### 2025

In [46]:
Week1_2025 = Week(1,League_2025)
Week2_2025 = Week(2,League_2025)
Week3_2025 = Week(3,League_2025)
Week4_2025 = Week(4,League_2025)
Week5_2025 = Week(5,League_2025)
Week6_2025 = Week(6,League_2025)
Week7_2025 = Week(7,League_2025)
Week8_2025 = Week(8,League_2025)
Week9_2025 = Week(9,League_2025)
Week10_2025 = Week(10,League_2025)
Week11_2025 = Week(11,League_2025)
Week12_2025 = Week(12,League_2025)
Week13_2025 = Week(13,League_2025)
Week14_2025 = Week(14,League_2025)
Week15_2025 = Week(15,League_2025)
Week16_2025 = Week(16,League_2025)
Week17_2025 = Week(17,League_2025)
Week18_2025 = Week(18,League_2025)

## Update Seasons to add Weeks

In [47]:
Season_2019.Update()
Season_2020.Update()
Season_2021.Update()
Season_2022.Update()
Season_2023.Update()
Season_2024.Update()
Season_2025.Update()

Season has been udpated.
Season has been udpated.
Season has been udpated.
Season has been udpated.
Season has been udpated.
Season has been udpated.
Season has been udpated.

## Create Side-Bet

In [48]:
SideBet2025 = SideBet(League_2025, Season_2025)

## Creating All-Time

In [49]:
All_Time = AllTime()

In [50]:
All_Time.Matches

,Team,QB,RB1,RB2,WR1,WR2,TE,WRT,K,DEF,...,Opp,Margin,Week,Season,Week Index,Year,LeagueTotal,PercentTotal,Opp_team,Abs Margin
0,bgmaddox,{'Drew Brees': 24.8},{'David Johnson': 22.7},{'Sony Michel': 1.4},{'JuJu Smith-Schuster': 10.8},{'DJ Moore': 8.1},{'David Njoku': 11.7},{'Calvin Ridley': 14.4},{'Harrison Butker': 17.0},{'BAL': 15.0},...,113.40,12.50,1,Regular,1,2019,1350.32,9.3,jlglover,12.50
1,jlglover,{'Russell Wilson': 20.6},{'Nick Chubb': 10.0},{'Aaron Jones': 3.4},{'T.Y. Hilton': 24.7},{'Marvin Jones': 8.0},{'Travis Kelce': 10.3},{'Derrick Henry': 28.4},{'Mason Crosby': 4.0},{'NO': 4.0},...,125.90,-12.50,1,Regular,1,2019,1350.32,8.4,bgmaddox,12.50
2,BMoreBallers88,{'Lamar Jackson': 43.56},{'James Conner': 8.5},{'Tevin Coleman': 6.6},{'Odell Beckham': 10.6},{'Tyler Boyd': 10.3},{'Hunter Henry': 8.0},{'Stefon Diggs': 4.7},{'Robbie Gould': 11.0},{'LAC': 1.0},...,114.62,-10.36,1,Regular,1,2019,1350.32,7.7,YouthPastor,10.36
3,YouthPastor,{'Carson Wentz': 31.02},{'Damien Williams': 15.5},{'Devonta Freeman': 1.6},{'DeAndre Hopkins': 27.1},{'Tyler Lockett': 10.9},{'Darren Waller': 10.5},{'Duke Johnson': 11.0},{'Matt Bryant': 0.0},{'NE': 7.0},...,104.26,10.36,1,Regular,1,2019,1350.32,8.5,BMoreBallers88,10.36
4,GurlyGirls,{'Cam Newton': 4.36},{'Saquon Barkley': 14.9},{'James White': 10.7},{'Adam Thielen': 11.8},{'Cooper Kupp': 8.1},{'Vance McDonald': 5.0},{'Josh Jacobs': 23.8},{'Brett Maher': 5.0},{'SEA': 11.0},...,125.52,-30.86,1,Regular,1,2019,1350.32,7.0,SweetDizzzzzle,30.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1311,DirtyCommie,{'Joe Burrow': 24.4},{'Jonathan Taylor': 15.9},{'Chris Rodriguez': 0.0},{'Tetairoa McMillan': 1.0},{'Amon-Ra St. Brown': 10.8},{'AJ Barner': 11.8},{'Stefon Diggs': 19.1},{'Jake Bates': 5.8},{'NE': 6.0},...,138.94,-44.14,17,Playoff,101,2025,1142.92,8.3,BMoreBallers88,44.14
1312,bgmaddox,{'Brock Purdy': 39.92},{'Jahmyr Gibbs': 5.4},{'Breece Hall': 19.9},{'Zay Flowers': 11.0},{'Courtland Sutton': 6.0},{'Taysom Hill': 0.0},{'Tyrone Tracy': 6.2},{'Evan McPherson': 8.7},{'CLE': 8.0},...,101.78,3.34,17,Playoff,101,2025,1142.92,9.2,InfiniteJesse,3.34
1313,InfiniteJesse,{'Dak Prescott': 26.68},{'Chase Brown': 27.6},{'Saquon Barkley': 6.8},{'Quentin Johnston': 12.3},{'Jaxon Smith-Njigba': 11.7},{'Zach Ertz': 0.0},{'Javonte Williams': 11.4},{'Chase McLaughlin': 5.3},{'WAS': 0.0},...,105.12,-3.34,17,Playoff,101,2025,1142.92,8.9,bgmaddox,3.34
1314,jhuntmadd,{'Matthew Stafford': 13.76},{'Woody Marks': 8.0},{'Kenneth Walker': 5.7},{'Justin Jefferson': 5.0},{'Tee Higgins': 7.9},{'Brenton Strange': 6.9},{'D'Andre Swift': 20.9},{'Jason Myers': 10.8},{'LAR': 8.0},...,87.28,-0.32,17,Playoff,101,2025,1142.92,7.6,RossLikeSauce,0.32
1315,RossLikeSauce,{'Bo Nix': 21.48},{'Travis Etienne': 10.2},{'Bucky Irving': 5.8},{'Ja'Marr Chase': 21.5},{'Xavier Worthy': 0.1},{'Dallas Goedert': 8.3},{'Jordan Mason': 0.0},{'Cam Little': 14.9},{'IND': 5.0},...,86.96,0.32,17,Playoff,101,2025,1142.92,7.6,jhuntmadd,0.32

In [51]:
All_Time.Matches.groupby('Week Index')['Total'].sum().reset_index().sort_values('Total', ascending=False)

     Week Index    Total
85           86  2729.20
14           15  2594.50
57           58  2586.08
43           44  2535.82
71           72  2511.00
..          ...      ...
23           24   971.40
27           28   927.62
98           99   895.40
13           14   864.84
100         101   781.32

[101 rows x 2 columns]

In [52]:
All_Time.OppWinPercentageTable()

Opp_team,bgmaddox,jlglover,JTizzzzle,RascalHazard,BMoreBallers88,eegrady,DirtyCommie,jhuntmadd,cosmodromedary,sgmaddox,RossLikeSauce,InfiniteJesse
Team,,,,,,,,,,,,
bgmaddox,,0.55,0.62,0.58,0.62,0.5,0.2,0.18,0.0,0.0,0.64,0.67
jlglover,0.45,,0.44,0.2,0.38,0.82,0.5,0.56,0.0,0.33,0.5,0.0
JTizzzzle,0.38,0.56,,0.5,0.7,0.33,0.71,0.78,0.0,0.2,0.43,0.5
RascalHazard,0.42,0.8,0.5,,0.3,0.88,0.6,0.36,1.0,0.2,0.29,0.5
BMoreBallers88,0.38,0.62,0.3,0.7,,0.36,0.8,0.44,0.0,0.43,0.89,0.67
eegrady,0.5,0.18,0.67,0.12,0.64,,0.38,0.44,1.0,0.62,0.62,0.25
DirtyCommie,0.8,0.5,0.29,0.4,0.2,0.62,,0.83,0.0,0.5,0.17,0.75
jhuntmadd,0.82,0.44,0.22,0.64,0.56,0.56,0.17,,0.0,0.5,0.62,0.25
cosmodromedary,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,,0.5,1.0,0.5
sgmaddox,1.0,0.67,0.8,0.8,0.57,0.38,0.5,0.5,0.5,,0.5,0.67
RossLikeSauce,0.36,0.5,0.57,0.71,0.11,0.38,0.83,0.38,0.0,0.5,,0.6
InfiniteJesse,0.33,1.0,0.5,0.5,0.33,0.75,0.25,0.75,0.5,0.33,0.4,

In [53]:
All_Time.HallofFame_Team()

# Weekly Graphs

## Setup

In [54]:
WeekNum = 17
CurrentWeek = Week17_2025
CurrentSeason = Season_2025

In [55]:
CurrentSeason.BrawnyBench()

In [56]:
CurrentWeek.Breakout

,team,matchup,player,points,starter,position_x,week_x,year,player_name,recent_teams,...,gwfg_made,gwfg_att,gwfg_missed,gwfg_blocked,gwfg_distance,fantasy_points,fantasy_points_ppr,recent_team,week_id_NFL,Game_date_time
0,bgmaddox,4.0,Tyrone Tracy,6.2,1,RB,17,2025,Tyrone Tracy,NYG,...,0.0,0.0,0.0,0.0,0.0,5.7,6.7,NYG,NYG-17,Sunday 4 PM
1,bgmaddox,4.0,Andy Borregales,6.0,0,K,17,2025,Andy Borregales,NE,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NE,NE-17,Sunday 1 PM
2,bgmaddox,4.0,Taysom Hill,0.0,1,TE,17,2025,Taysom Hill,NO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NO,NO-17,Sunday 1 PM
3,bgmaddox,4.0,Courtland Sutton,6.0,1,WR,17,2025,Courtland Sutton,DEN,...,0.0,0.0,0.0,0.0,0.0,4.0,8.0,DEN,DEN-17,Thursday 8 PM
4,bgmaddox,4.0,Evan McPherson,8.7,1,K,17,2025,Evan McPherson,CIN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CIN,CIN-17,Sunday 1 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,InfiniteJesse,4.0,Chase Brown,27.6,1,RB,17,2025,Chase Brown,CIN,...,0.0,0.0,0.0,0.0,0.0,26.1,29.1,CIN,CIN-17,Sunday 1 PM
165,InfiniteJesse,4.0,Jaxon Smith-Njigba,11.7,1,WR,17,2025,Jaxon Smith-Njigba,SEA,...,0.0,0.0,0.0,0.0,0.0,7.2,16.2,SEA,SEA-17,Sunday 1 PM
166,InfiniteJesse,4.0,Quentin Johnston,12.3,1,WR,17,2025,Quentin Johnston,LAC,...,0.0,0.0,0.0,0.0,0.0,9.8,14.8,LAC,LAC-17,Saturday 4 PM
167,InfiniteJesse,4.0,PHI,12.0,0,DEF,17,2025,PHI,PHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 4 PM
168,InfiniteJesse,4.0,WAS,0.0,1,DEF,17,2025,WAS,WAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Thursday 1 PM

## Side Bet

In [57]:
SideBet2025.Week13(CurrentWeek)

## For & Against

In [58]:
CurrentSeason.SeasonPointsForAgainst()

## Points Timeline

In [59]:
CurrentWeek.PointsOverTheWeekend()

In [60]:
Week16_2025.PointsOverTheWeekend()

In [61]:
CurrentWeek.Breakout

,team,matchup,player,points,starter,position_x,week_x,year,player_name,recent_teams,...,gwfg_made,gwfg_att,gwfg_missed,gwfg_blocked,gwfg_distance,fantasy_points,fantasy_points_ppr,recent_team,week_id_NFL,Game_date_time
0,bgmaddox,4.0,Tyrone Tracy,6.2,1,RB,17,2025,Tyrone Tracy,NYG,...,0.0,0.0,0.0,0.0,0.0,5.7,6.7,NYG,NYG-17,Sunday 4 PM
1,bgmaddox,4.0,Andy Borregales,6.0,0,K,17,2025,Andy Borregales,NE,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NE,NE-17,Sunday 1 PM
2,bgmaddox,4.0,Taysom Hill,0.0,1,TE,17,2025,Taysom Hill,NO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NO,NO-17,Sunday 1 PM
3,bgmaddox,4.0,Courtland Sutton,6.0,1,WR,17,2025,Courtland Sutton,DEN,...,0.0,0.0,0.0,0.0,0.0,4.0,8.0,DEN,DEN-17,Thursday 8 PM
4,bgmaddox,4.0,Evan McPherson,8.7,1,K,17,2025,Evan McPherson,CIN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CIN,CIN-17,Sunday 1 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,InfiniteJesse,4.0,Chase Brown,27.6,1,RB,17,2025,Chase Brown,CIN,...,0.0,0.0,0.0,0.0,0.0,26.1,29.1,CIN,CIN-17,Sunday 1 PM
165,InfiniteJesse,4.0,Jaxon Smith-Njigba,11.7,1,WR,17,2025,Jaxon Smith-Njigba,SEA,...,0.0,0.0,0.0,0.0,0.0,7.2,16.2,SEA,SEA-17,Sunday 1 PM
166,InfiniteJesse,4.0,Quentin Johnston,12.3,1,WR,17,2025,Quentin Johnston,LAC,...,0.0,0.0,0.0,0.0,0.0,9.8,14.8,LAC,LAC-17,Saturday 4 PM
167,InfiniteJesse,4.0,PHI,12.0,0,DEF,17,2025,PHI,PHI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 4 PM
168,InfiniteJesse,4.0,WAS,0.0,1,DEF,17,2025,WAS,WAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Thursday 1 PM

## Matchups

In [62]:
CurrentWeek.WeeklyGraph()

In [63]:
Week4_2025.Breakout

,team,matchup,player,points,starter,position_x,week_x,year,player_name,recent_teams,...,gwfg_made,gwfg_att,gwfg_missed,gwfg_blocked,gwfg_distance,fantasy_points,fantasy_points_ppr,recent_team,week_id_NFL,Game_date_time
0,bgmaddox,5,Tre Tucker,3.48,0,WR,4,2025,Tre Tucker,LV,...,0.0,0.0,0.0,0.0,0.0,2.2,4.2,LV,LV-4,Sunday 4 PM
1,bgmaddox,5,Rashee Rice,0.00,0,WR,4,2025,Rashee Rice,KC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 4 PM
2,bgmaddox,5,Brock Bowers,7.10,1,TE,4,2025,Brock Bowers,LV,...,0.0,0.0,0.0,0.0,0.0,4.6,9.6,LV,LV-4,Sunday 4 PM
3,bgmaddox,5,Dylan Sampson,-0.20,0,RB,4,2025,Dylan Sampson,CLE,...,0.0,0.0,0.0,0.0,0.0,-0.2,-0.2,CLE,CLE-4,Sunday 1 PM
4,bgmaddox,5,Cam Skattebo,12.00,1,RB,4,2025,Cam Skattebo,NYG,...,0.0,0.0,0.0,0.0,0.0,11.0,13.0,NYG,NYG-4,Sunday 1 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,InfiniteJesse,3,Javonte Williams,17.50,1,RB,4,2025,Javonte Williams,DAL,...,0.0,0.0,0.0,0.0,0.0,16.0,19.0,DAL,DAL-4,Sunday 8 PM
169,InfiniteJesse,3,Chase Brown,8.60,1,RB,4,2025,Chase Brown,CIN,...,0.0,0.0,0.0,0.0,0.0,7.1,10.1,CIN,CIN-4,Monday 8 PM
170,InfiniteJesse,3,Jaxon Smith-Njigba,11.00,1,WR,4,2025,Jaxon Smith-Njigba,SEA,...,0.0,0.0,0.0,0.0,0.0,9.0,13.0,SEA,SEA-4,Thursday 8 PM
171,InfiniteJesse,3,Quentin Johnston,19.80,0,WR,4,2025,Quentin Johnston,LAC,...,0.0,0.0,0.0,0.0,0.0,15.8,23.8,LAC,LAC-4,Sunday 1 PM
172,InfiniteJesse,3,PIT,9.00,1,DEF,4,2025,PIT,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 9 AM

## Preview

In [64]:
CurrentSeason.MatchupPreview_WinPercentage(WeekNum+1)

KeyError: 1

## Pick Em

In [ ]:
PickEm_2025.Data

               owner_id  week  points  ScoreYTD     owner
0    464551361732669440     0     0.0       0.0  bgmaddox
1    464551361732669440     1    11.0      11.0  bgmaddox
2    464551361732669440     2    16.0      27.0  bgmaddox
3    464551361732669440     3     8.0      35.0  bgmaddox
4    464551361732669440     4     7.0      42.0  bgmaddox
..                  ...   ...     ...       ...       ...
103  867944967480459264    13    10.0     129.0  sgmaddox
104  867944967480459264    14     6.0     135.0  sgmaddox
105  867944967480459264    15    13.0     148.0  sgmaddox
106  867944967480459264    16    10.0     158.0  sgmaddox
107  867944967480459264    17     9.0     167.0  sgmaddox

[108 rows x 5 columns]

In [ ]:
PickEm_2025.Graph()

## Lucky Squares

In [ ]:
CurrentSeason.LuckChart(WeekNum)

## Power Rankings

In [ ]:
CurrentSeason.StatusGraph(CurrentWeek)

## Snake Graph

In [ ]:
CurrentSeason.SnakeGraph(WeekNum)

## Score Trends

In [ ]:
CurrentSeason.PlayerPoints(WeekNum)

## Weekly Wins Breakout

In [ ]:
CurrentSeason.WeeklyWinsGraphBreakout(WeekNum)

## Scoring Frequency

In [ ]:
CurrentSeason.ScoreFrequencyGraph(WeekNum)

## Violin Player

In [ ]:
CurrentSeason.ViolinPlayer(WeekNum, Starters=True)

## Averages

In [ ]:
WeeklyAvg = CurrentSeason.Matches.groupby('Week')['Total'].mean().round(1).reset_index()
WeeklyAvg = WeeklyAvg[WeeklyAvg['Week'] <= WeekNum]
WeeklyAvg

    Week  Total
0      1  102.8
1      2  103.4
2      3  109.3
3      4  112.6
4      5  118.6
5      6  103.4
6      7  106.4
7      8  109.2
8      9  103.2
9     10  110.4
10    11   93.4
11    12  108.2
12    13  101.0
13    14  104.9
14    15  111.9
15    16  109.9
16    17   97.7

In [ ]:
AllTimedf = All_Time.Matches
AllTimedf['Week Year'] = '<b>Week ' + AllTimedf['Week'].astype(str) + '</b><br><sup>' + AllTimedf['Year'].astype(str) + '</sup>'

In [ ]:
AllTimeAvg = AllTimedf.groupby('Week Year')['Total'].mean().round(1).reset_index()
AllTimeAvg = AllTimeAvg[AllTimeAvg['Total']>50]
AllTimeAvg = AllTimeAvg.sort_values('Total',ascending=True).head(10)

In [ ]:
figAllTimeAvg = px.bar(AllTimeAvg,x='Week Year',y='Total',text = 'Total',title = '<b>All-Time League Worst Averages</b>', color = 'Total',color_continuous_scale=px.colors.sequential.Greens)
figAllTimeAvg.update_layout(xaxis = dict(title = '', tickfont = dict(size = 25)),yaxis = dict(title = '', tickfont = dict(size = 25)))
figAllTimeAvg.update_traces(insidetextanchor= 'middle',textfont=dict(
                        size=35, weight = 'bold'))
figAllTimeAvg.layout.coloraxis.showscale = False
apply_logo_to_fig(figAllTimeAvg)
figAllTimeAvg.show()

In [ ]:
figAvg = px.bar(WeeklyAvg,x='Week',y='Total',text = 'Total',title = '<b>Weekly League Average</b>', color = 'Total',color_continuous_scale=px.colors.sequential.Greens)
figAvg.update_layout(xaxis = dict(title = '', tickfont = dict(size = 25)),yaxis = dict(title = '', tickfont = dict(size = 25)))
figAvg.update_traces(insidetextanchor= 'middle',textfont=dict(
                        size=35, weight = 'bold'))
figAvg.layout.coloraxis.showscale = False
apply_logo_to_fig(figAvg)
figAvg.show()

## Polar Plots

In [ ]:
CurrentSeason.PositionStengthPolar()

## SideBet Scoreboard

In [ ]:
CurrentSeason.Matches.groupby(['Team','Won'])['Margin'].mean().reset_index()

              Team  Won     Margin
0   BMoreBallers88    0 -14.448571
1   BMoreBallers88    1  24.726000
2      DirtyCommie    0 -13.880000
3      DirtyCommie    1  16.886667
4    InfiniteJesse    0 -23.422222
5    InfiniteJesse    1  31.088571
6        JTizzzzle    0 -22.132500
7        JTizzzzle    1  26.905000
8     RascalHazard    0 -23.922857
9     RascalHazard    1  36.000000
10   RossLikeSauce    0 -30.697778
11   RossLikeSauce    1  19.397500
12        bgmaddox    0 -27.330000
13        bgmaddox    1  35.787500
14  cosmodromedary    0 -38.988000
15  cosmodromedary    1  21.460000
16         eegrady    0 -25.700000
17         eegrady    1  20.468000
18       jhuntmadd    0 -26.669091
19       jhuntmadd    1  19.340000
20        jlglover    0 -32.896364
21        jlglover    1  19.664000
22        sgmaddox    0 -16.584000
23        sgmaddox    1  26.592727

In [ ]:
SideBet2025.Scoreboard()

In [ ]:
SideBet2025.Tally

              Team  Wins Prize $
6     RascalHazard     0      $0
7    InfiniteJesse     0      $0
9    RossLikeSauce     0      $0
11        jlglover     0      $0
0        JTizzzzle     1     $20
1          eegrady     1     $20
2   cosmodromedary     1     $20
4         sgmaddox     1     $20
8   BMoreBallers88     1     $20
3         bgmaddox     3     $60
5        jhuntmadd     3     $60
10     DirtyCommie     3     $60

## All-Times

### Hall of Fame - Team

In [ ]:
All_Time.HallofFame_Team()

In [ ]:
All_Time.Matches.sort_values('Total', ascending=False)[0:10]

,Team,QB,RB1,RB2,WR1,WR2,TE,WRT,K,DEF,...,Margin,Week,Season,Week Index,Year,LeagueTotal,PercentTotal,Opp_team,Abs Margin,Week Year
251,BMoreBallers88,{'Deshaun Watson': 28.16},{'Alvin Kamara': 18.8},{'Todd Gurley': 20.2},{'Davante Adams': 38.1},{'Tyler Lockett': 45.5},{'Dalton Schultz': 3.2},{'Tyler Boyd': 22.24},{'Michael Badgley': 7.0},{'KC': 21.0},...,124.52,7,Regular,21,2020,1184.92,17.2,JTizzzzle,124.52,<b>Week 7</b><br><sup>2020</sup>
755,RReclam,{'Jalen Hurts': 21.88},{'James Cook': 12.2},{'Raheem Mostert': 41.7},{'Justin Jefferson': 24.4},{'Keenan Allen': 37.46},{'Hunter Henry': 2.7},{'Kenneth Walker': 29.1},{'Jake Moody': 11.5},{'CLE': 14.0},...,89.56,3,Regular,59,2023,1415.86,13.8,DirtyCommie,89.56,<b>Week 3</b><br><sup>2023</sup>
55,eegrady,{'Matt Ryan': 34.9},{'Joe Mixon': 11.4},{'Leonard Fournette': 21.7},{'William Fuller': 45.7},{'Robert Woods': 7.3},{'Delanie Walker': 1.5},{'Austin Ekeler': 13.8},{'Justin Tucker': 16.0},{'PHI': 35.0},...,103.76,5,Regular,5,2019,1421.22,13.2,BMoreBallers88,103.76,<b>Week 5</b><br><sup>2019</sup>
332,BMoreBallers88,{'Deshaun Watson': 30.76},{'Alvin Kamara': 54.7},{'Le'Veon Bell': 4.4},{'Davante Adams': 37.7},{'Tyler Lockett': 5.9},{'Mark Andrews': 10.6},{'Jeff Wilson': 26.9},{'Younghoe Koo': 1.0},{'BAL': 11.0},...,40.84,16,Playoff,30,2020,1231.46,14.9,SweetDizzzzzle,40.84,<b>Week 16</b><br><sup>2020</sup>
1095,jhuntmadd,{'Jared Goff': 50.06},{'Breece Hall': 12.1},{'Isaac Guerendo': 9.5},{'Davante Adams': 38.3},{'Mike Evans': 32.4},{'Brock Bowers': 5.0},{'Jaxon Smith-Njigba': 13.3},{'Cameron Dicker': 6.1},{'MIN': 9.0},...,80.12,15,Playoff,85,2024,1403.96,12.5,BMoreBallers88,80.12,<b>Week 15</b><br><sup>2024</sup>
1066,eegrady,{'Jayden Daniels': 34.4},{'Jahmyr Gibbs': 23.4},{'Saquon Barkley': 44.2},{'Jakobi Meyers': 17.1},{'Michael Pittman': 12.6},{'T.J. Hockenson': 14.9},{'George Kittle': 17.2},{'Jason Sanders': 11.2},{'Missing': 0.0},...,65.98,12,Regular,82,2024,1298.88,13.5,sgmaddox,65.98,<b>Week 12</b><br><sup>2024</sup>
59,RossLikeSauce,{'Tom Brady': 29.92},{'Todd Gurley': 16.2},{'Chris Carson': 18.8},{'Michael Thomas': 35.7},{'Amari Cooper': 34.1},{'O.J. Howard': 1.5},{'Allen Robinson': 25.2},{'Ka'imi Fairbairn': 11.0},{'DAL': 1.0},...,68.60,5,Regular,5,2019,1421.22,12.2,RascalHazard,68.60,<b>Week 5</b><br><sup>2019</sup>
91,BMoreBallers88,{'Matthew Stafford': 29.38},{'James Conner': 22.5},{'Latavius Murray': 32.2},{'Stefon Diggs': 14.8},{'Kenny Stills': 3.7},{'Hunter Henry': 6.7},{'Tevin Coleman': 36.8},{'Robbie Gould': 9.0},{'SF': 18.0},...,75.38,8,Regular,8,2019,1420.28,12.2,RascalHazard,75.38,<b>Week 8</b><br><sup>2019</sup>
1181,sgmaddox,{'Sam Darnold': 24.0},{'Josh Jacobs': 29.5},{'James Cook': 8.7},{'Emeka Egbuka': 3.4},{'George Pickens': 27.3},{'Sam LaPorta': 14.0},{'Rico Dowdle': 30.9},{'Cameron Dicker': 18.3},{'LAR': 16.0},...,76.72,6,Regular,90,2025,1241.24,13.9,bgmaddox,76.72,<b>Week 6</b><br><sup>2025</sup>
556,RascalHazard,{'Lamar Jackson': 47.42},{'Derrick Henry': 22.8},{'David Montgomery': 1.1},{'Marquise Brown': 21.0},{'DeVonta Smith': 27.38},{'Mark Andrews': 24.9},{'Miles Sanders': 4.9},{'Daniel Carlson': 9.8},{'DAL': 10.0},...,36.00,3,Regular,45,2022,1206.10,14.0,eegrady,36.00,<b>Week 3</b><br><sup>2022</sup>

### Hall of Fame - Player

In [ ]:
All_Time.HallofFame_Player()

### Biggest Losers

In [ ]:
All_Time.HighestScoringLosers()

# Testing

In [ ]:
League_2025.Teams.values()

dict_values(['bgmaddox', 'jlglover', 'RascalHazard', 'BMoreBallers88', 'eegrady', 'RossLikeSauce', 'JTizzzzle', 'jhmad', 'InfiniteJess', 'sgmaddox', 'DirtyCommie', 'cosmodromedary'])

In [66]:

Integer_Cols = ["Side Bet - Solo",	"Side Bet - Split","Side Bet Champion"	, "Survivor Champion",'Pick Em Champion',	"Top Scores",	"Bottom Winner"	,
              "3rd",	"Runner-Up"	, "League Champion", 'Money Haul']

Money_Cols = ["Team","Side Bet - Solo",	"Side Bet - Split","Side Bet Champion"	, "Survivor Champion",'Pick Em Champion',	"Top Scores",	"Bottom Winner"	,
              "3rd Place",	"Runner-Up"	, "League Champion", 'Money Haul']
MoneyDF = pd.DataFrame(columns=Money_Cols, index=League_2025.Teams.values())

MoneyDF.loc['bgmaddox'] = pd.Series({"Side Bet - Solo" : 3,	"Side Bet - Split" : 0,	 "Side Bet Champion" : 1,"Survivor Champion" : 1, "Pick Em Champion": 0,	"Top Scores" : 0,	"Bottom Winner"	: 1,
              "3rd Place" : 0,	"Runner-Up" : 	0, "League Champion" : 0,'Pick Em' : 0})
MoneyDF.loc['jlglover'] = pd.Series({"Side Bet - Solo" : 0,	"Side Bet - Split" : 0,	 "Side Bet Champion" : 0,"Survivor Champion" : 0,"Pick Em Champion": 0,	"Top Scores" : 0,	"Bottom Winner"	: 0,
              "3rd Place" : 0,	"Runner-Up" : 	0, "League Champion" : 0,'Pick Em' : 0})
MoneyDF.loc['RascalHazard'] = pd.Series({"Side Bet - Solo" : 0,	"Side Bet - Split" : 0,	 "Side Bet Champion" : 0,"Survivor Champion" : 0,"Pick Em Champion": 0,	"Top Scores" : 0,	"Bottom Winner"	: 0,
              "3rd Place" : 0,	"Runner-Up" : 	0, "League Champion" : 0,'Pick Em' : 0})
MoneyDF.loc['BMoreBallers88'] = pd.Series({"Side Bet - Solo" : 0,	"Side Bet - Split" : 1,	 "Side Bet Champion" : 0,"Survivor Champion" : 0,"Pick Em Champion": 0,	"Top Scores" : 0,	"Bottom Winner"	: 0,
              "3rd Place" : 1,	"Runner-Up" : 	0, "League Champion" : 0,'Pick Em' : 0})
MoneyDF.loc['eegrady'] = pd.Series({"Side Bet - Solo" : 1,	"Side Bet - Split" : 0,	 "Side Bet Champion" : 0,"Survivor Champion" : 0,"Pick Em Champion": 0,	"Top Scores" : 0,	"Bottom Winner"	: 0,
              "3rd Place" : 0,	"Runner-Up" : 	0, "League Champion" : 0,'Pick Em' : 0})
MoneyDF.loc['RossLikeSauce'] = pd.Series({"Side Bet - Solo" : 1,	"Side Bet - Split" : 0,	 "Side Bet Champion" : 0,"Survivor Champion" : 0,"Pick Em Champion": 0,	"Top Scores" : 0,	"Bottom Winner"	: 0,
              "3rd Place" : 0,	"Runner-Up" : 	0, "League Champion" : 0,'Pick Em' : 0})
MoneyDF.loc['JTizzzzle'] = pd.Series({"Side Bet - Solo" : 1,	"Side Bet - Split" : 0,	 "Side Bet Champion" : 0,"Survivor Champion" : 0,"Pick Em Champion": 0,	"Top Scores" : 0,	"Bottom Winner"	: 0,
              "3rd Place" : 0,	"Runner-Up" : 	0, "League Champion" : 0,'Pick Em' : 0})
MoneyDF.loc['jhmad'] = pd.Series({"Side Bet - Solo" : 1,	"Side Bet - Split" : 2,	 "Side Bet Champion" : 0,"Survivor Champion" : 0,"Pick Em Champion": 0,	"Top Scores" : 0,	"Bottom Winner"	: 0,
              "3rd Place" : 0,	"Runner-Up" : 	0, "League Champion" : 0,'Pick Em' : 0})
MoneyDF.loc['InfiniteJess'] = pd.Series({"Side Bet - Solo" : 0,	"Side Bet - Split" : 0,	 "Side Bet Champion" : 0,"Survivor Champion" : 0,"Pick Em Champion": 0,	"Top Scores" : 0,	"Bottom Winner"	: 0,
              "3rd Place" : 0,	"Runner-Up" : 	0, "League Champion" : 0,'Pick Em' : 0})
MoneyDF.loc['sgmaddox'] = pd.Series({"Side Bet - Solo" : 0,	"Side Bet - Split" : 1,	 "Side Bet Champion" : 0,"Survivor Champion" : 0,"Pick Em Champion": 1,	"Top Scores" : 1,	"Bottom Winner"	: 0,
              "3rd Place" : 0,	"Runner-Up" : 	1, "League Champion" : 0,'Pick Em' : 0})
MoneyDF.loc['DirtyCommie'] = pd.Series({"Side Bet - Solo" : 3,	"Side Bet - Split" : 0,	 "Side Bet Champion" : 0,"Survivor Champion" : 0,"Pick Em Champion": 0,	"Top Scores" : 0,	"Bottom Winner"	: 0,
              "3rd Place" : 0,	"Runner-Up" : 	0, "League Champion" : 0,'Pick Em' : 0})
MoneyDF.loc['cosmodromedary'] = pd.Series({"Side Bet - Solo" : 1,	"Side Bet - Split" : 0,	 "Side Bet Champion" : 0,"Survivor Champion" : 0,"Pick Em Champion": 0,	"Top Scores" : 0,	"Bottom Winner"	: 0,
              "3rd Place" : 0,	"Runner-Up" : 	0, "League Champion" : 1,'Pick Em' : 0})

LeaderboardAmount = 425 - MoneyDF['Top Scores'].sum()*5

MoneyDF['Money Haul'] = (MoneyDF['Side Bet - Solo'] * 20) + (MoneyDF['Side Bet - Split'] * 10) + (MoneyDF['Side Bet Champion'] * 40) + (MoneyDF['Survivor Champion'] * 70) \
                            + (MoneyDF['Top Scores'] * 5) + (MoneyDF['Bottom Winner'] * 25) + (MoneyDF['3rd Place'] * 50) + (MoneyDF['Runner-Up'] * 100) \
                            + (MoneyDF['League Champion'] * LeaderboardAmount)

MoneyDF = MoneyDF.sort_values("Money Haul", ascending = False)

WinningCellValues = [MoneyDF.index, MoneyDF['Side Bet - Solo'], MoneyDF['Side Bet - Split'] , MoneyDF['Side Bet Champion']  , MoneyDF['Survivor Champion'] ,MoneyDF['Pick Em Champion'] ,
                            MoneyDF['Top Scores'] , MoneyDF['Bottom Winner'] , MoneyDF['3rd Place'] , MoneyDF['Runner-Up'] ,
                            MoneyDF['League Champion'], MoneyDF['Money Haul']]

CleanedValues = [
    [val if val != 0 else '' for val in col] 
    for col in WinningCellValues
]

In [67]:
figWinnings = go.Figure(go.Table(
                columnwidth=[1.5, 1, 1],
                header=dict(values=Money_Cols,
                            #fill_color='paleturquoise',
                            align=['center','center'],
                            font=dict(size=18, weight = 'bold', color = 'black'),
                            fill_color='royalblue',
                            line_color='darkslategray', # Darker border for the header
                ),
                cells=dict(values=CleanedValues,
                        align=['left','center'],
                        height = 40,
                        fill_color=[['white', 'lavender'] * len(CleanedValues[0])],
                            font=dict(color='darkslategray', size=14, weight = 'bold'),
                            line_color='lightgrey', # Softer borders for the body
                        #font=dict(color='black', size=14)
                        )
                                        ))

figWinnings.update_layout(
    title_text="Winnings Breakdown",
    margin=dict(l=10, r=10, t=80, b=10), height = 700,
    title = dict(y=.90)
)

figWinnings.show()

In [ ]:
MoneyDF['Money Haul'].sum()

970.0

In [ ]:
CurrentWeek.WeeklyNoMatches

,QB,RB1,RB2,WR1,WR2,TE,WRT,K,DEF,Matchup,...,Won,Opp,Margin,Week,Season,Week Index,Year,LeagueTotal,PercentTotal,Opp_team
Team,,,,,,,,,,,,,,,,,,,,,
cosmodromedary,{'Josh Allen': 22.18},{'Kyren Williams': 14.5},{'Samaje Perine': 7.8},{'Kyle Williams': 3.5},{'Puka Nacua': 13.2},{'Tyler Warren': 6.8},{'Kenneth Gainwell': 6.22},{'Harrison Butker': 11.0},{'DEN': 7.0},1.0,...,1,74.24,17.96,17,Playoff,101,2025,1142.92,8.1,sgmaddox
sgmaddox,{'Trevor Lawrence': 23.12},{'James Cook': 8.2},{'Jaylen Warren': 6.32},{'George Pickens': 9.8},{'Michael Pittman': 2.6},{'Hunter Henry': 12.4},{'Josh Jacobs': 0.8},{'Eddy Pineiro': 6.0},{'TB': 5.0},1.0,...,0,92.20,-17.96,17,Playoff,101,2025,1142.92,6.5,cosmodromedary
BMoreBallers88,{'Drake Maye': 42.44},{'Ashton Jeanty': 8.3},{'Aaron Jones': 13.8},{'Nico Collins': 7.2},{'Mike Evans': 10.6},{'Trey McBride': 18.6},{'Michael Wilson': 17.4},{'Tyler Loop': 10.6},{'DET': 10.0},2.0,...,1,94.80,44.14,17,Playoff,101,2025,1142.92,12.2,DirtyCommie
DirtyCommie,{'Joe Burrow': 24.4},{'Jonathan Taylor': 15.9},{'Chris Rodriguez': 0.0},{'Tetairoa McMillan': 1.0},{'Amon-Ra St. Brown': 10.8},{'AJ Barner': 11.8},{'Stefon Diggs': 19.1},{'Jake Bates': 5.8},{'NE': 6.0},2.0,...,0,138.94,-44.14,17,Playoff,101,2025,1142.92,8.3,BMoreBallers88
bgmaddox,{'Brock Purdy': 39.92},{'Jahmyr Gibbs': 5.4},{'Breece Hall': 19.9},{'Zay Flowers': 11.0},{'Courtland Sutton': 6.0},{'Taysom Hill': 0.0},{'Tyrone Tracy': 6.2},{'Evan McPherson': 8.7},{'CLE': 8.0},4.0,...,1,101.78,3.34,17,Playoff,101,2025,1142.92,9.2,InfiniteJesse
InfiniteJesse,{'Dak Prescott': 26.68},{'Chase Brown': 27.6},{'Saquon Barkley': 6.8},{'Quentin Johnston': 12.3},{'Jaxon Smith-Njigba': 11.7},{'Zach Ertz': 0.0},{'Javonte Williams': 11.4},{'Chase McLaughlin': 5.3},{'WAS': 0.0},4.0,...,0,105.12,-3.34,17,Playoff,101,2025,1142.92,8.9,bgmaddox
jhuntmadd,{'Matthew Stafford': 13.76},{'Woody Marks': 8.0},{'Kenneth Walker': 5.7},{'Justin Jefferson': 5.0},{'Tee Higgins': 7.9},{'Brenton Strange': 6.9},{'D'Andre Swift': 20.9},{'Jason Myers': 10.8},{'LAR': 8.0},5.0,...,0,87.28,-0.32,17,Playoff,101,2025,1142.92,7.6,RossLikeSauce
RossLikeSauce,{'Bo Nix': 21.48},{'Travis Etienne': 10.2},{'Bucky Irving': 5.8},{'Ja'Marr Chase': 21.5},{'Xavier Worthy': 0.1},{'Dallas Goedert': 8.3},{'Jordan Mason': 0.0},{'Cam Little': 14.9},{'IND': 5.0},5.0,...,1,86.96,0.32,17,Playoff,101,2025,1142.92,7.6,jhuntmadd

In [ ]:
# .Barpolar(r=tallyDF['Wins'], theta=tallyDF['Team'],marker_color = neon_future_colorway, text = tallyDF['Team'], showlegend=True)

In [ ]:
BrawnyBench = CurrentSeason.BreakoutSeason

BrawnyBench = BrawnyBench[BrawnyBench.starter == 0]
BrawnyBenchGroup = BrawnyBench.groupby(['team'])['points'].sum().round(0).reset_index().sort_values('points')
BrawnyBenchGroup

figBench = px.bar(BrawnyBenchGroup, x = 'points',y = 'team', text = 'points',title = '<b>Brawny Benches</b>')
figBench.update_layout(margin = dict(l=220),
                       xaxis = dict(title = "",tickfont = dict(size = 22)),
                       yaxis = dict(title = '',tickfont = dict(size = 22)),
                       title = dict(y = 0.91, font= dict(size = 75))
                       )
figBench.update_traces(textposition='inside', textfont_size=80)
figBench.show()

In [ ]:
BestAvg = Season_2025.Matches
BestAvg = BestAvg[BestAvg['Week']<9]
BestAvg.groupby('Team')['Total'].mean().round(1).reset_index().sort_values('Total', ascending=False)

              Team  Total
11        sgmaddox  125.9
1      DirtyCommie  123.2
4     RascalHazard  118.2
6         bgmaddox  112.5
7   cosmodromedary  110.0
0   BMoreBallers88  107.9
2    InfiniteJesse  104.7
3        JTizzzzle  104.5
5    RossLikeSauce  104.0
8          eegrady   97.7
9        jhuntmadd   95.6
10        jlglover   94.4

In [ ]:
Week9Setup = CurrentWeek.Breakout
Week9Setup = Week9Setup[Week9Setup.starter == 1]
Week9Setup = Week9Setup[(Week9Setup['rookie_year'] == 2025.0) | (Week9Setup['age']>29.0)]
    
Week9Setup['Type'] = np.where(Week9Setup['rookie_year'] == 2025.0, 'Young Buck', 'Old Man')

idx = Week9Setup.groupby(['team','Type'])['points'].idxmax()

Week9 = Week9Setup.loc[idx]

Week9['Player_Text'] = '<b>' + Week9['player'] + '</b><br><sup>' + Week9['Type'] + '</sup>'

figWeek9 = px.bar(Week9, x = 'points', y = 'team', orientation='h', color = 'Type', text = 'Player_Text', title = f'<b>Week 9 Side Bet</b><br><sup>The Old Man & Young Buck</sup>')
figWeek9.update_layout(yaxis={'categoryorder':'total ascending'})

figWeek9.show()

In [ ]:
Week9

,team,matchup,player,points,starter,position_x,week_x,year,player_name,recent_teams,...,gwfg_missed,gwfg_blocked,gwfg_distance,fantasy_points,fantasy_points_ppr,recent_team,week_id_NFL,Game_date_time,Type,Player_Text
63,BMoreBallers88,2.0,Aaron Jones,13.80,1,RB,17,2025,Aaron Jones,MIN,...,0.0,0.0,0.0,12.30,15.30,MIN,MIN-17,Thursday 4 PM,Old Man,<b>Aaron Jones</b><br><sup>Old Man</sup>
61,BMoreBallers88,2.0,Tyler Loop,10.60,1,K,17,2025,Tyler Loop,BAL,...,0.0,0.0,0.0,0.00,0.00,BAL,BAL-17,Saturday 8 PM,Young Buck,<b>Tyler Loop</b><br><sup>Young Buck</sup>
89,DirtyCommie,2.0,Stefon Diggs,19.10,1,WR,17,2025,Stefon Diggs,NE,...,0.0,0.0,0.0,16.10,22.10,NE,NE-17,Sunday 1 PM,Old Man,<b>Stefon Diggs</b><br><sup>Old Man</sup>
88,DirtyCommie,2.0,Tetairoa McMillan,1.00,1,WR,17,2025,Tetairoa McMillan,CAR,...,0.0,0.0,0.0,0.50,1.50,CAR,CAR-17,Sunday 1 PM,Young Buck,<b>Tetairoa McMillan</b><br><sup>Young Buck</sup>
158,InfiniteJesse,4.0,Dak Prescott,26.68,1,QB,17,2025,Dak Prescott,DAL,...,0.0,0.0,0.0,22.68,22.68,DAL,DAL-17,Thursday 1 PM,Old Man,<b>Dak Prescott</b><br><sup>Old Man</sup>
28,JTizzzzle,NaN,Brandon Aubrey,17.50,1,K,17,2025,Brandon Aubrey,DAL,...,0.0,0.0,0.0,0.00,0.00,DAL,DAL-17,Thursday 1 PM,Old Man,<b>Brandon Aubrey</b><br><sup>Old Man</sup>
48,RascalHazard,NaN,Chris Boswell,8.40,1,K,17,2025,Chris Boswell,PIT,...,0.0,0.0,0.0,0.00,0.00,PIT,PIT-17,Sunday 1 PM,Old Man,<b>Chris Boswell</b><br><sup>Old Man</sup>
47,RascalHazard,NaN,Quinshon Judkins,0.00,1,RB,17,2025,Quinshon Judkins,CLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 1 PM,Young Buck,<b>Quinshon Judkins</b><br><sup>Young Buck</sup>
147,RossLikeSauce,5.0,Dallas Goedert,8.30,1,TE,17,2025,Dallas Goedert,PHI,...,0.0,0.0,0.0,6.80,9.80,PHI,PHI-17,Sunday 4 PM,Old Man,<b>Dallas Goedert</b><br><sup>Old Man</sup>
2,bgmaddox,4.0,Taysom Hill,0.00,1,TE,17,2025,Taysom Hill,NO,...,0.0,0.0,0.0,0.00,0.00,NO,NO-17,Sunday 1 PM,Old Man,<b>Taysom Hill</b><br><sup>Old Man</sup>
118,cosmodromedary,1.0,Harrison Butker,11.00,1,K,17,2025,Harrison Butker,KC,...,0.0,0.0,0.0,0.00,0.00,KC,KC-17,Thursday 8 PM,Old Man,<b>Harrison Butker</b><br><sup>Old Man</sup>
114,cosmodromedary,1.0,Tyler Warren,6.80,1,TE,17,2025,Tyler Warren,IND,...,0.0,0.0,0.0,4.30,9.30,IND,IND-17,Sunday 1 PM,Young Buck,<b>Tyler Warren</b><br><sup>Young Buck</sup>
70,eegrady,NaN,RJ Harvey,16.10,1,RB,17,2025,RJ Harvey,DEN,...,0.0,0.0,0.0,13.60,18.60,DEN,DEN-17,Thursday 8 PM,Young Buck,<b>RJ Harvey</b><br><sup>Young Buck</sup>
102,jhuntmadd,5.0,Matthew Stafford,13.76,1,QB,17,2025,Matthew Stafford,LA,...,0.0,0.0,0.0,12.76,12.76,LA,LA-17,Monday 8 PM,Old Man,<b>Matthew Stafford</b><br><sup>Old Man</sup>
100,jhuntmadd,5.0,Woody Marks,8.00,1,RB,17,2025,Woody Marks,HOU,...,0.0,0.0,0.0,7.50,8.50,HOU,HOU-17,Saturday 4 PM,Young Buck,<b>Woody Marks</b><br><sup>Young Buck</sup>
20,jlglover,NaN,Derrick Henry,45.60,1,RB,17,2025,Derrick Henry,BAL,...,0.0,0.0,0.0,45.60,45.60,BAL,BAL-17,Saturday 8 PM,Old Man,<b>Derrick Henry</b><br><sup>Old Man</sup>
17,jlglover,NaN,Omarion Hampton,16.00,1,RB,17,2025,Omarion Hampton,LAC,...,0.0,0.0,0.0,12.00,20.00,LAC,LAC-17,Saturday 4 PM,Young Buck,<b>Omarion Hampton</b><br><sup>Young Buck</sup>
128,sgmaddox,1.0,Hunter Henry,12.40,1,TE,17,2025,Hunter Henry,NE,...,0.0,0.0,0.0,10.90,13.90,NE,NE-17,Sunday 1 PM,Old Man,<b>Hunter Henry</b><br><sup>Old Man</sup>

In [ ]:
df6 = Week3_2025.Breakout
df6 = df6[df6.starter == 1]
df6group = df6.groupby('team')['points'].count().reset_index().sort_values('points')

In [ ]:
figWeek8 = px.bar(df6,x='player',y='points',facet_col='team',facet_col_wrap=3, color = 'position', title = '<b>Side Bet Week 9</b><br><sup>Players Over 15 pts</sup>'
                  )
figWeek8.add_hline(y=15,line_color = 'red' ,annotation_text='15 pts.')
figWeek8.update_xaxes(matches=None,showticklabels = False, title = '')
figWeek8.update_yaxes(title = '')
figWeek8.update_layout(showlegend = True)

figWeek8.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
figWeek8.update_layout(margin=dict(t=150, b=100, l=40, r=40))
figWeek8.update_layout(
            legend=dict(
                x=0.5,  # x-coordinate of the legend (0 to 1, where 0 is left and 1 is right)
                y=1.08,   # y-coordinate of the legend (0 to 1, where 0 is bottom and 1 is top)
                xanchor="center",  # horizontal anchor point ('left', 'center', 'right')
                yanchor="top",   # vertical anchor point ('top', 'middle', 'bottom')
                title = None
            )
        )
        
apply_logo_to_fig(figWeek8)
for annotation in figWeek8.layout.annotations:
            title_text = annotation.text  # e.g., "Team A vs Team B"
            #teams = title_text.split(" vs ")  # Split into individual team names
            # Create a styled title with team names in respective colors
            annotation.text = f"<span style='color:{self.teamcolors[title_text]}'>{teams[0]}</span>"
            annotation.font.size = 23  # Optional: Adjust font size for clarity
figWeek8.show()

NameError: name 'self' is not defined

,team,matchup,player,points,starter,position,week_x,year,player_name,recent_teams,...,gwfg_made,gwfg_att,gwfg_missed,gwfg_blocked,gwfg_distance,fantasy_points,fantasy_points_ppr,recent_team,week_id_NFL,Game_date_time
13,bgmaddox,4,Zay Flowers,2.3,1,WR,3,2025,Zay Flowers,BAL,...,0.0,0.0,0.0,0.0,0.0,1.3,3.3,BAL,BAL-3,Monday 8 PM

In [ ]:
maxtest = maxtest[maxtest.points == maxtest.points.min()]

In [ ]:
maxtest

,team,matchup,player,points,starter,position,week_x,year,player_name,recent_teams,...,gwfg_made,gwfg_att,gwfg_missed,gwfg_blocked,gwfg_distance,fantasy_points,fantasy_points_ppr,recent_team,week_id_NFL,Game_date_time
13,bgmaddox,4,Zay Flowers,2.3,1,WR,3,2025,Zay Flowers,BAL,...,0.0,0.0,0.0,0.0,0.0,1.3,3.3,BAL,BAL-3,Monday 8 PM

In [ ]:
df6 = Week6_2025.Breakout
df6 = df6[df6.starter == 1]
df6group = df6.groupby('team')
BustBoom = pd.DataFrame()

for team in df6.team.unique():
    teamdf = df6group.get_group(team)
    maxrow = teamdf[teamdf.points == teamdf.points.max()]
    minrow = teamdf[teamdf.points == teamdf.points.min()]
    teamrows = pd.concat([maxrow,minrow])
    teamrows['difference'] = teamrows.points.sum().round(1)

    BustBoom = pd.concat([BustBoom,teamrows])

BustBoom.sort_values('difference')
figWeek6 = px.bar(BustBoom, y='team',x='points',template = 'gridiron_ink',color = "team", title = f'Week 6 Side Bet', orientation='h',barmode='overlay', text = 'player')


figWeek6.show()

In [ ]:
def UpdateColors(self,fig):
    for annotation in fig.layout.annotations:
                title_text = annotation.text  # e.g., "Team A vs Team B"
                #teams = title_text.split(" vs ")  # Split into individual team names
                # Create a styled title with team names in respective colors
                annotation.text = f"<span style='color:{self.teamcolors[title_text]}'>{title_text}</span>"
            
    return fig

In [ ]:
dfTester = Season_2025.ConcatinatedWeeks
unique_teams = dfTester['Team'].unique()
week_zero_df = pd.DataFrame({
    'Team': unique_teams,
    'Week': 0,
    'Total Wins': 0
})
dfCombo = pd.concat([dfTester,week_zero_df], ignore_index=True,)
dfCombo

,Team,QB,RB1,RB2,WR1,WR2,TE,WRT,K,DEF,...,Season,Week Index,Year,LeagueTotal,PercentTotal,Opp_team,Week Rank,Total Wins,Score YTD,Opp YTD
0,BMoreBallers88,{'Baker Mayfield': 28.58},{'Ashton Jeanty': 11.0},{'Tyrone Tracy': 4.5},{'Nico Collins': 4.0},{'Terry McLaurin': 3.7},{'Trey McBride': 9.1},{'Calvin Ridley': 4.7},{'Tyler Loop': 13.1},{'NE': 6.0},...,Regular,85.0,2025.0,1233.74,6.9,sgmaddox,2.0,0,84.68,127.42
1,sgmaddox,{'Kyler Murray': 22.32},{'Josh Jacobs': 13.5},{'James Cook': 18.7},{'Malik Nabers': 9.6},{'Garrett Wilson': 19.0},{'Sam LaPorta': 10.9},{'Jaylen Warren': 12.9},{'Cameron Dicker': 10.5},{'SF': 10.0},...,Regular,85.0,2025.0,1233.74,10.3,BMoreBallers88,10.0,1,127.42,84.68
2,jlglover,{'Justin Fields': 31.52},{'Derrick Henry': 28.7},{'Omarion Hampton': 7.1},{'Brian Thomas': 8.5},{'Davante Adams': 7.1},{'Colston Loveland': 2.2},{'DeVonta Smith': 3.1},{'Cam Little': 16.6},{'LAR': 12.0},...,Regular,85.0,2025.0,1233.74,9.5,jhuntmadd,8.0,1,116.82,76.78
3,jhuntmadd,{'Brock Purdy': 20.78},{'Kenneth Walker': 3.9},{'D'Andre Swift': 8.0},{'Tee Higgins': 4.8},{'Drake London': 9.5},{'David Njoku': 5.2},{'Justin Jefferson': 12.8},{'Chase McLaughlin': 5.8},{'NYJ': 6.0},...,Regular,85.0,2025.0,1233.74,6.2,jlglover,1.0,0,76.78,116.82
4,eegrady,{'Patrick Mahomes': 28.02},{'Bijan Robinson': 21.4},{'RJ Harvey': 7.4},{'A.J. Brown': 1.3},{'Tyreek Hill': 6.0},{'T.J. Hockenson': 3.0},{'Jerry Jeudy': 9.1},{'Evan McPherson': 5.5},{'HOU': 8.0},...,Regular,85.0,2025.0,1233.74,7.3,DirtyCommie,4.0,0,89.72,91.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,RossLikeSauce,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
224,cosmodromedary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
225,InfiniteJesse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
226,JTizzzzle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
227,RascalHazard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN

In [ ]:
df = Season_2024.Matches
df_group = df.groupby('Team')[['Total','Opp']].sum().round(0)
df_group['Opp'] = df_group['Opp'] * -1
df_group['Dif'] = df_group['Total'] + df_group['Opp']
df_group['Total_Rank'] = df_group['Total'].rank(ascending=False)
df_group['Opp_Rank'] = df_group['Opp'].rank(ascending=True)

df_group.sort_values('Dif',ascending=False)




figTotal = px.bar(df_group.reset_index(),x=['Total','Opp'], y = 'Team', barmode= 'relative', text_auto=True, title=f'<b>For & Against</b>')
figTotal.update_layout( xaxis={'title': None},
                                 yaxis={'categoryorder':'total ascending','title': None}
                                 )
figTotal.update_xaxes(
                tickfont=dict(
                    size=16,         # Font size
                ),
                title = None
            )

            # Customize the y-axis labels
figTotal.update_yaxes(
                tickfont=dict(
                    size=25, weight ='bold'       # Font size
                ),
                title=None
            )
figTotal.update_traces(insidetextanchor= 'middle',textfont=dict(
                size=35, weight = 'bold'))

figTotal.show()

In [ ]:
Season_2025.SeasonPointsForAgainst()

In [ ]:
SideBet2025.Week3(Week2_2025)

In [ ]:
CurrentSeason.PowerRankings(2)

,Team,QB,RB1,RB2,WR1,WR2,TE,WRT,K,DEF,...,PercentTotal,Opp_team,Week Rank,Total Wins,Score YTD,Opp YTD,Power YTD,Power Loss YTD,Win Percentage,Power Ranking
0,jlglover,{'Justin Fields': 2.98},{'Derrick Henry': 1.3},{'Omarion Hampton': 3.0},{'Brian Thomas': 6.9},{'Davante Adams': 19.6},{'Harold Fannin': 7.3},{'DeVonta Smith': 7.3},{'Cam Little': 9.7},{'LAR': 10.0},...,5.5,sgmaddox,0,1,184.90,199.18,8,14,0.363636,9
1,sgmaddox,{'Kyler Murray': 16.0},{'Josh Jacobs': 14.4},{'James Cook': 25.0},{'Malik Nabers': 33.2},{'Garrett Wilson': 6.0},{'Sam LaPorta': 4.1},{'Emeka Egbuka': 10.9},{'Cameron Dicker': 7.8},{'SF': 5.0},...,9.9,jlglover,9,2,249.82,152.76,19,3,0.863636,1
2,BMoreBallers88,{'Baker Mayfield': 22.9},{'Ashton Jeanty': 5.9},{'J.K. Dobbins': 15.0},{'Nico Collins': 12.7},{'Terry McLaurin': 7.3},{'Trey McBride': 10.8},{'Tyrone Tracy': 12.38},{'Tyler Loop': 12.5},{'BAL': 15.0},...,9.2,jhuntmadd,7,1,199.16,210.20,9,13,0.409091,7
3,jhuntmadd,{'Caleb Williams': 20.98},{'Kenneth Walker': 18.3},{'D'Andre Swift': 12.4},{'Tee Higgins': 13.1},{'Justin Jefferson': 9.6},{'David Njoku': 6.0},{'Drake London': 4.4},{'Chase McLaughlin': 2.0},{'DAL': -4.0},...,6.7,BMoreBallers88,2,0,159.56,231.30,3,19,0.136364,12
4,bgmaddox,{'Joe Burrow': 9.04},{'Jahmyr Gibbs': 17.9},{'Breece Hall': 4.8},{'Zay Flowers': 11.4},{'Courtland Sutton': 1.1},{'Brock Bowers': 6.3},{'Dylan Sampson': 9.4},{'Matt Prater': 14.3},{'DET': 8.0},...,6.6,eegrady,1,1,195.26,153.98,8,14,0.363636,9
5,eegrady,{'Patrick Mahomes': 24.08},{'Bijan Robinson': 18.3},{'Zach Charbonnet': 1.0},{'A.J. Brown': 5.2},{'Tyreek Hill': 14.66},{'T.J. Hockenson': 1.7},{'Jerry Jeudy': 7.1},{'Evan McPherson': 7.1},{'HOU': 6.0},...,6.9,bgmaddox,3,1,174.86,173.76,7,15,0.318182,11
6,DirtyCommie,{'Jayden Daniels': 23.7},{'Jonathan Taylor': 28.5},{'James Conner': 11.7},{'Amon-Ra St. Brown': 34.7},{'Deebo Samuel': 17.02},{'Hunter Henry': 1.4},{'Tony Pollard': 9.2},{'Ka'imi Fairbairn': 9.8},{'ARI': 12.0},...,11.9,RossLikeSauce,11,2,239.54,227.00,16,6,0.727273,3
7,RossLikeSauce,{'Jordan Love': 24.88},{'Bucky Irving': 15.1},{'Alvin Kamara': 13.0},{'Ja'Marr Chase': 29.5},{'Mike Evans': 8.1},{'Tucker Kraft': 21.4},{'Travis Etienne': 15.9},{'Jake Bates': 10.4},{'WAS': -1.0},...,11.1,DirtyCommie,10,0,206.12,261.04,10,12,0.454545,6
8,JTizzzzle,{'Jalen Hurts': 10.54},{'De'Von Achane': 22.2},{'Jordan Mason': 4.8},{'CeeDee Lamb': 15.7},{'DJ Moore': 7.1},{'Travis Kelce': 8.1},{'Jakobi Meyers': 9.8},{'Brandon Aubrey': 24.5},{'PHI': 7.0},...,8.8,InfiniteJesse,6,1,218.42,214.30,12,10,0.545455,5
9,InfiniteJesse,{'Dak Prescott': 25.14},{'Saquon Barkley': 16.4},{'Chase Brown': 7.5},{'Marquise Brown': 5.5},{'Jaxon Smith-Njigba': 14.3},{'Chig Okonkwo': 5.5},{'TreVeyon Henderson': 5.0},{'Wil Lutz': 4.0},{'PIT': 4.0},...,7.0,JTizzzzle,5,0,174.38,252.00,8,14,0.363636,9
10,RascalHazard,{'Lamar Jackson': 34.3},{'Christian McCaffrey': 19.7},{'Chuba Hubbard': 16.2},{'Ladd McConkey': 7.3},{'Marvin Harrison': 3.7},{'Mark Andrews': 0.9},{'Chris Olave': 8.4},{'Chris Boswell': 14.1},{'BUF': 12.0},...,9.4,cosmodromedary,8,2,243.56,195.50,17,5,0.772727,2
11,cosmodromedary,{'Josh Allen': 11.82},{'Kyren Williams': 9.0},{'David Montgomery': 12.6},{'Puka Nacua': 23.6},{'DK Metcalf': 9.5},{'Zach Ertz': 15.4},{'Aaron Jones': 2.3},{'Harrison Butker': 7.6},{'DEN': -5.0},...,7.0,RascalHazard,4,1,229.08,203.64,15,7,0.681818,4

In [ ]:
Week1_2025.PointsOverTheWeekend()

In [ ]:
Season_2025.ForAgainstwithTeams()

In [ ]:
HallofShame = All_Time.HallofShame_Team()
HallofShame.add_annotation(
        text="L",
        xref="paper", yref="paper",
        x=1, y=.8, # Position relative to figure (right side, middle)
        showarrow=False,
        font=dict(
            family="Retromoticons",
            size=80,
            color="gold"
        )
        )
HallofShame.show()

In [ ]:
#All_Time.Update()
All_Time.TopScores(Top_Bottom='Top',Team_Player='Team')

In [ ]:
OptScores = pd.concat(OptimalScores2019.values())

In [ ]:
OptScores

,team,matchup,player,points,starter,position,week_x,year,player_name,recent_teams,...,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr,week_id_NFL,Game_date_time,color,starting_position
152,RossLikeSauce,6.0,Christian Kirk,8.40,0,WR,1,2019,Christian Kirk,ARI,...,0.230769,0.257407,0.526339,0.0,6.400000,10.400000,ARI-1,Sunday 4 PM,#54A2E5,FLEX
52,RascalHazard,4.0,Kyler Murray,25.62,0,QB,1,2019,Kyler Murray,ARI,...,NaN,NaN,NaN,0.0,21.620001,21.620001,ARI-1,Sunday 4 PM,#E377C2,QB
0,bgmaddox,1.0,David Johnson,22.70,1,RB,1,2019,David Johnson,ARI,...,0.134615,0.083333,0.260256,0.0,19.700001,25.700001,ARI-1,Sunday 4 PM,#43AA8B,RB
128,SweetDizzzzzle,3.0,Larry Fitzgerald,21.30,0,WR,1,2019,Larry Fitzgerald,ARI,...,0.250000,0.283333,0.573333,0.0,17.299999,25.299999,ARI-1,Sunday 4 PM,#FF7F0E,WR
89,YouthPastor,2.0,Devonta Freeman,1.60,1,RB,1,2019,Devonta Freeman,ATL,...,0.088889,0.031884,0.155652,0.0,1.100000,4.100000,ATL-1,Sunday 1 PM,#9467BD,FLEX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,eegrady,NaN,Austin Seibert,5.00,1,K,17,2019,Austin Seibert,CLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 1 PM,NaN,K
20,jlglover,NaN,Wil Lutz,6.00,1,K,17,2019,Wil Lutz,NO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 1 PM,NaN,K
67,BMoreBallers88,NaN,Lamar Jackson,0.00,1,QB,17,2019,Lamar Jackson,BAL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 4 PM,NaN,QB
86,YouthPastor,NaN,Ryan Griffin,0.00,1,TE,17,2019,Ryan Griffin,TB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 1 PM,NaN,TE
159,JTizzzzle,NaN,Marvin Jones,0.00,1,WR,17,2019,Marvin Jones,DET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 1 PM,NaN,WR

In [ ]:
def OptimalTeams(week):    
    OptimalDF = week.Breakout

    position_counts = {
        'QB': 1, 
        'RB': 2,
        'WR': 2,
        'TE': 1,
        'DEF': 1,
        'K': 1
    }
    # Define which positions are eligible for the FLEX spot
    flex_eligible_positions = ['RB', 'WR', 'TE']

    OptGroups = OptimalDF.groupby(['team', 'position'])
    DreamGroups = OptimalDF.groupby(['position'])
    core_lineup_df = pd.DataFrame()
    dream_lineup_df = pd.DataFrame()

    for name, group in OptGroups:
        position = name[1]
        # Use .get() to safely handle positions not in your dictionary (e.g., FLEX)
        # It will default to 0 if the position isn't found.
        num_players = position_counts.get(position, 0)

        if num_players > 0:
            topPlayers = group.sort_values('points', ascending=False).head(num_players)
            core_lineup_df = pd.concat([core_lineup_df, topPlayers])

    for position, group in DreamGroups:
        position = name[1]
        
        num_players = position_counts.get(position, 0)

        if num_players > 0:
            dreamPlayers = group.sort_values('points', ascending=False).head(num_players)
            dream_lineup_df = pd.concat([dream_lineup_df, dreamPlayers])

    # Create a pool of players who are NOT in the core lineup
    flex_pool_df = OptimalDF.drop(core_lineup_df.index)
    flex_dream_pool_df = OptimalDF.drop(dream_lineup_df.index)

    # Filter this pool to only include FLEX-eligible positions
    flex_pool_df = flex_pool_df[flex_pool_df['position'].isin(flex_eligible_positions)]
    flex_dream_pool_df = flex_dream_pool_df[flex_dream_pool_df['position'].isin(flex_eligible_positions)]

    # For each team, find the single highest-scoring player in the flex_pool_df
    # The .loc[...idxmax()] pattern is a very efficient way to do this
    flex_players_df = flex_pool_df.loc[flex_pool_df.groupby('team')['points'].idxmax()]
    flex_dream_pool_df = flex_dream_pool_df.loc[flex_dream_pool_df['points'].idxmax()]

    # For clarity, let's add a column to show where each player started
    core_lineup_df['starting_position'] = core_lineup_df['position']
    flex_players_df['starting_position'] = 'FLEX'
    dream_lineup_df['starting_position'] = dream_lineup_df['position']
    flex_dream_pool_df['starting_position'] = 'FLEX'

    # Concatenate the two DataFrames to get the final, complete optimal lineup
    final_optimal_lineup = pd.concat([core_lineup_df, flex_players_df])
    final_dream_team = pd.concat([dream_lineup_df, flex_dream_pool_df])

    # Sort for a clean final view
    final_optimal_lineup = final_optimal_lineup.sort_values(
        by=['team', 'starting_position'], 
        ascending=True
    )

    OptimalScoresDict = dict(final_optimal_lineup.groupby('team')['points'].sum().round(2))
    OptimalScoresDF = final_optimal_lineup
    DreamTeamDF = final_dream_team
    return DreamTeamDF

In [ ]:
OptimalTeams(Week10_2019)

/var/folders/xg/y9j6k4pn725g1jx4yx1dfv2m0000gn/T/ipykernel_26420/2849849059.py:30: FutureWarning:

In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.

,team,matchup,player,points,starter,position,week_x,year,player_name,recent_teams,...,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr,week_id_NFL,Game_date_time,color,starting_position,0
130,GurlyGirls,4.0,BAL,23.00,1.0,DEF,10.0,2019.0,BAL,BAL,...,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 1 PM,#F94144,DEF,NaN
159,RossLikeSauce,1.0,PIT,23.00,1.0,DEF,10.0,2019.0,PIT,PIT,...,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 4 PM,#54A2E5,DEF,NaN
6,bgmaddox,1.0,Harrison Butker,14.00,1.0,K,10.0,2019.0,Harrison Butker,KC,...,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 1 PM,#43AA8B,K,NaN
99,YouthPastor,3.0,Matt Gay,14.00,1.0,K,10.0,2019.0,Matt Gay,TB,...,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 1 PM,#9467BD,K,NaN
67,BMoreBallers88,4.0,Lamar Jackson,39.42,1.0,QB,10.0,2019.0,Lamar Jackson,BAL,...,NaN,NaN,0.0,33.419998,33.419998,BAL-10,Sunday 1 PM,#FFC300,QB,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fantasy_points_ppr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0
week_id_NFL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KC-10
Game_date_time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 1 PM
color,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,#8C564B
starting_position,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLEX

In [ ]:
StdDevTest = Season_2019.BreakoutSeason

In [ ]:
PlayerStdDev = StdDevTest.groupby(['player','position'], group_keys=False)['points'].std().round(2).reset_index()

In [ ]:
PlayerStdDev

             player position  points
0        A.J. Brown       WR    3.56
1        A.J. Green       WR    0.00
2               ATL      DEF     NaN
3       Aaron Jones       RB   13.11
4     Aaron Rodgers       QB   12.84
..              ...      ...     ...
273  William Fuller       WR   11.19
274    Younghoe Koo        K    6.36
275       Zach Ertz       TE    7.61
276     Zach Pascal       WR    6.61
277   Zane Gonzalez        K    0.58

[278 rows x 3 columns]

In [ ]:
Draft  = pd.concat([League_2019.Draft(),League_2020.Draft(),League_2021.Draft(),League_2022.Draft(),League_2023.Draft(),League_2024.Draft()])

In [ ]:
Draft

,draft_id,draft_slot,is_keeper,pick_no,picked_by,player_id,reactions,roster_id,round,metadata.first_name,...,metadata.player_id,metadata.position,metadata.sport,metadata.status,metadata.team,metadata.years_exp,player_name,year,metadata.team_abbr,metadata.team_changed_at
0,464552032536096768,1,None,1,465621897623629824,4866,None,GurlyGirls,1,Saquon,...,4866,RB,nfl,Active,NYG,1,Saquon Barkley,2019,NaN,NaN
1,464552032536096768,2,None,2,465635428372836352,4035,None,SweetDizzzzzle,1,Alvin,...,4035,RB,nfl,Active,NO,2,Alvin Kamara,2019,NaN,NaN
2,464552032536096768,3,None,3,465620492519206912,4034,None,BillyRayGonnaGetcha,1,Christian,...,4034,RB,nfl,Active,CAR,2,Christian McCaffrey,2019,NaN,NaN
3,464552032536096768,4,None,4,466655131358720000,3164,None,JTizzzzle,1,Ezekiel,...,3164,RB,nfl,Did Not Report,DAL,3,Ezekiel Elliott,2019,NaN,NaN
4,464552032536096768,5,None,5,464564681915232256,4988,None,jlglover,1,Nick,...,4988,RB,nfl,Active,CLE,1,Nick Chubb,2019,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,1122303756063965185,8,None,164,465743483693428736,96,None,sgmaddox,14,Aaron,...,96,QB,nfl,Active,NYJ,19,Aaron Rodgers,2024,,
164,1122303756063965185,9,None,165,867944967480459264,TB,None,InfiniteJess,14,Tampa Bay,...,TB,DEF,nfl,,TB,,TB,2024,,
165,1122303756063965185,10,None,166,464551361732669440,8132,None,bgmaddox,14,Tyler,...,8132,RB,nfl,Active,ATL,2,Tyler Allgeier,2024,,
166,1122303756063965185,11,None,167,464565465964867584,WAS,None,BMoreBallers88,14,Washington,...,WAS,DEF,nfl,,WAS,,WAS,2024,,
167,1122303756063965185,12,None,168,464835149461188608,2747,None,RReclam,14,Jason,...,2747,K,nfl,Active,SEA,9,Jason Myers,2024,,

In [ ]:
Draft.groupby('player_name')['roster_id'].value_counts()

player_name    roster_id
A.J. Brown     BillyRaySouth    1
               InfiniteJess     1
               RReclam          1
               RascalHazard     1
               YouthPastor      1
                               ..
Zamir White    RReclam          1
               sgmaddox         1
Zane Gonzalez  jhuntmadd        1
Zay Flowers    RascalHazard     1
               bgmaddox         1
Name: roster_id, Length: 880, dtype: int64

In [ ]:
League_2025.player_names['17']

'Matt Prater'

In [ ]:
Week1_2024.Breakout

,team,matchup,player,points,starter,position,week_x,year,player_name,recent_teams,...,racr,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr,week_id_NFL,Game_date_time,color
0,bgmaddox,1,Kirk Cousins,8.20,0,QB,1,2024,Kirk Cousins,ATL,...,NaN,NaN,NaN,NaN,0.0,6.20,6.20,ATL-1,Sunday 1 PM,#9467BD
1,bgmaddox,1,Devaughn Vele,7.90,0,WR,1,2024,Devaughn Vele,DEN,...,2.294118,0.190476,0.064394,0.330790,0.0,3.90,11.90,DEN-1,Sunday 4 PM,#9467BD
2,bgmaddox,1,Derrick Henry,10.60,1,RB,1,2024,Derrick Henry,BAL,...,-0.000000,0.050000,-0.037453,0.048783,0.0,10.60,10.60,BAL-1,Thursday 8 PM,#9467BD
3,bgmaddox,1,Alvin Kamara,19.50,1,RB,1,2024,Alvin Kamara,NO,...,-1.588235,0.208333,-0.081731,0.255288,0.0,17.00,22.00,NO-1,Sunday 1 PM,#9467BD
4,bgmaddox,1,Younghoe Koo,3.40,1,K,1,2024,Younghoe Koo,ATL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 1 PM,#9467BD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,InfiniteJesse,3,Javonte Williams,2.80,1,RB,1,2024,Javonte Williams,DEN,...,0.000000,0.047619,0.003788,0.074080,0.0,2.30,3.30,DEN-1,Sunday 4 PM,#F94144
169,InfiniteJesse,3,Jerome Ford,15.90,0,RB,1,2024,Jerome Ford,CLE,...,1.388889,0.162791,0.048387,0.278057,0.0,12.90,18.90,CLE-1,Sunday 4 PM,#F94144
170,InfiniteJesse,3,De'Von Achane,19.50,1,RB,1,2024,De'Von Achane,MIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday 1 PM,#F94144
171,InfiniteJesse,3,C.J. Stroud,22.66,1,QB,1,2024,C.J. Stroud,HOU,...,NaN,NaN,NaN,NaN,0.0,18.66,18.66,HOU-1,Sunday 1 PM,#F94144
172,InfiniteJesse,3,BAL,3.00,1,DEF,1,2024,BAL,BAL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Thursday 8 PM,#F94144

In [ ]:
League_2024.league_settings

{'name': 'Legacy League',
 'status': 'complete',
 'avatar': '526e9241a4a02943072ebcebbfc61c6c',
 'company_id': None,
 'season': '2024',
 'season_type': 'regular',
 'sport': 'nfl',
 'last_message_id': '1180089464010055680',
 'shard': 824,
 'last_author_avatar': None,
 'last_author_display_name': 'sys',
 'last_author_id': '166666666666666666',
 'last_author_is_bot': True,
 'last_message_attachment': None,
 'last_message_text_map': None,
 'draft_id': '1122303756063965185',
 'last_message_time': 1735717762525,
 'last_pinned_message_id': '1179876074580656128',
 'last_read_id': None,
 'league_id': '1122303756063965184',
 'previous_league_id': '992181788975620096',
 'group_id': None,
 'bracket_id': 1172494500812046336,
 'bracket_overrides_id': None,
 'loser_bracket_id': 1172494500816240641,
 'loser_bracket_overrides_id': None,
 'roster_positions': ['QB',
  'RB',
  'RB',
  'WR',
  'WR',
  'TE',
  'FLEX',
  'K',
  'DEF',
  'BN',
  'BN',
  'BN',
  'BN',
  'BN'],
 'total_rosters': 12,
 'metadata.continued': 'yes',
 'metadata.latest_league_winner_roster_id': '7',
 'metadata.squad_id': '784487100811755520',
 'settings.best_ball': 0,
 'settings.last_report': 14,
 'settings.waiver_budget': 100,
 'settings.disable_adds': 0,
 'settings.capacity_override': 0,
 'settings.taxi_deadline': 0,
 'settings.draft_rounds': 3,
 'settings.reserve_allow_na': 0,
 'settings.start_week': 1,
 'settings.playoff_seed_type': 0,
 'settings.playoff_teams': 6,
 'settings.squads': 1,
 'settings.num_teams': 12,
 'settings.daily_waivers_hour': 0,
 'settings.playoff_type': 1,
 'settings.taxi_slots': 0,
 'settings.last_scored_leg': 17,
 'settings.daily_waivers_days': 1093,
 'settings.playoff_week_start': 15,
 'settings.waiver_clear_days': 2,
 'settings.reserve_allow_doubtful': 0,
 'settings.reserve_allow_dnr': 0,
 'settings.taxi_allow_vets': 0,
 'settings.waiver_day_of_week': 2,
 'settings.playoff_round_type': 0,
 'settings.reserve_allow_out': 1,
 'settings.reserve_allow_sus': 1,
 'settings.trade_deadline': 11,
 'settings.taxi_years': 0,
 'settings.daily_waivers': 0,
 'settings.disable_trades': 0,
 'settings.pick_trading': 0,
 'settings.type': 0,
 'settings.max_keepers': 1,
 'settings.waiver_type': 0,
 'settings.league_average_match': 0,
 'settings.trade_review_days': 2,
 'settings.bench_lock': 1,
 'settings.offseason_adds': 0,
 'settings.leg': 17,
 'settings.reserve_slots': 1,
 'settings.reserve_allow_cov': 1,
 'settings.daily_waivers_last_ran': 3,
 'scoring_settings.sack': 1.0,
 'scoring_settings.fgm_40_49': 0.0,
 'scoring_settings.fgm_yds': 0.1,
 'scoring_settings.pass_int': -2.0,
 'scoring_settings.pts_allow_0': 5.0,
 'scoring_settings.pass_2pt': 2.0,
 'scoring_settings.yds_allow_450_499': -5.0,
 'scoring_settings.st_td': 6.0,
 'scoring_settings.def_pr_yd': 0.0,
 'scoring_settings.pr_td': 6.0,
 'scoring_settings.rec_td': 6.0,
 'scoring_settings.yds_allow_400_449': -3.0,
 'scoring_settings.fgm_30_39': 0.0,
 'scoring_settings.kr_td': 6.0,
 'scoring_settings.xpmiss': -1.0,
 'scoring_settings.rush_td': 6.0,
 'scoring_settings.def_kr_yd': 0.0,
 'scoring_settings.yds_allow_550p': -5.0,
 'scoring_settings.yds_allow_350_399': -1.0,
 'scoring_settings.rec_2pt': 2.0,
 'scoring_settings.pass_int_td': -3.0,
 'scoring_settings.st_fum_rec': 2.0,
 'scoring_settings.fgmiss': 0.0,
 'scoring_settings.ff': 0.0,
 'scoring_settings.rec': 0.5,
 'scoring_settings.yds_allow_200_299': 2.0,
 'scoring_settings.pts_allow_14_20': 1.0,
 'scoring_settings.fgm_0_19': 0.0,
 'scoring_settings.int': 2.0,
 'scoring_settings.def_st_fum_rec': 1.0,
 'scoring_settings.fum_lost': -1.0,
 'scoring_settings.pts_allow_1_6': 4.0,
 'scoring_settings.kr_yd': 0.04,
 'scoring_settings.fgmiss_20_29': -1.0,
 'scoring_settings.fgm_20_29': 0.0,
 'scoring_settings.yds_allow_500_549': -5.0,
 'scoring_settings.pts_allow_21_27': 0.0,
 'scoring_settings.xpm': 1.0,
 'scoring_settings.rec_40p': 0.0,
 'scoring_settings.fgmiss_0_19': -1.0,
 'scoring_settings.rush_2pt': 2.0,
 'scoring_settings.fum_rec': 2.0,
 'scoring_settings.def_st_td': 6.0,
 'scoring_settings.fgm_50p': 0.0,
 'scoring_settings.def_td': 6.0,
 'scoring_settings.rec_td_40p': 0.0,
 'scoring_settings.safe': 2.0,
 'scoring_settings.pass_yd': 0.04,
 'scoring_settings.blk_kick': 2.0,
 'scoring_settings.pass_td': 6.0,
 'scoring_settings.yds_allow_100_199': 3.0,
 'scoring_settings.rush_yd': 0.1,
 'scoring_settings.yds_allow_0_100': 5.0,
 'scoring_settings.rush_40p': 0.0,
 'scoring_settings.pr_yd': 0.04,
 'scoring_settings.fum': -1.0,
 'scoring_settings.pts_allow_28_34': -1.0,
 'scoring_settings.pts_allow_35p': -4.0,
 'scoring_settings.fum_rec_td': 6.0,
 'scoring_settings.rec_yd': 0.1,
 'scoring_settings.rush_td_40p': 0.0,
 'scoring_settings.def_st_ff': 1.0,
 'scoring_settings.pts_allow_7_13': 3.0,
 'scoring_settings.st_ff': 2.0}

In [ ]:
df = Season_2024.Breakout

# Assume 'df' is your DataFrame with player data

# --- Step 1: Create the simplified list of nodes ---
positions = df['position'].unique()
teams = df['team'].unique()

# The new list of labels no longer includes individual players
all_labels = list(positions) + list(teams) + ['Total Points']

# --- Step 2: Create the mapping from label to index ---
label_to_index = {label: i for i, label in enumerate(all_labels)}

# --- Step 3: Build the links ---
source_indices = []
target_indices = []
link_values = []

# Link 1: Position -> Team
pos_team_agg = df.groupby(['position', 'team'])['points'].sum().reset_index()
for index, row in pos_team_agg.iterrows():
    source_indices.append(label_to_index[row['position']])
    target_indices.append(label_to_index[row['team']])
    link_values.append(row['points'])

# Link 2: Team -> Grand Total
team_agg = df.groupby('team')['points'].sum().reset_index()
for index, row in team_agg.iterrows():
    source_indices.append(label_to_index[row['team']])
    target_indices.append(label_to_index['Total Points'])
    link_values.append(row['points'])


# --- Create the Sankey Diagram ---

fig = go.Figure(data=[go.Sankey(
    # Define the nodes
    node=dict(
      pad=25,
      thickness=20,
      line=dict(color="black", width=0.5),
      label=all_labels,
      color="#153045" # Your main color for nodes
    ),
    # Add the links
    link=dict(
      source=source_indices,
      target=target_indices,
      value=link_values
  ))])

fig.update_layout(
    title_text="Fantasy Football Points Flow",
    font_size=12,
    template='gridiron_ink' # Your custom template!
)

fig.show()

AttributeError: 'Season' object has no attribute 'Breakout'